### ISSUE TITLE
Examples/tutorials for custom comparisons

### ISSUE THREAD

**Issue by samnlindsay** [moj-analytical-services/splink#1007]
As far as I can tell, there is no instructional components in the docs for how to:
- build a comparison using `comparison_level_library` functions
- create a custom comparison level directly in SQL

There are DuckDB examples that include these features in the settings, but these are not signposted anywhere and these advanced settings are offered without explanation. 

New users need clear communication that these different levels of customisation are available, and guidance on how to use them (either in the API documentation or in the form of specific tutorials).

For example the [Estimating model parameters](https://moj-analytical-services.github.io/splink/demos/04_Estimating_model_parameters.html) tutorial uses only off-the-shelf `comparison_library` functions, leaving a clear gap in terms of first defining those model parameters being estimated.

**Comment by RobinL** [comment]
Some info here but doesn't cover everything you mention and probably hard to find: https://moj-analytical-services.github.io/splink/topic_guides/customising_comparisons.html

**Comment by samnlindsay** [comment]
Pretty sure this has been addressed by #1041 and subsequent PRs ✅
