### ISSUE TITLE
Bug: Comparison.__deepcopy__() doesn't respect subclassing

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1019]
### What happens?

See https://github.com/moj-analytical-services/splink/pull/992/commits/a9a1d087a7902b305e01edd8091f7993e379ced7. That fix was included in https://github.com/moj-analytical-services/splink/pull/992, but then I dropped it in the v2 of that PR, https://github.com/moj-analytical-services/splink/pull/1018. Some version of this fix needs to happen, but I wanted to break it out into its own PR so it gets the attention it deserves, and since it wasn't actually causing any tests to fail (I don't remember exactly how I even ran across the bug/why I cared lol....)

Does this look like a good solution? I was thinking that all Comparisons should conform to the interface of having both a `to_dict(self)` and `from_dict(cls)` methods.

In an ideal world, if we were starting from scratch, I would make it so that Comparison.__init__() doesn't take a dict as argument, but instead takes an Iterable of ComparisonLevels. The heavy logic would be in the from_dict() class method. This would make it easier for subclassing, because as it is I had to do some gross stuff with __new__. See http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/. But I think that ship has sailed, I don't think we can change the signature of Comparison.__init__ without being breaking for users.

Thoughts??

### To Reproduce

...

### OS:

all

### Splink version:

3.4.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
I think this has changed in Splink4 so closing.  Can be reopened if still an issue
