### ISSUE TITLE
The 'register_table' methods should allow you to pass a string representing a table that's already in the database

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#1022]
At the moment, all of the register table methods assume the user is passing in a pandas dataframe/list of dicts etc.

But there are cases when you want to tell Splink that an already-existing table represents some Splink table such as the labels table, a tf table or whatever.  

That is, the user might want to tell splink that a table called "term_frequencies_first_name" represents the Splink entity: "__splink__df_tf_first_name"

def register_table
def register_table_input_nodes_concat_with_tf
def register_table_predict 
etc.

**Comment by RossKen** [comment]
Think this is resolved
