### ISSUE TITLE
Add some standard date comparison functions to splink api

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1029]
### Is your proposal related to a problem?
Given feedback from databricks session & other users, adding some date comparison functions that are used frequently could be useful. Particularly for dates of birth, you could build in a first of January exception as a parameter. This is currently done through custom SQL but could be made more consistent if we solve it once within the package. Also, if we decide what our 'recommended' ways of comparing dates should be, it is much easier to get users to follow these if there are functions built in.

### Describe the solution you'd like
Perhaps something like
`splink.cl.DateDiff(interval, date_1, date_2, [diff1, diff2])`
e.g. 
`splink.cl.DateDiff(days, "dob_l", "dob_r", [30, 365])`

### Describe alternatives you've considered

Rather than in cl, you could build something simpler in cll

**Comment by ADBond** [comment]
There is a recently-added [datediff comparison level](https://github.com/moj-analytical-services/splink/blob/master/splink/comparison_level_library.py#L405) and associated [comparison](https://github.com/moj-analytical-services/splink/blob/master/splink/comparison_library.py#L418), although I noticed this morning that it does not appear in the documentation (and the documentation around available comparisons/levels is not that readable currently).

**Comment by ADBond** [comment]
I do really like the idea of having a more ready-made dob template (e.g. including 1st Jan/ other exceptions, and having a mix of levenshtein and date comparisons) - think a few of these 'higher-level' ready made comparisons would be very handy (such as full-blown name comparison on forename and surname, with various fuzzy/partial matches and name-switching etc)

**Comment by RossKen** [comment]
Excellent! Tom has just mentioned to me that he added it too which is excellent!

I think the ready-made template is something worth doing so going to leave this issue here as a reminder to do that.

**Comment by RossKen** [comment]
Function added, closing issue
