### ISSUE TITLE
[FEAT] Profile multiple columns simultaneously by supplying a list

### ISSUE THREAD

**Issue by ThomasHepworth** [moj-analytical-services/splink#1034]
This is a feature present in splink2, which we never ported across.

Essentially, this would allow the `profile_columns` method to take a list as an argument, in addition to allowing SQL query that concatenates columns

A working implementation of this for `splink3` can be found [here](https://github.com/moj-analytical-services/splink/compare/concat_profiling).

### To run
```python
from splink.duckdb.duckdb_linker import DuckDBLinker
import pandas as pd

from tests.basic_settings import get_settings_dict

df = pd.read_csv("./tests/datasets/fake_1000_from_splink_demos.csv")

linker = DuckDBLinker(
    df,
    get_settings_dict(),
)


cols_or_exprs = [["first_name", "surname"], "surname"]
linker.profile_columns(cols_or_exprs)
```

Which results in charts where `first_name` and `surname` are separated by spaces:

![Screenshot 2023-02-07 at 20 00 50](https://user-images.githubusercontent.com/45356472/217352494-06971920-e819-4caa-bea6-c6faec24ec23.png)

<hr>

The original implementation in `splink2` can be found [here](https://github.com/moj-analytical-services/splink/blob/v2.1.14/splink/profile.py).

*To do* - add tests to ensure this works as expected.

**Comment by RobinL** [comment]
One thing you need to be careful of here is null handling.

For some reason I don't understand, in duckdb, using the || operator results in a null if any of the concated values are null, which is probably what you want, whereas concat() treats null as blank string. 

Not sure whether this is standard behaviour across dialects

**Comment by ThomasHepworth** [comment]
@RobinL I've added a template for null tests/a test for nulls in duckdb [here](https://github.com/moj-analytical-services/splink/commit/c7fb5e63ee480038f4d9043b2ebd22c0c3b4b076).

I'll let Zoe add some further tests for both duckdb and our various alternate dialects when she gets the time.
