### ISSUE TITLE
adding a column to a dataset and recreating a linker will cause an error

### ISSUE THREAD

**Issue by robertwhiffin** [moj-analytical-services/splink#1052]
### What happens?

The internal tables Splink caches do not get updated when creating a new linker.
Example;

Dataset = (name, address)
Put this into a SparkLinker and go through linking workflow. 

Do feature engineering to create a new dataset of (name, forename, address).
Put this into a SparkLinker and go through linking workflow. 
Get error that forename not found. 

Resolved by dropping Splink's internal tables

Suggested fixes;
Throw an error on linker creation that existing splink tables are present. Add argument to delete  any previous __Splink__ tables when creating a new linker. (pro - prevent accidental dropping of previous work, con, means a single database can only have a single Splink model's data in it)
Add a GUID to splink's internal tables. (pro - can have many splink models working in same dataset. con - proliferation of datasets)

### To Reproduce

Dataset = (name, address)
Put this into a SparkLinker and go through linking workflow. 

Do feature engineering to create a new dataset of (name, forename, address).
Put this into a SparkLinker and go through linking workflow. 
Get error that forename not found. 

### OS:

Databricks

### Splink version:

3.6

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
This should be fixed by #987 once it's merged

**Comment by RobinL** [comment]
It's now merged and a prerelease has been published to pypi if you'd like to try it:
https://pypi.org/project/splink/3.7.0.dev1/

**Comment by robertwhiffin** [comment]
Thanks Robin - it worked!
When will this get published in full release?

**Comment by samnlindsay** [comment]
@RossKen Can this be closed now Robin's PR has been merged?
