### ISSUE TITLE
Enable linking multiple datasets (n > 2) with no dedupe

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#109]
This probably just needs a `multilink` option added [here](https://github.com/moj-analytical-services/splink/blob/31609a6585d435def3280f13f7b7b90d017b013e/splink/blocking.py#L133) with a `where` condition like `l._source_table < r._source_table` and a setting that allows the user to set the `source_table` column

**Comment by spencertollefson** [comment]
@RobinL I think this may be closed with the v1.0.0 update?
