### ISSUE TITLE
Scala UDFs documentation

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1093]
Right now if you want to find out about the functions defined in [the spark jars](https://github.com/moj-analytical-services/splink/tree/master/splink/files/spark_jars) you have to poke around in [the source code](https://github.com/moj-analytical-services/splink_scalaudfs) (and possibly the docs of the functions that these wrap). Additionally, that repo is only mentioned (afaict) in a comment on a [pyspark example page](https://moj-analytical-services.github.io/splink/demos/example_simple_pyspark.html) in the docs, so is easy to miss.

May make sense for the actual function docs to live in `splink_scalaudfs` and imported here in some fashion, which I realise is an additional bit of overhead compared to documenting functions directly in Splink.

**Comment by RossKen** [comment]
I 100% agree with this. I am planning to get under the hood of UDFs in the next week so I will write up some docs on the current state. Once that's done I think it is worth us giving the whole process a rethink re where the functions live etc.
