### ISSUE TITLE
`cumulative_num comparisons_from_blocking_rules_chart` time

### ISSUE THREAD

**Issue by James-Osmond** [moj-analytical-services/splink#1102]
I've made a DuckDBLinker object with two blocking rules. Individually, I can count the number of comparisons for each blocking rule with the `count_num_comparisons_from_blocking_rule` function - for each of the blocking rules this takes less than 3 seconds. However I have not yet been able to successfully run the `cumulative_num comparisons_from_blocking_rules_chart` function as it takes an unreasonably long time to run (I have kept it going for well over 10 minutes with no output) with just those two blocking rules. 

Has anyone else seen a similar issue, is this expected behaviour?

(on version 3.6.0)

**Comment by RossKen** [comment]
Hey @James-Osmond - I haven't heard of this behaviour before. What size of data are you working with?

**Comment by James-Osmond** [comment]
Hi @RossKen - this is a dataset with just over half a million rows, and 15 fields (not included uid). The blocking rules use 7 of these fields.

Unfortunately this isn't public data so I don't think I can provide a reproducible example!

**Comment by ThomasHepworth** [comment]
Do you know how long your `predict()` step takes on this data?

`cumulative_num comparisons_from_blocking_rules_chart` uses a snippet of that code flow to produce the chart.

**Comment by James-Osmond** [comment]
@ThomasHepworth I tried running `predict()` in the background out of interest, and gave up after 70 minutes I think. They weren't particularly good blocking rules, but I was just interested in seeing what the cumulative number of comparisons was with them, which in theory should have been quick enough to calculate, based on how long it took the code to calculate the number of pairs for each BR individually.

**Comment by RossKen** [comment]
@James-Osmond I've had one thought on this - what form were your blocking rules?

Were they a sequence of "l.column1 = r.column1" statements? Or something more complex?

Related to issue #1188 - under the hood, splink hashes the combinations of columns in your blocking rules with a unique id that can be referenced, making it run much quicker. This only works when you have blocking rules that are "=" statements (on one or more columns). So, if you are doing something more complex, that could possible explain the slow down.

**Comment by James-Osmond** [comment]
Hi @RossKen - one of the blocking rules DOES have a list filter in it. Wouldn't be the first time my use of those has caused me Splink troubles!

I thought I might have had issues even ignoring that one (but I'm not sure and don't have the data to hand so can't check). Another one is comparing columns to a VALUE, rather than to each other directly (l.sex='f' and r.sex='f'), would that cause a similar problem? Also got a few `l.x=r.x OR (l.y=r.y AND l.z = r.z)`s in there

**Comment by RossKen** [comment]
So your comparisons of values should be fine (l.sex='f' and r.sex='f').

Your `l.x=r.x OR (l.y=r.y AND l.z = r.z)` may be causing some issues though. Can you try breaking them up into separate blocking rules and see what happens? E.g.

```
"blocking_rules_to_generate_predictions" [
        "l.x = r.x",
        "l.y = r.y AND l.z = r.z"
        ]
```

This should be quicker as I think it will only run "l.y = r.y and l.z = r.z" if "l.x = r.x" is not true, whereas you are currently running them every time.

I'm also not sure how performance "OR" is an operation, so that may help as well.

**Comment by RossKen** [comment]
Not able to recreate this issue so closing
