### ISSUE TITLE
[FEAT] Implement Jaro similarity into comparison_level_library

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1107]
### Is your proposal related to a problem?

During team session running through comparison levels we talked about jaro potentially being useful for swapping in dates (e.g. month and day).

### Describe the solution you'd like

comparison_library and comparison_level_library functions similar to what is there for the likes of jaro-winkler, levenshtein etc

**Comment by RossKen** [comment]
@chloepugh if you ever feel like doing some splink dev work! 😄

**Comment by ThomasHepworth** [comment]
I think jaro needs its own scala udf.

**Comment by chloepugh** [comment]
I think @mamonu started work on this. Damerau-Levenshtein is the other one that could be useful for similar reasons (although would be less good for swapped day and month) but I think that'd require a scala udf as well.

**Comment by RossKen** [comment]
Separate issue added for Damerau-Levenshtein #1111

**Comment by mamonu** [comment]
I have started working on the Damerau UDF one and have something in the oven.
Once i'm happy with that (ie tested) i can have another look on restarting to work on creating a UDF for Jaro, when time allows.
Before, had started working on it but then my results were wrong so took a big break from that.

**Comment by mamonu** [comment]
UPDATE 12/3/23
Have tried to provide a Jaro Similarity UDF added on the jar on a branch [here](https://github.com/moj-analytical-services/splink_scalaudfs/tree/spark3_x_v0_1_1)

the (updated) jar itself is here [scala-udf-similarity-0.1.1_spark3.x.jar](https://github.com/moj-analytical-services/splink_scalaudfs/blob/spark3_x_v0_1_1/jars/scala-udf-similarity-0.1.1_spark3.x.jar)

the new function  can be registered by

```python
spark.udf.registerJavaFunction('jaro_sim', 'uk.gov.moj.dash.linkage.JaroSimilarity',\ 
                                pyspark.sql.types.StringType())   
```

I will test this function a bit before I merge it to the spark3.3 scala_udf branch but if you would like to try it please feel free.
If you downloaded this jar yesterday from issue #1111 you will need to update it as this is new code now including Jaro .

before including it anywhere:
 💀   💀   💀     we will need to test it . My last attempt at Jaro was not successful so caveat emptor :)  💀   💀   💀   

PS I have documented Jaro and JaroWinlkler on the splink docs but i think the best explanation (with an example) I have found is on this page. It would be nice if someone could update the Jaro doc to inlude graphics / example etc as this page does.

https://www.baseclass.io/newsletter/jaro-winkler

**Comment by RossKen** [comment]
Note - DuckDB already has jaro https://duckdb.org/docs/sql/functions/char.html
