### ISSUE TITLE
Add a feature engineering topic guide to docs

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1121]
### Is your proposal related to a problem?

While we do not want to create a [data standardisation module](https://github.com/moj-analytical-services/splink/discussions/986) module. It would be good to have a place to document ideas/suggestion on how users can get the most out of their data in the preprocessing step, other than standardisation, before it gets to splink in order to get better comparisons (and potentially some code examples).

For example
- Phonetics - we have a [high level guide](https://github.com/moj-analytical-services/splink/discussions/986) describing what sounded and dmetaphone are, but not how to actually use them (e.g. the scala UDFs). We also need to reword to explain the benefits in comparison levels as well as blocking.
- Postcodes - We should soon have a [string matching function for postcodes](https://github.com/moj-analytical-services/splink/issues/215), but in most cases if users created lat-long columns then would get much more value out of the `cll. distance_in_km_level` and `cl.distance_in_km_at_thresholds` functions.

### Describe the solution you'd like

Topic guide in the docs with suggestions for feature engineering.

**Comment by RossKen** [comment]
For example #1110

**Comment by aalexandersson** [comment]
Another example of a missing high-level topic guide which directly affect pre-processing other than standardisation:
* **Test data** - How many test datasets are currently easily available? How are these test data similar or different, for example in terms of size, missingness, variables, and type of errors and amount of errors? How can the `splink` test data be improved? What other record linkage test data are available? Is there any attempt to formally cooperate with other known developers of Python test data such as @aflaxman and @joke2k ?

**Comment by aflaxman** [comment]
You can rest assured that I'll have my eye on anything `splink` devs are working on in this space!  Let me know if there is anything I can do to help. :)
