### ISSUE TITLE
Fix benchmark comment workflow

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1148]
A couple of things here - one is that in #1122 the removal of the `ref` means that the benchmarking comment for the PR has `(detached head)` instead of the relevant branch name (and the commit ref points to a hypothetical 'merge' commit rather than the tip of the branch) - see e.g. [this comment](https://github.com/moj-analytical-services/splink/pull/1147#issuecomment-1484157436). The other is that the 'comment' step will not work if the PR originates from a fork - this is unavoidable without a workaround, as PR-initiated workflows do not have write permissions on the repo.

**Comment by ADBond** [comment]
Some partial work on [this branch](https://github.com/ADBond/splink/tree/different-comparison-bm) but haven't found a combination that sorts both yet.

**Comment by ADBond** [comment]
Semi-related: the link to the vegalite time series charts is broken - looks like this has been the case since 1st April '22. Think this is a github issue rather than us (the link works fine, just not rendering) - possibly related to [this issue](https://github.com/orgs/community/discussions/48174).

**Comment by RobinL** [comment]
It's probably because i'm encoding too much data into the url.  probably there's a better way

**Comment by RobinL** [comment]
Closing now that [splink 4](https://moj-analytical-services.github.io/splink/blog/2024/07/24/splink-400-released.html) has been released.  We've removed the benchmarking workflows
