### ISSUE TITLE
Parser Error and Syntax error when doing predictions

### ISSUE THREAD

**Issue by ashczq** [moj-analytical-services/splink#1168]
### What happens?

![image](https://user-images.githubusercontent.com/49942750/229490007-b1b4db5e-c812-43bb-b9e0-a99818ddff1c.png)

I am getting a syntax error after training the model and trying to make predictions. Any idea why does this happen? I was previously using spark (works perfectly) but am now trying using the DuckDB backend. 

### To Reproduce

![image](https://user-images.githubusercontent.com/49942750/229490514-ef477a26-f0b2-4ae1-9bf5-a4130341d83c.png)

![image](https://user-images.githubusercontent.com/49942750/229490654-6ddea5d6-77e7-43a9-8a14-58469907394b.png)

My settings and comparisons output looks fine as well. Am unsure what causes the error above. Only difference this time was that M and U probabilities were both estimated after only estimating via random sampling as i removed some irrelevant columns but still kept the remaining 5 useful ones.

### OS:

Windows

### Splink version:

3.0.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
That error would usually occur if there were no comparisons in your settings dictionary.  If you restart the Python session and run everything again from scratch does it still occur?

If it's still occurs would you be able to share your complete script please?

**Comment by ashczq** [comment]
Hi @RobinL I've fixed the initial error , occurred because i re-instantiated the linker and replaced the settings json dictionary. However i am now facing this issue of binder error where by it is asking for a column. I am currently on the latest version of 3.7 as well.  

![image](https://user-images.githubusercontent.com/49942750/229681748-da9a4813-be66-4e9a-a1e9-44b3b891d70d.png)

**Comment by RobinL** [comment]
Are you using Spark settings with DuckDB?  You need to import e.g. the comparison library from Splink.duckdb

**Comment by ashczq** [comment]
Thanks @RobinL , you were right the comparison library was used from the Spark settings instead. Fixed by using the duckdb. Closing the issue.
