### ISSUE TITLE
[FEAT] Blocking rule creation helper functions

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1171]
### Is your proposal related to a problem?

With the comparison/level/template libraries and comparison level composition we have abstracted away a lot of SQL, so that it is possible to write fairly detailed models without having to explicitly write any explicit SQL statements in the comparison settings. However, you currently still need to write explicit statements for blocking rules, both for predictions and parameter estimation. 

Additionally one can accidentally get mixed up and write something like `blocking_rule = "first_name_l = first_name_r"` which, although easily remedied, can be a bit of a pain. Another possible pitfall could be a typo, especially with lots of rules, and large compound expressions: `blocking_rule = "... AND l.surname = l.surname"`.

It would be nice to allow an option to have these abstracted into some helper functions, which could also aid readability.

### Describe the solution you'd like

Something akin to the `comparison_level_library`, but for blocking rules. There won't be the need for as much variety as most are exact matches, but there are still a few different options used in practice. Not sure if any dialect-dependent statements are ever really used, but might be worth having them separated out a) just in case, and b) as that pattern probably fits better with the existing approach. Probably with composition like #1114 also.

something like:
```python
from splink.duckdb.duckdb_linker import DuckDBLinker
import splink.duckdb.duckdb_comparison_library as cl
import splink.duckdb.duckdb_blocking_rule_library as brl


df = pd.read_csv("data.csv")

settings = {
    "link_type": "dedupe_only",
    "comparisons": [
        cl.exact_match("first_name"),
        cl.exact_match("surname"),
        cl.levensthein_at_thresholds("email"),
    ],
    "blocking_rules_to_generate_predictions": [
        brl.exact_match("full_name"),
        brl.and_(brl.exact_match("postcode"), brl.exact_match("dob")),
        brl.array_intersect("tag", 2),
        # I realise duckdb doesn't currenty support salting, but for illustration:
        brl.exact_match("dob_day_month", salting_partitions=6),
    ]
}
linker = DuckDBLinker(df, settings)

linker.estimate_probability_two_random_records_match(
    [
        brl.exact_match("full_name"),
        brl.and_(brl.exact_match("email"), brl.match_substring("dob", 1, 4)),
    ],
    recall=0.6
)

linker.estimate_parameters_using_expectation_maximisation(
    brl.exact_match("postcode")
)
```

### Describe alternatives you've considered

Things work okay as they stand - this may be overkill.

### Additional context

Some points that may require thought:
* need some care handling whether things are a `BlockingRule` or string/dict for e.g. serialisation, similar to `Comparisons` currently
* some SQL-construction may overlap slightly with comparison levels (although column name format distinct)
* could allow for extended features, such as chart labels which might aid readability

**Comment by RossKen** [comment]
Closed by #1370
