### ISSUE TITLE
Bayes factor SQL issue in spark linker - infinity edge case

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1209]
### What happens?

The use of infinity for Bayes factors in Spark SQL is not handled correctly in our custom dialect. This can manifest in EM training, leading to `splink.exceptions.SplinkException: Error executing the following sql for table '__splink__m_u_counts'`. The underlying issue from Spark is `Column 'InfinityD' does not exist` due to the generated SQL - for example
```SQL
CASE
      WHEN gamma_tm_partial = -1
      THEN 1.0D
      WHEN gamma_tm_partial = 1
      THEN InfinityD
      WHEN gamma_tm_partial = 0
      THEN 0.8556553394066886D
    END AS bf_tm_partial
```
This is coming from [this custom dialect code](https://github.com/moj-analytical-services/splink/blob/43067891ffaea14a117e26532a4053a04e588ef8/splink/spark/custom_spark_dialect.py#L6-L19).

### To Reproduce

`tests/test_charts.py::test_m_u_charts` translated to Spark dialect yields this error.

### OS:

MacOS

### Splink version:

3.8.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment]
A simple fix for this is available in [this commit](https://github.com/ADBond/splink/commit/bdf46069f23dd67323cde19d61fae67bdad02d75). This branches from #1205 but is not dependent on it, so can be cherry-picked and merged in before/independently of whether that gets merged if desired. There may be a smarter way to do it (not sure if e.g. `NaN`s or other funny values could end up here?)

**Comment by ADBond** [comment]
NB in looking into this I noticed that [this expression](https://github.com/moj-analytical-services/splink/blob/43067891ffaea14a117e26532a4053a04e588ef8/splink/comparison_level.py#L540) hard-codes a SQL expression for infinity. Not sure if that breaks in any dialect (Athena possibly?) - if not (and this is in fact universal) we could remove all the `_infinity_expression` stuff.

If it _does_ break in some dialect, then we need to allow `_infinity_expression` to be available to `ComparisonLevels`. This is currently not trivial, as `ComparisonLevels` do not consistently retain their `_sql_dialect` - see related #1019 and #1118

**Comment by RobinL** [comment]
Fwiw I have a general preference for overriding any match weights of plus or minus infinity with some very large number, since it simplifies the logic and also helps prevent convergence problems

**Comment by RossKen** [comment]
Fixed by @ADBond
