### ISSUE TITLE
[FEAT] Add versioning to the docsite

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1217]
### Is your proposal related to a problem?

mkdocs allows docs versioning as per https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

This should be helpful for tracking changes over time. Also, when major changes to the docs are made (with inevitable broken links, this should help users in the transition period)

### Describe the solution you'd like

Implement mkdocs versioning as per the link above

**Comment by NickCrews** [comment]
Note that if you want to keep it simple, Ibis just [chose to do the exact opposite transition](https://github.com/ibis-project/ibis/issues/5347) 😆

**Comment by RobinL** [comment]
I think we've decided it's more trouble than it's worth.

Legacy Splink 3 docs are 
https://moj-analytical-services.github.io/splink3_legacy_docs/index.html
