### ISSUE TITLE
[FEAT] Developer guide for adding new linkers

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1221]
### Is your proposal related to a problem?

As shown in #1191 and #1220, there is an appetite for additional linkers to be added to Splink. It would be helpful to add a dev guide to outline this process to make it easier for anyone to add new backend compatibility.

### Describe the solution you'd like

Something similar to the dev guides for [adding](https://moj-analytical-services.github.io/splink/dev_guides/comparisons/new_library_comparisons_and_levels.html) and [extending](https://moj-analytical-services.github.io/splink/dev_guides/comparisons/extending_library_comparisons_and_levels.html) comparisons.

**Comment by RobinL** [comment]
I think given the changes in Splink 4, this is probably no longer necessary.  People with the skills to add a linker can review pull requests which added the existing linkers.

For future readers, Andy has posted some useful guidance [here](https://github.com/moj-analytical-services/splink/discussions/2303)
