### ISSUE TITLE
Very poor performance of `estimate_u_using_random_sampling` using `link_only` and imbalanced length of input dfs

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#1225]
### What happens?

When you call `estimate_u_using_random_sampling` on a `link_only` job with imbalanced length of input dfs (say 100 and 500k records), the `USING SAMPLE N% (bernoulli)` sampled percentage is large.

That is to be expected, since it's a link only because you'll be comparing a very small number of (hopefully sampled) records from the length 100 dataset to a larger number of records from the 500k dataset.

_Note that if the input dfs were more balanced, the same size would be much smaller and hence wouldn't cause an issue at the blocking stage_

The problem is that Splink then runs the following blocking query:

```
select blah
from __splink__df_concat_with_tf_sample as l
            inner join __splink__df_concat_with_tf_sample as r
            on
            1=1
            where l."source_dataset" || '-__-' || l."unique_id" < r."source_dataset" || '-__-' || r."unique_id" and l."source_dataset" != r."source_dataset"
            )
```

So that:
1. compares every record with every other. (because nothing in there where condition is hashable)
2. evalutes the where conditions

That means a huge number of record comparisons have to be generated, the vast majority are _within_ the 500k dataset, which are immediately discarded.

I wonder whether for the sake of simplicity we should make the `link_only` case behave in the same was as `link_and_dedupe` case

### To Reproduce

```
import random
import string
import uuid

import pandas as pd

from splink.duckdb.duckdb_comparison_library import (
    exact_match,
)
from splink.duckdb.duckdb_linker import DuckDBLinker


def random_string(length):
    return "".join(random.choice(string.ascii_letters) for _ in range(length))



num_rows = 100
unique_ids = [str(uuid.uuid4()) for _ in range(num_rows)]
first_names = [random_string(random.randint(3, 10)) for _ in range(num_rows)]
df_left = pd.DataFrame({"unique_id": unique_ids, "first_name": first_names})


num_rows = 500_000
unique_ids = [str(uuid.uuid4()) for _ in range(num_rows)]
first_names = [random_string(random.randint(3, 10)) for _ in range(num_rows)]
df_right = pd.DataFrame({"unique_id": unique_ids, "first_name": first_names})


settings = {
    "link_type": "link_only",
    "blocking_rules_to_generate_predictions": [],
    "comparisons": [
        exact_match("first_name"),
    ],
    "retain_matching_columns": False,
    "retain_intermediate_calculation_columns": False,
}


linker = DuckDBLinker(
    [df_left, df_right], settings, input_table_aliases=["df_left", "df_right"]
)

# logging.getLogger("splink").setLevel(5)
# linker.debug_mode = True
linker.estimate_u_using_random_sampling(target_rows=1e3)


```

### OS:

iOS

### Splink version:

3.8.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by mshearer0** [comment]
Hi. Is it possible to give an indication of when this might be fixed? Its a blocker for my project. Alternatively is there any workaround that i could employ? Thanks.
