### ISSUE TITLE
[FEAT] Add function/parameter to generate scores for new records only

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1229]
### Is your proposal related to a problem?

A number of users have requested the ability to store pairwise comparisons that have already been made and then generate any new pairwise comparisons generated by additional records being added.

### Describe the solution you'd like

A function within the `linker` object to load in previous Splink results and remove them from the possible pairwise comparisons from a new dataset. Probably should be included at the blocking stage most easily integrate with the rest of the pipeline.

**Comment by RobinL** [comment]
linker.find_matches_to_new_records does something like this - specifically it creates only links between the new records and themselves or between the new records and the existing records (ie. It excludes links within the existing data)

**Comment by RossKen** [comment]
Ah nice, I didn't know that function existed! Thanks @RobinL 😊

I'm starting to wonder whether a specific function in needed for this. Assuming this sort of functionality is aimed at users with pipelines in production, I would imagine they would have a trained model they are loading in to score records against. In that case, the could do
1. Dedupe on the new records
2. Link only between existing and new records

Which can then be added to the existing edges and do clustering. I don't know enough about the connected components algorithm to know if clustering would need to be run again for all records, or if there is an easy way to read in the existing clusters and add the new edges. I the latter, it should be easier to track the difference new records have made to the clusters as you would have the previous cluster IDs.

**Comment by RobinL** [comment]
For reference, there's a discussion [here](https://github.com/moj-analytical-services/splink/discussions/869#discussioncomment-4075019) with a little bit more detail

**Comment by RossKen** [comment]
The function. exists so closing this issue
