### ISSUE TITLE
[FEAT] make altair (and jinja?) optional dependencies

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1246]
In a deployed model, I don't need the plotting capabilities from altair (and jinja?). It would be great if those were optional to reduce my build time, size, and vulnerability/bug surface area.

Hide them under a `viz` extra?

**Comment by RobinL** [comment]
Yes - I think you're right that both Altair and Jinja are only needed for charting/dashboards.

I think my main consideration here is the 'typical' Splink user, who is often not a professional programmer, and often primarily a statistician/analyst who may not have used Python very much.

I'm keen that a 'vanilla' `pip install splink` works as easily as possible for these users so I'd err on the side of retaining the dependencies that are often wanted by these 'less technical' users.  

I haven't experimented much with optional dependencies - would it be possible to have something like a `pip install splink[minimal_deps]` option?

**Comment by NickCrews** [comment]
I had to do some digging into this. Per https://discuss.python.org/t/optional-dependency-groups-omitting-package-requirements/20833/30, basically this isn't easy.

It looks like we could do it awkwardly with some fake shim intermediate packages that don't actually have any code, they just define the correct sets of dependencies. But that sounds like more trouble than it's worth. I would probably say close this as not worth it.

**Comment by RobinL** [comment]
Thanks for looking into it and sorry it's not easy!
