### ISSUE TITLE
comparison_template_library leads to error in linker.estimate_u_using_random_sampling

### ISSUE THREAD

**Issue by matriim** [moj-analytical-services/splink#1284]
Hello, thank you all for this amazing tool!
I wanted to try out the cool out-of-the-box comparisons you guys added through the splink.duckdb.duckdb_comparison_template_library but every time I add any of those comparisons I get an error. If I just remove the one line in the comparissons that use that library then everything works. I also tried a different machine, installed from scratch in a different OS and I still get the same error. Does anyone know how I can fix this?

`#imports
import numpy as np
import csv
import re
import pandas as pd
import altair as alt
from splink.duckdb.duckdb_linker import DuckDBLinker
import splink.duckdb.duckdb_comparison_library as cl
from splink.duckdb.duckdb_comparison_template_library import name_comparison
#load my cleaned up data into df here
settings = {
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.surname = r.surname and l.first_name = r.first_name and l.url_number != r.url_number",
        "l.surname = r.surname and ABS(l.app_year-r.app_year)<5 and l.industry_class = r.industry_class and l.url_number != r.url_number",
        "l.surname = r.surname and substr(l.first_name,1,2) = substr(r.first_name,1,2) and l.url_number != r.url_number",
        "l.surname = r.surname and l.profession = r.profession and l.url_number != r.url_number",
        "l.surname = r.surname and l.hisco = r.hisco and l.url_number != r.url_number",
        "l.unique_words = r.unique_words and l.url_number != r.url_number",
    ],
    "comparisons": [
        cl.exact_match("surname", term_frequency_adjustments=True),
        name_comparison("first_name"),
        cl.jaccard_at_thresholds("profession", term_frequency_adjustments=True),
        cl.exact_match("industry_class", term_frequency_adjustments=True),
        cl.exact_match("hisco", term_frequency_adjustments=True),
        cl.jaccard_at_thresholds("unique_words", term_frequency_adjustments=True),
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True
}
deterministic_rules = [
    "l.first_name = r.first_name and l.surname = r.surname and l.url_number != r.url_number",
    "l.hisco = r.hisco and l.surname = r.surname and l.industry_class = r.industry_class and l.url_number != r.url_number",
]

linker.estimate_probability_two_random_records_match(deterministic_rules, recall=0.09)
`
gives me this error:

`
----- Estimating u probabilities using random sampling -----
---------------------------------------------------------------------------
CatalogException                          Traceback (most recent call last)
File [c:\Python311\Lib\site-packages\splink\linker.py:602](file:///C:/Python311/Lib/site-packages/splink/linker.py:602), in Linker._log_and_run_sql_execution(self, final_sql, templated_name, physical_name)
    601 try:
--> 602     return self._run_sql_execution(final_sql, templated_name, physical_name)
    603 except Exception as e:
    604     # Parse our SQL through sqlglot to pretty print

File [c:\Python311\Lib\site-packages\splink\duckdb\duckdb_linker.py:220](file:///C:/Python311/Lib/site-packages/splink/duckdb/duckdb_linker.py:220), in DuckDBLinker._run_sql_execution(self, final_sql, templated_name, physical_name)
    219 def _run_sql_execution(self, final_sql, templated_name, physical_name):
--> 220     self._con.execute(final_sql)

CatalogException: Catalog Error: Scalar Function with name damerau_levenshtein does not exist!
Did you mean "levenshtein"?

The above exception was the direct cause of the following exception:

SplinkException                           Traceback (most recent call last)
Cell In[205], line 1
----> 1 linker.estimate_u_using_random_sampling(max_pairs=10e6)

File [c:\Python311\Lib\site-packages\splink\linker.py:1260](file:///C:/Python311/Lib/site-packages/splink/linker.py:1260), in Linker.estimate_u_using_random_sampling(self, max_pairs, seed, target_rows)
   1257 else:
   1258     raise TypeError("Missing argument max_pairs")
-> 1260 estimate_u_values(self, max_pairs, seed)
   1261 self._populate_m_u_from_trained_values()
   1263 self._settings_obj._columns_without_estimated_parameters_message()

File [c:\Python311\Lib\site-packages\splink\estimate_u.py:129](file:///C:/Python311/Lib/site-packages/splink/estimate_u.py:129), in estimate_u_values(linker, max_pairs, seed)
    127 sql = compute_new_parameters_sql(settings_obj)
    128 linker._enqueue_sql(sql, "__splink__m_u_counts")
--> 129 df_params = training_linker._execute_sql_pipeline(sample_dataframe)
    131 param_records = df_params.as_pandas_dataframe()
    132 param_records = compute_proportions_for_new_parameters(param_records)

File [c:\Python311\Lib\site-packages\splink\linker.py:544](file:///C:/Python311/Lib/site-packages/splink/linker.py:544), in Linker._execute_sql_pipeline(self, input_dataframes, materialise_as_hash, use_cache)
    537     dataframe = self._sql_to_splink_dataframe_checking_cache(
    538         sql_gen,
    539         output_tablename_templated,
    540         materialise_as_hash,
    541         use_cache,
    542     )
    543 except Exception as e:
--> 544     raise e
    545 finally:
    546     self._pipeline.reset()

File [c:\Python311\Lib\site-packages\splink\linker.py:537](file:///C:/Python311/Lib/site-packages/splink/linker.py:537), in Linker._execute_sql_pipeline(self, input_dataframes, materialise_as_hash, use_cache)
    534 output_tablename_templated = self._pipeline.queue[-1].output_table_name
    536 try:
--> 537     dataframe = self._sql_to_splink_dataframe_checking_cache(
    538         sql_gen,
    539         output_tablename_templated,
    540         materialise_as_hash,
    541         use_cache,
    542     )
    543 except Exception as e:
    544     raise e

File [c:\Python311\Lib\site-packages\splink\linker.py:750](file:///C:/Python311/Lib/site-packages/splink/linker.py:750), in Linker._sql_to_splink_dataframe_checking_cache(self, sql, output_tablename_templated, materialise_as_hash, use_cache)
    747     print(sql)
    749 if materialise_as_hash:
--> 750     splink_dataframe = self._execute_sql_against_backend(
    751         sql, output_tablename_templated, table_name_hash
    752     )
    753 else:
    754     splink_dataframe = self._execute_sql_against_backend(
    755         sql,
    756         output_tablename_templated,
    757         output_tablename_templated,
    758     )

File [c:\Python311\Lib\site-packages\splink\duckdb\duckdb_linker.py:215](file:///C:/Python311/Lib/site-packages/splink/duckdb/duckdb_linker.py:215), in DuckDBLinker._execute_sql_against_backend(self, sql, templated_name, physical_name)
    208 self._delete_table_from_database(physical_name)
    210 sql = f"""
    211 CREATE TABLE {physical_name}
    212 AS
    213 ({sql})
    214 """
--> 215 self._log_and_run_sql_execution(sql, templated_name, physical_name)
    217 return DuckDBLinkerDataFrame(templated_name, physical_name, self)

File [c:\Python311\Lib\site-packages\splink\linker.py:614](file:///C:/Python311/Lib/site-packages/splink/linker.py:614), in Linker._log_and_run_sql_execution(self, final_sql, templated_name, physical_name)
    611 except Exception:
    612     pass
--> 614 raise SplinkException(
    615     f"Error executing the following sql for table "
    616     f"`{templated_name}` ({physical_name}):\n{final_sql}"
    617 ) from e

SplinkException: Error executing the following sql for table `__splink__m_u_counts` (__splink__m_u_counts_0c7213887):
CREATE TABLE __splink__m_u_counts_0c7213887 AS
(
  WITH __splink__df_concat_with_tf_sample AS (
    SELECT
      *
    FROM __splink__df_concat_with_tf_sample_547e93d16
  ), __splink__df_blocked AS (
    SELECT
      "l"."unique_id" AS "unique_id_l",
      "r"."unique_id" AS "unique_id_r",
      "l"."surname" AS "surname_l",
      "r"."surname" AS "surname_r",
      "l"."first_name" AS "first_name_l",
      "r"."first_name" AS "first_name_r",
      "l"."profession" AS "profession_l",
      "r"."profession" AS "profession_r",
      "l"."industry_class" AS "industry_class_l",
      "r"."industry_class" AS "industry_class_r",
      "l"."hisco" AS "hisco_l",
      "r"."hisco" AS "hisco_r",
      "l"."unique_words" AS "unique_words_l",
      "r"."unique_words" AS "unique_words_r",
      "l"."url_number" AS "url_number_l",
      "r"."url_number" AS "url_number_r",
      "l"."app_year" AS "app_year_l",
      "r"."app_year" AS "app_year_r",
      '0' AS match_key
    FROM __splink__df_concat_with_tf_sample AS l
    INNER JOIN __splink__df_concat_with_tf_sample AS r
      ON 1 = 1
    WHERE
      l."unique_id" < r."unique_id"
  ), __splink__df_comparison_vectors AS (
    SELECT
      "unique_id_l",
      "unique_id_r",
      CASE
        WHEN "surname_l" IS NULL OR "surname_r" IS NULL
        THEN -1
        WHEN "surname_l" = "surname_r"
        THEN 1
        ELSE 0
      END AS gamma_surname,
      CASE
        WHEN "first_name_l" IS NULL OR "first_name_r" IS NULL
        THEN -1
        WHEN "first_name_l" = "first_name_r"
        THEN 4
        WHEN DAMERAU_LEVENSHTEIN("first_name_l", "first_name_r") <= 1
        THEN 3
        WHEN JARO_WINKLER_SIMILARITY("first_name_l", "first_name_r") >= 0.9
        THEN 2
        WHEN JARO_WINKLER_SIMILARITY("first_name_l", "first_name_r") >= 0.8
        THEN 1
        ELSE 0
      END AS gamma_first_name,
      CASE
        WHEN "profession_l" IS NULL OR "profession_r" IS NULL
        THEN -1
        WHEN "profession_l" = "profession_r"
        THEN 3
        WHEN JACCARD("profession_l", "profession_r") >= 0.9
        THEN 2
        WHEN JACCARD("profession_l", "profession_r") >= 0.7
        THEN 1
        ELSE 0
      END AS gamma_profession,
      CASE
        WHEN "industry_class_l" IS NULL OR "industry_class_r" IS NULL
        THEN -1
        WHEN "industry_class_l" = "industry_class_r"
        THEN 1
        ELSE 0
      END AS gamma_industry_class,
      CASE
        WHEN "hisco_l" IS NULL OR "hisco_r" IS NULL
        THEN -1
        WHEN "hisco_l" = "hisco_r"
        THEN 1
        ELSE 0
      END AS gamma_hisco,
      CASE
        WHEN "unique_words_l" IS NULL OR "unique_words_r" IS NULL
        THEN -1
        WHEN "unique_words_l" = "unique_words_r"
        THEN 3
        WHEN JACCARD("unique_words_l", "unique_words_r") >= 0.9
        THEN 2
        WHEN JACCARD("unique_words_l", "unique_words_r") >= 0.7
        THEN 1
        ELSE 0
      END AS gamma_unique_words,
      "url_number_l",
      "url_number_r",
      "app_year_l",
      "app_year_r"
    FROM __splink__df_blocked
  ), __splink__df_predict AS (
    SELECT
      *,
      CAST(0.0 AS DOUBLE) AS match_probability
    FROM __splink__df_comparison_vectors
  )
  SELECT
    gamma_surname AS comparison_vector_value,
    SUM(match_probability) AS m_count,
    SUM(1 - match_probability) AS u_count,
    'surname' AS output_column_name
  FROM __splink__df_predict
  GROUP BY
    gamma_surname
  UNION ALL
  SELECT
    gamma_first_name AS comparison_vector_value,
    SUM(match_probability) AS m_count,
    SUM(1 - match_probability) AS u_count,
    'first_name' AS output_column_name
  FROM __splink__df_predict
  GROUP BY
    gamma_first_name
  UNION ALL
  SELECT
    gamma_profession AS comparison_vector_value,
    SUM(match_probability) AS m_count,
    SUM(1 - match_probability) AS u_count,
    'profession' AS output_column_name
  FROM __splink__df_predict
  GROUP BY
    gamma_profession
  UNION ALL
  SELECT
    gamma_industry_class AS comparison_vector_value,
    SUM(match_probability) AS m_count,
    SUM(1 - match_probability) AS u_count,
    'industry_class' AS output_column_name
  FROM __splink__df_predict
  GROUP BY
    gamma_industry_class
  UNION ALL
  SELECT
    gamma_hisco AS comparison_vector_value,
    SUM(match_probability) AS m_count,
    SUM(1 - match_probability) AS u_count,
    'hisco' AS output_column_name
  FROM __splink__df_predict
  GROUP BY
    gamma_hisco
  UNION ALL
  SELECT
    gamma_unique_words AS comparison_vector_value,
    SUM(match_probability) AS m_count,
    SUM(1 - match_probability) AS u_count,
    'unique_words' AS output_column_name
  FROM __splink__df_predict
  GROUP BY
    gamma_unique_words
  UNION ALL
  SELECT
    0 AS comparison_vector_value,
    AVG(match_probability) AS m_count,
    AVG(1 - match_probability) AS u_count,
    '_probability_two_random_records_match' AS output_column_name
  FROM __splink__df_predict
)
`

**Comment by RobinL** [comment]
I think possibly you need to update duckdb to the latest version using e.g 

```bash
pip install --upgrade duckdb
```

**Comment by matriim** [comment]
No trouble at all, I don't know what I would do without your project! Thank you again :)
