### ISSUE TITLE
SplinkException While running SQL

### ISSUE THREAD

**Issue by konsbn** [moj-analytical-services/splink#1304]
### What happens?

While trying to replicate the [demo](https://github.com/moj-analytical-services/splink_demos/blob/master/example_febrl4.ipynb) I am getting this error
`---------------------------------------------------------------------------
BinderException                           Traceback (most recent call last)
File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/linker.py:602, in Linker._log_and_run_sql_execution(self, final_sql, templated_name, physical_name)
    601 try:
--> 602     return self._run_sql_execution(final_sql, templated_name, physical_name)
    603 except Exception as e:
    604     # Parse our SQL through sqlglot to pretty print

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/duckdb/duckdb_linker.py:220, in DuckDBLinker._run_sql_execution(self, final_sql, templated_name, physical_name)
    219 def _run_sql_execution(self, final_sql, templated_name, physical_name):
--> 220     self._con.execute(final_sql)

BinderException: Binder Error: Values list "l" does not have a column named "rec_id"

The above exception was the direct cause of the following exception:

SplinkException                           Traceback (most recent call last)
Cell In[11], line 6
      1 deterministic_rules = [
      2     "l.soc_sec_id = r.soc_sec_id",
      3     "l.given_name = r.given_name and l.surname = r.surname and l.date_of_birth = r.date_of_birth",
      4 ]
----> 6 linker_detailed.estimate_probability_two_random_records_match(deterministic_rules, recall=0.8)

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/linker.py:2867, in Linker.estimate_probability_two_random_records_match(self, deterministic_matching_rules, recall)
   2864 if isinstance(deterministic_matching_rules, str):
   2865     deterministic_matching_rules = [deterministic_matching_rules]
-> 2867 records = cumulative_comparisons_generated_by_blocking_rules(
   2868     self,
   2869     deterministic_matching_rules,
   2870 )
   2872 summary_record = records[-1]
   2873 num_observed_matches = summary_record["cumulative_rows"]

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/analyse_blocking.py:100, in cumulative_comparisons_generated_by_blocking_rules(linker, blocking_rules, output_chart)
     91 sql = """
     92     select
     93     count(*) as row_count,
   (...)
     97     order by cast(match_key as int) asc
     98 """
     99 linker._enqueue_sql(sql, "__splink__df_count_cumulative_blocks")
--> 100 cumulative_blocking_rule_count = linker._execute_sql_pipeline([concat])
    101 br_n = cumulative_blocking_rule_count.as_pandas_dataframe()
    102 cumulative_blocking_rule_count.drop_table_from_database()

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/linker.py:544, in Linker._execute_sql_pipeline(self, input_dataframes, materialise_as_hash, use_cache)
    537     dataframe = self._sql_to_splink_dataframe_checking_cache(
    538         sql_gen,
    539         output_tablename_templated,
    540         materialise_as_hash,
    541         use_cache,
    542     )
    543 except Exception as e:
--> 544     raise e
    545 finally:
    546     self._pipeline.reset()

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/linker.py:537, in Linker._execute_sql_pipeline(self, input_dataframes, materialise_as_hash, use_cache)
    534 output_tablename_templated = self._pipeline.queue[-1].output_table_name
    536 try:
--> 537     dataframe = self._sql_to_splink_dataframe_checking_cache(
    538         sql_gen,
    539         output_tablename_templated,
    540         materialise_as_hash,
    541         use_cache,
    542     )
    543 except Exception as e:
    544     raise e

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/linker.py:750, in Linker._sql_to_splink_dataframe_checking_cache(self, sql, output_tablename_templated, materialise_as_hash, use_cache)
    747     print(sql)
    749 if materialise_as_hash:
--> 750     splink_dataframe = self._execute_sql_against_backend(
    751         sql, output_tablename_templated, table_name_hash
    752     )
    753 else:
    754     splink_dataframe = self._execute_sql_against_backend(
    755         sql,
    756         output_tablename_templated,
    757         output_tablename_templated,
    758     )

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/duckdb/duckdb_linker.py:215, in DuckDBLinker._execute_sql_against_backend(self, sql, templated_name, physical_name)
    208 self._delete_table_from_database(physical_name)
    210 sql = f"""
    211 CREATE TABLE {physical_name}
    212 AS
    213 ({sql})
    214 """
--> 215 self._log_and_run_sql_execution(sql, templated_name, physical_name)
    217 return DuckDBLinkerDataFrame(templated_name, physical_name, self)

File ~/Documents/Codes/RecordLinkage/.env/lib64/python3.10/site-packages/splink/linker.py:614, in Linker._log_and_run_sql_execution(self, final_sql, templated_name, physical_name)
    611 except Exception:
    612     pass
--> 614 raise SplinkException(
    615     f"Error executing the following sql for table "
    616     f"`{templated_name}` ({physical_name}):\n{final_sql}"
    617 ) from e

SplinkException: Error executing the following sql for table `__splink__df_count_cumulative_blocks` (__splink__df_count_cumulative_blocks_f6881c415):
CREATE TABLE __splink__df_count_cumulative_blocks_f6881c415 AS
(
  WITH __splink__df_concat AS (
    SELECT
      *
    FROM __splink__df_concat_6ccccf0e1
  ), __splink__df_blocked_data AS (
    SELECT
      "l"."source_dataset" AS "source_dataset_l",
      "r"."source_dataset" AS "source_dataset_r",
      "l"."rec_id" AS "rec_id_l",
      "r"."rec_id" AS "rec_id_r",
      "l"."given_name" AS "given_name_l",
      "r"."given_name" AS "given_name_r",
      "l"."surname" AS "surname_l",
      "r"."surname" AS "surname_r",
      "l"."date_of_birth" AS "date_of_birth_l",
      "r"."date_of_birth" AS "date_of_birth_r",
      "l"."soc_sec_id" AS "soc_sec_id_l",
      "r"."soc_sec_id" AS "soc_sec_id_r",
      "l"."street_number" AS "street_number_l",
      "r"."street_number" AS "street_number_r",
      "l"."postcode" AS "postcode_l",
      "r"."postcode" AS "postcode_r",
      "l"."state" AS "state_l",
      "r"."state" AS "state_r",
      "l"."address_1" AS "address_1_l",
      "r"."address_1" AS "address_1_r",
      '0' AS match_key
    FROM __splink__df_concat AS l
    INNER JOIN __splink__df_concat AS r
      ON l.soc_sec_id = r.soc_sec_id
    WHERE
      l."source_dataset" || '-__-' || l."rec_id" < r."source_dataset" || '-__-' || r."rec_id"
      AND l."source_dataset" <> r."source_dataset"
    UNION ALL
    SELECT
      "l"."source_dataset" AS "source_dataset_l",
      "r"."source_dataset" AS "source_dataset_r",
      "l"."rec_id" AS "rec_id_l",
      "r"."rec_id" AS "rec_id_r",
      "l"."given_name" AS "given_name_l",
      "r"."given_name" AS "given_name_r",
      "l"."surname" AS "surname_l",
      "r"."surname" AS "surname_r",
      "l"."date_of_birth" AS "date_of_birth_l",
      "r"."date_of_birth" AS "date_of_birth_r",
      "l"."soc_sec_id" AS "soc_sec_id_l",
      "r"."soc_sec_id" AS "soc_sec_id_r",
      "l"."street_number" AS "street_number_l",
      "r"."street_number" AS "street_number_r",
      "l"."postcode" AS "postcode_l",
      "r"."postcode" AS "postcode_r",
      "l"."state" AS "state_l",
      "r"."state" AS "state_r",
      "l"."address_1" AS "address_1_l",
      "r"."address_1" AS "address_1_r",
      '1' AS match_key
    FROM __splink__df_concat AS l
    INNER JOIN __splink__df_concat AS r
      ON l.given_name = r.given_name
      AND l.surname = r.surname
      AND l.date_of_birth = r.date_of_birth
      AND NOT (
        COALESCE((
          l.soc_sec_id = r.soc_sec_id
        ), FALSE)
      )
    WHERE
      l."source_dataset" || '-__-' || l."rec_id" < r."source_dataset" || '-__-' || r."rec_id"
      AND l."source_dataset" <> r."source_dataset"
  )
  SELECT
    COUNT(*) AS row_count,
    match_key
  FROM __splink__df_blocked_data
  GROUP BY
    match_key
  ORDER BY
    CAST(match_key AS INT) NULLS LAST
)
`

### To Reproduce

I ran this bit of code 
`
linker_detailed.estimate_probability_two_random_records_match(deterministic_rules, recall=0.8)`
[Pip configurations](https://github.com/moj-analytical-services/splink/files/11679220/requirement.txt)

### OS:

Fedora 36

### Splink version:

3.9.0

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment]
This error indicates that the dataframes passed to the linker do not have the column `rec_id`. I'm not exactly sure how this could have ended up so - have you run all the code in the previous cells of the notebook without issue? What output do you get when you run the lines:
```py
display(dfs[0].head(2))
display(dfs[1].head(2))
```

and when you run `linker.missingness_chart()` do you see a row labelled `rec_id`? (and if not what rows do you see?)

**Comment by konsbn** [comment]
Sorry, silly mistake. I made rec_id into the index instead of a column. Thanks
