### ISSUE TITLE
[FEAT] Error message if you try to use `Damerau-Levenshtein` with older duckdb version installed

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1311]
### Is your proposal related to a problem?
`damerau_levenshtein` only exists on DuckDB >= 0.8.0, but currently we support versions >= 0.6.0. If a user has a pre-0.8.0 version installed and attempts to use `damerau_levenshtein` in their model they will get an error `Scalar Function with name damerau_levenshtein does not exist! Did you mean "levenshtein"`. See #1284 and #1309.

### Describe the solution you'd like
If a user tries to use comparisons using `damerau_levenshtein`, check the installed `duckdb` version, and raise an error if the version is too low with a helpful error message - e.g. "Your currently installed version of `duckdb` (0.6.1) does not support the function `damerau_levenshein`. To make use of this function you must upgrade your installation to >= 0.8.0, with e.g. `pip install --upgrade duckdb` or `pip install duckdb==0.8.0`". This could potentially build on Tom's work with the settings validator #1252.

### Describe alternatives you've considered
We could also drop support for lower versions of DuckDB, which would circumvent this. But this may possibly exclude users who are not so freely able to upgrade versions (+dependencies). Worth thinking about whether this option might be preferable on balance.

**Comment by RossKen** [comment]
Thanks for writing this issue up @ADBond, Tom and I talked about this earlier in the week after a few people have raised issues with 3.9.0 and 3.9.1. We came to the conclusion that we should just upgrade duckdb to 0.8.0 in the next splink release by default.

**Comment by RobinL** [comment]
I think I agree with ☝️ as well.  If people for some reason don't have access to duckdb 0.8.0, then they can either
- install an earlier version of Splink
- manually install Splink with `pip install --no-deps` and install the other deps by hand, and not use the `damerau_levenshtein` function

That leave the 'happy path', which should be available to most users, of just `pip install splink` and everything works as expected.  Generally I think that users in constrained environments are more likely to have the skills to solve these sorts of problems themselves (because they must be doing it all the time)

**Comment by ADBond** [comment]
Hi @espenfl 
> Can the feedstock config be updated or is there other reasons why the upper limit is there?

As far as I recall I don't think so (believe this constraint was pre-duckdb 0.7.0) - was probably just guarding against possible future breaking changes. Apologies, I have not looked at the feedstock since initially updating the recipe to start re-capturing versions some months back - I can take a look in the next few days and see about getting it more up-to-date again.

**Comment by espenfl** [comment]
Greatly appreciated if you could look into this. I think a few are fully dependent on a `conda` only environment. And given the increased adoption of Splink timing is great. Thanks to all the developers and folks spreading the word. Great stuff.
