### ISSUE TITLE
Error messages printed in docs

### ISSUE THREAD

**Issue by zslade** [moj-analytical-services/splink#1332]
### What happens?

Error messages displaying in code output blocks

### To Reproduce

See Examples > Pyspark > Deduplication using Pyspark section of docs here: https://moj-analytical-services.github.io/splink/demos/example_simple_pyspark.html

### OS:

iOS

### Splink version:

3.9.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RossKen** [comment]
Still not fully fixed - try https://timvink.github.io/mkdocs-charts-plugin/
