### ISSUE TITLE
The running speed of Splink algorithm is gradually slowing down

### ISSUE THREAD

**Issue by ZhimingMei** [moj-analytical-services/splink#1344]
### What happens?

I write a name-matching algorithm between two large datasets. I trained the model, and saved the settings so I can load the settings for later work.

And I write a _for_ loop to match all other datasets, without using the distributed algorithm. Here's a strange issue that, the running speed is quite fast in the first few iterations, but it will get slower after several iterations.

I tried adding gc.collect() in my code, and it doesn't work. I wonder why this happened and how to solve it.

Thanks.

### To Reproduce

```python
country_lst = [] # countries name here

for country in country_lst:
    print(f'---------------start loading {country}---------------')
    # loading the dataset
    os.chdir(df_l_path)
    temp_l = pd.read_pickle(f'df_l_{country}.pkl')

    len_l = len(temp_l)
    os.chdir(df_r_path)
    temp_r = pd.read_pickle(f'df_r_{country}.pkl')

    df_l, df_r = process_data(temp_l, temp_r)
    result = generate_prediction(df_l, df_r) # here's the function that I defined to generate the prediction. load settings, and .predict()

    os.chdir(result_path)
    result.to_pickle(f'result_{country}.pkl')
    print(f'complete saving of {country}')
    print(f'---------------finish {country} matching!---------------')
    gc.collect()
```

### OS:

MacOS (running on linux server)

### Splink version:

3.9.0

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Would need more info on this to address e.g. a full reprex and timings
