### ISSUE TITLE
Loading term frequencies into another model

### ISSUE THREAD

**Issue by hoffmanndam** [moj-analytical-services/splink#1356]
I am trying to calculate term frequencies in a large data set and re use them in a smaller data set for reference I am linking people within a time window of 6 hours 3 hours before and 3 hour after the person appears in the first dataset, feedback would be greatly appreciated, thanks

#computing tf tables
full_name_tf = linker.compute_tf_table("full_name")
date_of_birth_tf = linker.compute_tf_table("date_of_birth")

#saving a parquet
df_full_name_tf.to_parquet("./TF/full_name_tf.parquet", overwrite = True)
df_date_of_birth_tf.to_parquet("./TF/date_of_birth_tf.parquet", overwrite = True)

#loading files
df_full_name_tf = pd.read_parquet("./TF/full_name_tf.parquet")
df_date_of_birth_tf = pd.read_parquet("./TF/date_of_birth_tf.parquet")

-----------------------------------------------------------------------------------------------------------------------------------------

#attempt 1 no errors tf didn't update

linker = DuckDBLinker([dfl, dfr], trained_settings, input_table_aliases=["df_left", "df_right"])
linker.register_term_frequency_lookup("full_name", "full_name_tf")
linker.register_term_frequency_lookup("date_of_birth", "date_of_birth_tf")

linker._settings_obj_._retain_intermediate_calculation_columns = True
linker._settings_obj_._retain_matching_columns = True

linker._settings_obj_._custom_sql_ = {
    "term_frequencies": {
        "full_name": {
            "table": "full_name_tf",
            "term_column": "full_name",
            "frequency_column": "tf_full_name",
        },
        "date_of_birth": {
            "table": "date_of_birth_tf",
            "term_column": "date_of_birth",
            "frequency_column": "tf_date_of_birth",
        },

    }
}

-----------------------------------------------------------------------------------------------------------------------------------------

#attempt 2 tried loading in before creating the linker got error 

df_full_name_tf["full_name"] = df_full_name_tf["full_name"].astype(str)
df_full_name_tf["tf_full_name"] = df_full_name_tf["tf_full_name"].astype(str)

df_date_of_birth_tf["date_of_birth"] = df_date_of_birth_tf["date_of_birth"].astype(str)
df_date_of_birth_tf["tf_date_of_birth"] = df_date_of_birth_tf["tf_date_of_birth"].astype(str)

term_frequencies = {
    "full_name": df_full_name_tf.to_dict(orient="records"),
    "date_of_birth": df_date_of_birth_tf.to_dict(orient="records"),

}

term_frequencies_serializable = {
    col: json.dumps(data)
    for col, data in term_frequencies.items()
}

trained_settings["term_frequencies"] = term_frequencies_serializable

clean_settings = {
    "link_type": "link_only",  
}

settings = Settings(clean_settings)
settings_dict = settings.as_dict()

linker = DuckDBLinker([dflf, dfrf], settings_dict, input_table_aliases=["df_left", "df_right"])

results = linker.predict(threshold_match_probability=0.9)

#ERROR 
LINE 34:     log2(CASE WHEN  THEN cast('infinity' as double) ELSE cast(0.00010001000100010001 as double) *  END) as match_weight,
    CASE WHEN  THEN 1.0 ELSE ((CASE WHEN  THEN cast('infinity' as double) ELSE cast(0.00010001000100010001 as double) *  END)/(1+(CASE WHEN  THEN cast('infinity' as double) ELSE cast(0.00010001000100010001 as double) *  END))) END as match_probability,
    "source_dataset_l","source_dataset_r","unique_id_l","unique_id_r" 
    from __splink__df_match_weight_parts
     where log2(CASE WHEN  THEN cast('infinity' as double) ELSE cast(0.00010001000100010001 as double) *  END) >= 3.1699250014423126 
    )

-----------------------------------------------------------------------------------------------------------------------------------------

#attempt 3 asked chatgpt, no errors tf didn't update

linker = DuckDBLinker([dfl, dfr], trained_settings, input_table_aliases=["df_left", "df_right"])
connection = duckdb.connect(database=":memory:")

connection.register("full_name_tf", df_full_name_tf)
connection.register("date_of_birth_tf", df_date_of_birth_tf)
connection.register("address_tf", df_address_tf)
connection.register("postcode_tf", df_postcode_tf)

linker.register_term_frequency_lookup("full_name", "full_name_tf")
linker.register_term_frequency_lookup("date_of_birth", "date_of_birth_tf")

linker._settings_obj_._retain_intermediate_calculation_columns = True
linker._settings_obj_._retain_matching_columns = True

linker._settings_obj_._custom_sql_ = {
    "term_frequencies": {
        "full_name": {
            "table": "full_name_tf",
            "term_column": "full_name",
            "frequency_column": "tf_full_name",
        },
        "date_of_birth": {
            "table": "date_of_birth_tf",
            "term_column": "date_of_birth",
            "frequency_column": "tf_date_of_birth",
        },

    }
}

for column, table in table_name_mapping.items():
    term_column = term_column_mapping[column]
    frequency_column = frequency_column_mapping[column]

    # Fetch the term frequencies from the DuckDB table
    query = f"SELECT \"{term_column}\", \"{frequency_column}\" FROM {table}"  # Enclose column names in double quotes
    term_frequencies = connection.execute(query).fetchall()
    term_frequencies_df = pd.DataFrame(term_frequencies, columns=[term_column, frequency_column])

    # Create a temporary DuckDB table with the updated term frequencies
    temp_table_name = f"temp_{table}"
    term_frequencies_tuples = [tuple(x) for x in term_frequencies_df.values]

    # Drop the temporary table if it exists
    query = f"DROP TABLE IF EXISTS {temp_table_name}"
    connection.execute(query)

    query = f"CREATE TABLE {temp_table_name} (\"{term_column}\" TEXT, \"{frequency_column}\" INTEGER)"
    connection.execute(query)

    query = f"INSERT INTO {temp_table_name} (\"{term_column}\", \"{frequency_column}\") VALUES (?, ?)"
    connection.executemany(query, term_frequencies_tuples)

    # Check if the original object is a table or a view
    query = f"SELECT type FROM sqlite_master WHERE name='{table}'"
    result = connection.execute(query).fetchone()
    object_type = result[0] if result is not None else None

    # Drop the original object (table or view)
    if object_type == "table":
        query = f"DROP TABLE {table}"
    elif object_type == "view":
        query = f"DROP VIEW {table}"
    else:
        raise ValueError(f"Unknown object type: {object_type}")

    connection.execute(query)

    # Copy the data from the temporary table to the original table
    query = f"CREATE TABLE {table} AS SELECT * FROM {temp_table_name}"
    connection.execute(query)

    # Drop the temporary table
    query = f"DROP TABLE {temp_table_name}"
    connection.execute(query)

**Comment by RobinL** [comment]
The way to do this in Splink 3 was:

```python
import duckdb

from splink.datasets import splink_datasets
from splink.duckdb.blocking_rule_library import block_on
from splink.duckdb.comparison_library import (
    exact_match,
    levenshtein_at_thresholds,
)
from splink.duckdb.linker import DuckDBLinker
import pandas as pd

df = splink_datasets.fake_1000

con = duckdb.connect()

tf_table = [
    {"first_name": "Theodore", "tf_first_name": 0.012033694344163659},
    {"first_name": "Alfie", "tf_first_name": 0.013237063778580024},
    {"first_name": "James", "tf_first_name": 0.015643802647412757},
    {"first_name": "Kaur", "tf_first_name": 0.0012033694344163659},
    {"first_name": "Jacob", "tf_first_name": 0.019253910950661854},
]


settings = {
    "probability_two_random_records_match": 0.01,
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        block_on(["first_name"]),
        block_on(["surname"]),
    ],
    "comparisons": [
        levenshtein_at_thresholds("first_name", 2),
        exact_match("surname"),
        exact_match("dob"),
    ],
}


linker = DuckDBLinker(df, settings, connection=con)
tf_df = pd.DataFrame(tf_table)
linker.register_term_frequency_lookup(tf_df, "first_name")
predictions = linker.predict()
```

In Splink 4 it's:

```python
import splink.comparison_library as cl
from splink import DuckDBAPI, Linker, SettingsCreator, block_on, splink_datasets
import pandas as pd

db_api = DuckDBAPI()

df = splink_datasets.fake_1000


tf_table = [
    {"first_name": "Theodore", "tf_first_name": 0.012033694344163659},
    {"first_name": "Alfie", "tf_first_name": 0.013237063778580024},
    {"first_name": "James", "tf_first_name": 0.015643802647412757},
    {"first_name": "Kaur", "tf_first_name": 0.0012033694344163659},
    {"first_name": "Jacob", "tf_first_name": 0.019253910950661854},
]



settings = SettingsCreator(
    link_type="dedupe_only",
    comparisons=[
        cl.JaroWinklerAtThresholds("first_name", [0.9, 0.7]),
        cl.JaroAtThresholds("surname", [0.9, 0.7]),
        cl.DateOfBirthComparison(
            "dob",
            input_is_string=True,
            datetime_metrics=["year", "month"],
            datetime_thresholds=[1, 1],
        ),
        cl.ExactMatch("city").configure(term_frequency_adjustments=True),
        cl.EmailComparison("email"),
    ],
    blocking_rules_to_generate_predictions=[
        block_on("first_name"),
        block_on("surname"),
    ],
    retain_matching_columns=True,
    retain_intermediate_calculation_columns=True,
)

linker = Linker(df, settings, db_api)
tf_df = pd.DataFrame(tf_table)
linker.table_management.register_term_frequency_lookup(tf_df, "first_name")
linker.inference.predict()
```

**Comment by RobinL** [comment]
I've also now documented how to do this in this pr
https://github.com/moj-analytical-services/splink/pull/2343
