### ISSUE TITLE
BUG: Assuming pkg_resources is installed, should migrate to importlib.resources

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1386]
### What happens?

splink imports pkg_resources, assuming that it is present. Usually this is a passable assumption, because pkg_resources is installed with setuptools, and setuptools is usually installed. However, when PDM manages a venvs, PDM doesn't include setuptools, and thus no pkg_resources. I just ran into this.

possible solutions:
1. Include setuptools as a dep
2. Migrate to importlib.resources

option 1 seems silly and like overkill just for the tiny bit of funcitonality we need. We should do 2, that is what [official docs of setuptools recommends](https://setuptools.pypa.io/en/latest/pkg_resources.html).

### To Reproduce

Create a new venv with PDM, listing splink as the only requirement. Enter the venv and try to use splink. You get an import error for pkg_resources.

Easy workaround is to just list setuptools as another dep.

### OS:

any

### Splink version:

present on main

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by NickCrews** [comment]
I can write a PR to do this if you think this is the right idea.

**Comment by RobinL** [comment]
Yes please - if you don't mind!
