### ISSUE TITLE
Find a better way to insert markdown includes into docs

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1395]
Right now when building the docs, we generate some tables automatically for the libaries + datasets, which are then incorporated into the actual markdown for the docs site, by inserting e.g.:

```
{% include-markdown "./includes/generated_files/comparison_library_dialect_table.md" %}
```

This works by running a simple search-and-replace on the docs folder, replacing these lines with the substituted file contents. This means you end up with these changes lingering in your working tree, risk accidentally committing them (which should hopefully be at least picked up in review, but still), and generally just cause a pain (particularly if you are switching around between branches).

There is [mkdocs-include-markdown-plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin), which the current syntax is taken from, but this doesn't interact well with `mknotebooks`, causing the build to hang (or just be unfeasibly slow) - see #1073, and #1035.

One possibility would be making a fairly small [mkdocs plugin](https://www.mkdocs.org/dev-guide/plugins/) to get just the basic functionality we need, but there may be a simpler way to hook into the document-generation process.

It could also make sense to bake the actual generation of these include files into this process also, rather than the fairly basic approach currently (running the script if _one_ of the includes is present in the directory 😬 (sorry!)), or even find an entirely different way to incorporate these dynamic bits of the docs (i.e. not using includes at all).

**Comment by RossKen** [comment]
Agree that this would be a really good problem to solve - I can only see us using these auto-generated features more so would be great to have a more streamlined solution.

**Comment by ADBond** [comment]
Also [mkdocs-simple-hooks](https://pypi.org/project/mkdocs-simple-hooks/) might be an option to give us what we need without having to write a whole plugin
