### ISSUE TITLE
[FEAT] make naming consistent for saving and loading a model

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1411]
### Is your proposal related to a problem?

Recently we added the `load_model` and `load_settings` functions, however these don't match naming-wise with how we save models `save_model_to_json` and `save_settings_to_json`. We should resolve these for consistency.

### Describe the solution you'd like

Rename save functions as `save_model` and `save_settings` and deprecate the existing functions.

**Comment by RobinL** [comment]
load settings no longer exists in SPlink4 because you cannot instantiate linker without settings.  closing
