### ISSUE TITLE
How to create a comparison using Euclidean distance between 2D coordinates?

### ISSUE THREAD

**Issue by arnaudsj** [moj-analytical-services/splink#1413]
I reviewed and scanned through the examples and documentation. I haven't found a clear example of how to implement a simple euclidean distance when the variable I am trying to compare are simple 2D coordinates (as a tuple). 

Thank you in advance for any pointers.

**Comment by arnaudsj** [comment]
I am going to try based on this: https://moj-analytical-services.github.io/splink/topic_guides/customising_comparisons.html#method-4-providing-the-spec-as-a-dictionary

**Comment by RobinL** [comment]
Yep - that's the best way to do it right now
