### ISSUE TITLE
[FEAT] comparison viewer: Color code gammas due to match weight, not gamma value

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1437]
### Is your proposal related to a problem?

Look at the top row in the comparison vectors, the green 5 and the yellow 3:
<img width="162" alt="image" src="https://github.com/moj-analytical-services/splink/assets/10820686/a221731c-683e-491c-80fd-a2ff53e6fa43">

This makes it look like gamma level 5 leads to more of a match, and 3 leads to less of a match. But this is not actually the case, it's the other way for me. Level 5 has a negative match weight, and level 3 has a positive weight.

### Describe the solution you'd like
Similar to how the histogram bars are color coded due to match weight (this is great!), the gammas should be coded following the same color scale.

### Describe alternatives you've considered
If this is too hard, at least use a different color scale, like blue-green. Then you can still see the different vector kinds, but it doesn't imply anything about match weight.

### Additional context
I looked into writing a PR for this, but it was too confusing for me, I don't know where this relevant code is.

**Comment by RobinL** [comment]
Thanks.  Yeah, the source code for this is elsewhere.  I remember noticing this bug a while back but then forgot about it.  Good to have it as an issue so I remember to fix.

**Comment by NickCrews** [comment]
Also, while you're in there, worth considering switching to the colormap [viridis](https://sjmgarnier.github.io/viridis/): 

viridis, and its companion package [viridisLite](https://cran.r-project.org/package=viridisLite) provide a series of color maps that are designed to improve graph readability for readers with common forms of color blindness and/or color vision deficiency. The color maps are also perceptually-uniform, both in regular form and also when converted to black-and-white for printing.
