### ISSUE TITLE
[FEAT] test python 3.10, 3.11

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1496]
I am using splink with python 3.11 and it is working fine, but I would feel better if splink were tested against that. Is there anything preventing me from writing a PR that simply adds this to the config so 3.10 and 3.11 are run in tests and CI?

**Comment by ADBond** [comment]
There's no fundamental reason why we don't do this - I believe initially we excluded >= 3.10 just as there was some sort of dependency issue that needed resolving to get things running in CI (maybe something with `numpy`?), and have not got round to adding yet.

Would be good to have newer versions tested though, so would be happy if you did manage to add these in okay

**Comment by ADBond** [comment]
See [the PR initially adding multiple versions for testing](https://github.com/moj-analytical-services/splink/pull/1090), although realise I have not explained in much detail there precisely what was causing difficulties
