### ISSUE TITLE
[FEAT] Allow `profile_columns` with no parameters

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1514]
### Is your proposal related to a problem?

Currently we need to manually declare the columns to profile in `profile_columns`. While this functionality is fine, it feels like there should be a default to plot all columns, such as with the `missingness_chart`.

### Describe the solution you'd like

`linker.profile_columns()` produces a chart profiling all columns in a dataset

**Comment by RobinL** [comment]
This upcoming method should be a useful function to use to implement this:
https://github.com/moj-analytical-services/splink/blob/42ec64030436afbcfb0c804de75394d844436d80/splink/linker.py#L255

**Comment by samnlindsay** [comment]
Fixed by #1516
