### ISSUE TITLE
SSLCertVerificationError when downloading splink datasets

### ISSUE THREAD

**Issue by aliceoleary0** [moj-analytical-services/splink#1542]
### What happens?

Get SSLCertVerificationError when try to download Splink in-built datasets

Code fails here:
```
   1347             try:
-> 1348                 h.request(req.get_method(), req.selector, req.data, headers,
   1349                           encode_chunked=req.has_header('Transfer-encoding'))
```

### To Reproduce

Running the following on Mac (with VPN) in VScode

```
from splink.datasets import splink_datasets
df = splink_datasets.fake_1000
```

### OS:

Mac OS Bug Sur 11.7

### Splink version:

3.9.5

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RossKen** [comment]
Hey @aliceoleary0 - does the solution in [this comment](https://github.com/moj-analytical-services/splink/pull/1358#pullrequestreview-1506869362) make it work for you? I'm not sure if there is a more permanent fix, so if it works I am likely thinking of just adding this workaround to the docs to guide people having issues.
