### ISSUE TITLE
Missing quotes

### ISSUE THREAD

**Issue by espenfl** [moj-analytical-services/splink#1556]
### What happens?

Upon passing a dataset do the Spark linker we get:

```
pyspark.sql.utils.ParseException:
mismatched input '00' expecting {'ADD....
```
etc. 

Looking at https://github.com/moj-analytical-services/splink/blob/99f321b26966fe0798628723dd9e2fa90d75b316/splink/spark/linker.py#L239 (thanks @patrikkj) it seems you can get situations here that is interpreted wrongly unless maybe `{self.splink_data_store}` is quoted. There are also other instances of the same usage without the quotes.

### To Reproduce

Passing `self.splink_data_store` a value of `00-00-00-00-00` yields this error. The value obviously depends on the database and catalog. In our case, this is what we have to work with. Same dataset works fine with the DuckDB linker.

### OS:

Linux

### Splink version:

3.9.2

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ThomasHepworth** [comment]
Thanks for the report! I've added what should be the fix in here - https://github.com/moj-analytical-services/splink/pull/1558.

The entire team (other than I) are off this week, so I'm not sure when this will get merged.

For the time being (and assuming you're able to on your machines), you can install the dev build from that branch using:
```sh
pip install git+https://github.com/moj-analytical-services/splink.git@1f8d4851956e40134a0e036e4f02a6d1b275a7ac
```

**Comment by espenfl** [comment]
Thanks a lot @ThomasHepworth. Greatly appreciated.
