### ISSUE TITLE
Blocking rules generating unexpected SQL queries

### ISSUE THREAD

**Issue by antongiac** [moj-analytical-services/splink#1568]
### What happens?

While working on some blocking rules I receive unexpected behaviour when trying to distinguish between the left and right table.

When I run:
block_on("abs(l.amount - r.amount) < 100")
I receive the following output:
<Custom blocking rule using SQL: ABS(l."amount" - l."amount") < 100 = ABS(r."amount" - r."amount") < 100>

Whereas I would have expected something along the lines of ABS(l.amount - r.amount) < 100

Similarly, when I run:
block_on("l.amount<>r.amount")
It outputs:
<Custom blocking rule using SQL: l."amount" <> l."amount" = r."amount" <> r."amount">
Whereas I would have expected something along the lines of l.amount <> r.amount 

Am I missing something?

### To Reproduce

from splink.datasets import splink_datasets
from splink.duckdb.linker import DuckDBLinker
import altair as alt

df_origin = splink_datasets.transactions_origin
df_destination = splink_datasets.transactions_destination

# Simple settings just for exploratory analysis
settings = {"link_type": "link_only"}
linker = DuckDBLinker([df_origin, df_destination], settings,input_table_aliases=["__ori", "_dest"])
linker.profile_columns(["transaction_date", "memo", "round(amount/5, 0)*5"])

# Design blocking rules that allow for differences in transaction date and amounts
from splink.duckdb.blocking_rule_library import block_on, and_

block_on("abs(l.amount - r.amount) < 100")

### OS:

Windows 11

### Splink version:

3.9.6

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by antongiac** [comment]
Thanks a lot!

**Comment by ThomasHepworth** [comment]
Just to tag onto the above comment from Sam, we also have a series of ["composition functions"](https://moj-analytical-services.github.io/splink/blocking_rule_composition.html) for blocking rules.

Utilising the `not_` function, your other example - `"l.amount<>r.amount"` can be rewritten as `not_(block_on("amount"))`.

A toy example:
```py
from splink.duckdb.duckdb_linker import DuckDBLinker
from splink.duckdb.blocking_rule_library import not_, block_on
from splink.datasets import splink_datasets

linker = DuckDBLinker(
    splink_datasets.fake_1000,
    settings_dict={"link_type": "dedupe_only"}
)

print(linker.cumulative_comparisons_from_blocking_rules_records(["l.surname <> r.surname"]))
print(linker.cumulative_comparisons_from_blocking_rules_records([not_(block_on("surname"))]))
```
