### ISSUE TITLE
[FEAT] Add some examples to docs of blocking rules _without_ `block_on`

### ISSUE THREAD

**Issue by samnlindsay** [moj-analytical-services/splink#1569]
### Is your proposal related to a problem?

#1568 highlighted potential confusion around how to specify blocking rules as the examples exclusively use `block_on` without any examples of explicit SQL conditions

### Describe the solution you'd like

Reinstate some examples of other blocking rules

**Comment by RobinL** [comment]
https://moj-analytical-services.github.io/splink/demos/examples/duckdb/transactions.html
