### ISSUE TITLE
Unable to create `SparkLinker` on Databricks

### ISSUE THREAD

**Issue by cswaney** [moj-analytical-services/splink#1584]
### What happens?

The `SparkLinker` constructor fails on (AWS) Databricks with error: `py4j.Py4JException: Constructor com.databricks.libraries.JavaJarId([class java.net.URI, class java.lang.String, class java.lang.String]) does not exist`

### To Reproduce

Follow the "end-to-end" example in the `auto-data-linkage` [workshop](https://github.com/databricks-industry-solutions/auto-data-linkage/blob/f425125c62904f18f2e2f084467293f1878f908c/Workshop%20Materials/notebooks/Splink%20in%20Databricks%20-%20end-to-end%20example.py).

Specifically, connect to personal compute running DBR 13.3 LTS (with default libraries, init script, spark configuration, etc.) and run the following in a notebook:

```
%pip install splink --quiet

from splink.spark.spark_linker import SparkLinker
# or from splink.spark.linker import SparkLinker
from splink.databricks.enable_splink import enable_splink
import splink.spark.spark_comparison_library as cl

df = spark.read.table('main.default.<table>')

linker = SparkLinker(df, spark=spark) # error
```

### OS:

Databricks Runtime 13.3 LTS (Spark 3.4.1, Scala 2.12)

### Splink version:

3.9.6

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by aymonwuolanne** [comment]
I've had this same issue, downgrading to Databricks Runtime 11.3 LTS worked as a temporary solution for me. Something must have changed in Spark or Databricks that means the code in https://github.com/moj-analytical-services/splink/blob/master/splink/databricks/enable_splink.py no longer works as expected.

**Comment by beedrumms** [comment]
I have also had this exact same issue when upgrading from RT 13.2 (Spark 3.4.0) to RT 14.2 (Spark 3.5.0) in my databrick env. I also upgraded to the lastest splink version (3.9.9). **Downgrading back to RT 13.2 (Spark 3.4.0) worked**
