### ISSUE TITLE
enable_splink() in databricks fails

### ISSUE THREAD

**Issue by robertwhiffin** [moj-analytical-services/splink#1616]
### What happens?

A change in Databricks has broken the enable_splink() call to auto attach the jar.

I would suggest yanking the enable_splink() calls in the spark linker.py at lines 182, 183, 184

### To Reproduce

Run Splink in Databricks.

### OS:

Databricks

### Splink version:

3.7.9

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by robertwhiffin** [comment]
closing as this can be solved by using a different runtime.

**Comment by RobinL** [comment]
Hey Robert, thanks for this.  Unfortunately we don't have access to databricks but I know that others have struggled with this.  I wondered if you would be willing just to add just a little bit more detail about how you solved this - how do you change the runtime and databricks and what runtime works for you?

Thanks so much!

**Comment by robertwhiffin** [comment]
yes, was going to PR but this is a better fix - we just need to add to the docs that it requires 12.2LTS ML DB Runtime.
