### ISSUE TITLE
Splink Spark Backend does not work on Splink v3.9.6 due to class import issue

### ISSUE THREAD

**Issue by robertusvincent** [moj-analytical-services/splink#1618]
### What happens?

I am currently experimenting with Splink 3 (v3.9.6) under following environment:
- Python 3.7.16
- Spark 2.4.7

The goal is to see if I can run Splink with Spark 2. Especially, running record linkage with Jaro Winkler Similarity.
I am running it through Spark Backend and the [example given in the docs](https://github.com/moj-analytical-services/splink/blob/v3.9.6/docs/demos/examples/spark/deduplicate_1k_synthetic.ipynb) does not work for me. Throwing following error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o535.registerJava.
: org.apache.spark.sql.AnalysisException: Can not load class uk.gov.moj.dash.linkage.LevDamerauDistance, please make sure it is on the classpath;
        at org.apache.spark.sql.UDFRegistration.registerJava(UDFRegistration.scala:661)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)
```

There are some problems that I see following Spark backend, especially Spark 2.

**First problem** is the jar associate with Spark < 3.0. [`similarity_jar_location`](https://github.com/moj-analytical-services/splink/blob/v3.9.6/splink/spark/jar_location.py) returns an invalid path if Spark < 3.0. It returns `scala-udf-similarity-0.1.0_legacy.jar`, although there is no legacy jar. I can see [classic](https://github.com/moj-analytical-services/splink/tree/v3.9.6/splink/files/spark_jars), but no legacy. 

I handled this on my site by loading the classic jar, and it solves the issue. With this workaround, I can register JaroWinklerSimilarity function coming from `uk.gov.moj.dash.linkage.JaroWinklerSimilarity` and run simple test with the function.

However, the **Second Problem** blocks me if I do not make a change to the code. [SparkLinker](https://github.com/moj-analytical-services/splink/blob/ce1c1ea3408109fdb62e6e26049c1cfda26289ab/splink/spark/linker.py#L81C12-L81C12) registers udfs from jar automatically. And amongst them, it tries to load [LevDameraueDistance](https://github.com/moj-analytical-services/splink/blob/ce1c1ea3408109fdb62e6e26049c1cfda26289ab/splink/spark/linker.py#L281).

I checked the classes inside the scala-udf-similarity-0.1.0_classic.jar and the class is not available. Further checking shows that the LevDameraueDistance class is only available on 0.1.1 jar.

Is there a workaround to this problem? Would Spark 2 work with (Spark 3) 0.1.1 jar without any issue?

### To Reproduce

Run [Splink Spark Backend demo](https://github.com/moj-analytical-services/splink/blob/v3.9.6/docs/demos/examples/spark/deduplicate_1k_synthetic.ipynb ) with Spark 2

### OS:

Unix

### Splink version:

3.9.6

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ThomasHepworth** [comment]
Thanks for the report. We're conscious of the fact that the jars aren't currently working as intended and we're planning to fix it for the next release (which should be next Wednesday).

Just a warning too, we've recently updated Splink to require python >= 3.8. We're not wedded to this, but it makes our lives easier with regards to dependency management. 

If this is an issue, please do let us know and we'll see if we can work around the existing issues or just roll back some of our changes and return to supporting py 3.7.

**Comment by robertusvincent** [comment]
First of all, thank you for your quick response.
Will the release next week fix the spark backend issue? And do you foresee any Spark 2 compatibility issue with it?

Unfortunately, I am bound to Python 3.7, especially if there is no strong enough argument to move to 3.8 (as you mentioned, Splink 3 is not wedded to Python 3.8). Is there any existing issue with Python 3.7 except for dependency management? 
Or is there any Splink 3.x version that would be compatible with Python 3.7 + Spark 2.4.7 for the time being?
