### ISSUE TITLE
[FEAT] use base 10 for log odds

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1649]
### Is your proposal related to a problem?
converting log odds to odds is not intuitive for me. I'd imagine it is even harder for non-computer scientists to convert.

### Describe the solution you'd like
Instead of base 2, use base 10.

Then, log odds is what order of magnitude: 1 -> 10 times more likely, 2 -> 100 times more likely, etc

I think this would also allow the charts to use more intuitive axes too: Instead of showing the range [-15, 15] on many charts (https://moj-analytical-services.github.io/splink/charts/match_weights_chart.html, https://moj-analytical-services.github.io/splink/charts/waterfall_chart.html), we could instead use `labelExpr` argument to `altair.Axes` to make the labels instead be "10", "100", "1k", "10k", etc

I'm not sure if there is a principled reason why we need base 2. Is there some benefit of base 2 that I'm not thinking of?

**Comment by NickCrews** [comment]
Yeah makes sense that in the scientific/stats community they would use base 2. Would that be too fragmenting for us to use something different? Do you not really see a benefit?

**Comment by RobinL** [comment]
I def see the benefit but since it's relatively modest I think I'm probably minded to stick with the convention to make sure we align to textbooks/courses etc.   Does that make sense?

**Comment by NickCrews** [comment]
yeah sounds good!
