### ISSUE TITLE
BUG: `comparison_viewer_dashboard` vectors are not synced with histogram

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1651]
### What happens?

1. Go to https://moj-analytical-services.github.io/splink/charts/comparison_viewer_dashboard.html
2. zoom into the brush a little bit.
3. slide the brush from side to side
4. the upper histogram bars shift a little in regards to the vectors below them:

In this pic, the red "0" in the vector is underneath the really tall bar, the 3rd from the left
<img width="655" alt="image" src="https://github.com/moj-analytical-services/splink/assets/10820686/c19685d8-a4b9-40af-bdb7-447c494724b0">

If I slide the brush over a tiny bit, the histogram slides over, but the vector values do not. Now the red "0" is underneath a different bar:
<img width="683" alt="image" src="https://github.com/moj-analytical-services/splink/assets/10820686/858d869e-8d47-4e00-97a8-e852b06c4370">

### To Reproduce

see above

### OS:

NA

### Splink version:

main

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Ah - thanks for report.  I just took a quick look and I think the filter is applied but the order is not guaranteed i.e. the grid contains all the right records, but they're not guaranteed to align to the bars.

I will fix next week

**Comment by RobinL** [comment]
Issue here is that 
- each bar in the stop chart represents a record from df_predict. it is sorted by fiinal match_weight from the record, which is term-frequency adjusted (assuming tf adjustments are on in the model)
- The elements in the comparison vector grid do not represent records - they do not have a final match weight.  Instead, they're sorted by the sum of the (non tf adjusted) match weights.

So where there's a difference in ordering between example tf-adjusted match weights  and average match weights, there's a mismatch in the ordering between the two charts.
