### ISSUE TITLE
Linker API subset pages in docs have all methods

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1663]
The focussed Linker API pages (e.g. [Estimating model parameters](https://moj-analytical-services.github.io/splink/linkerest.html) and [Exploratory analysis](https://moj-analytical-services.github.io/splink/linkerexp.html)) now each show _all_ linker methods, rather than just the relevant subset.

**Comment by ADBond** [comment]
Weirdly this is not an issue when I build the docs locally

**Comment by RobinL** [comment]
Maybe we should just delete the focussed api pages?  @RossKen  does anyone actually look at them (we have stats now don't we?)

I practice I find the main use for the API pages is to link people to a relevant section, and i usually use the full api page for that just because it's easy to search the page to find what i want because everything's there

**Comment by RossKen** [comment]
Yea, that is an interesting point - so some stuff from the last month of analytics:
Full API:
<img width="718" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/263d4ec9-98ac-4543-a097-fd2e952ad58e">

Specific pages:
<img width="666" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/72a3fded-6652-4a2b-8944-d1765253808b">
<img width="661" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/de672ba9-19dd-4bc3-b922-89a3f9a4ce8a">
<img width="668" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/793f8792-ca7c-4cc8-a44d-8ce77fd6c918">
<img width="670" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/8ba4e173-c755-4118-8364-e540a50c2c6a">
<img width="672" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/53e7f494-023f-4742-aae5-5d8ff7c36b46">
<img width="676" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/841a9f60-5492-42f5-b2b7-035015784fc3">


So they do drive some traffic. However, that isn't to say they are entirely necessary when the same information can come from the full api

**Comment by RobinL** [comment]
Interesting - that's actually more traffic than i was perhaps expecting so perhaps they do have more value than i thought

**Comment by RossKen** [comment]
This could be down to the links referring to them in the tutorial rather than users really wanting them 
<img width="778" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/c4de30cb-4674-4dc2-a36f-127cdd911471">

**Comment by RobinL** [comment]
Fixed by Splink 4
