### ISSUE TITLE
[MAINT] Consolidate our multiple linkers/introducing lazy factories

### ISSUE THREAD

**Issue by ThomasHepworth** [moj-analytical-services/splink#1670]
### Is your proposal related to a problem?
See the dicussion issue https://github.com/moj-analytical-services/splink/issues/1644#issuecomment-1774689385, which highlights one aspect of this.

<hr>

## Consolidating Our Linkers: An Overview
As Splink has expanded and we've added support for more linkers, the complexity of our code, particularly for our predefined [comparisons and blocking rules](https://github.com/moj-analytical-services/splink/blob/master/splink/duckdb/duckdb_helpers/duckdb_comparison_imports.py), has started to become unwieldy.

The inheritance patterns currently in use are challenging to follow and the structure of the project has led to extensive code duplication (see all of our comparison scripts).

Robin and I believe it might be possible to simplify this by consolidating everything into single objects, with their required SQL characteristics generated based on the 'dialect' set within the settings dictionary.

In the case of our linkers, we would only need to import from a central linker class - `from splink.linker import Linker`. This class would then determine the appropriate dialect variant to use under the hood via a factory.

Similarly, our comparisons and blocking rules could be generated using centralised classes, with their contents updated lazily based on the dialect.

As an example, here's what we envision the API for our linker will look like in the future.

**From this...**
```py
from splink.duckdb.duckdb_linker import DuckDBLinker
import splink.duckdb.comparison_library as cl
import splink.duckdb.blocking_rule_library as br
from splink.datasets import splink_datasets

df = splink_datasets.historical_50k

settings = {
    "probability_two_random_records_match": 0.01,
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        br.block_on("first_name")
    ],
    "comparisons": [
        cl.exact_match("surname")
    ]
}

linker = DuckDBLinker(df, settings)
```

**To this...**
```py
from splink.linker import Linker
import splink.comparison_library as cl
import splink.blocking_rule_library as br
from splink.datasets import splink_datasets

df = splink_datasets.historical_50k

settings = {
    "dialect": "duckdb",
    "probability_two_random_records_match": 0.01,
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        br.block_on("first_name")
    ],
    "comparisons": [
        cl.exact_match("surname")
    ]
}

linker = Linker(df, settings)
```

Simply by required that the user specify the `dialect` key be passed on startup.

## Suggestion for initial Implementation - lazy factories
... I'll write up some dummy code and an overview of how this would function in the morning ...

## Benefits
* Simplified API for users.
* Streamlined codebase for easier navigation.
* Reduction of anti-patterns that have emerged, minimizing the need for copy-pasting comparisons and blocking rules.
* Removal of many [dialect-specific docstrings](https://github.com/moj-analytical-services/splink/blob/master/splink/blocking_rules_library.py#L35), which are currently duplicated.

### Blocking Rules and Comparisons
Blocking rules and comparisons serve as SQL factories, requiring information on the dialect to use the correct functions and quotation styles.

Introducing a mechanism for [lazy execution](https://stackoverflow.com/questions/61942205/lazy-class-factory) or behavior that can be modified when a dialect is set seems necessary.

Specifically, we aim to enable someone to run `br.block_on("first_name")` independently and receive a meaningful text output. When provided with a dialect by our linker, it should be configured and executed accordingly.

Currently, we benefit from useful autocompletion in our libraries, displaying available functions per backend basis, like so:
```python
import splink.duckdb.comparison_library as cl
cl. -> reveals the list of available functions (see below)
```
![image](https://github.com/moj-analytical-services/splink/assets/45356472/5768ea4f-fb3d-4191-95ce-f7873c7e51a1)

Although we will lose this functionality, it appears to be a minor loss, especially if replaced with informative error messages. We can likely employ ABC (Abstract Base Classes) to define the SQL needed for creating a function. In cases where this information is missing, we can raise an error.

To compensate for the missing import information, we could create a reference table outlining available comparisons and blocking rules across our supported dialects, similar to the [tables](https://moj-analytical-services.github.io/splink/comparison_library.html) in the documentation.

### Additional notes
I don't believe we should consider setting a default dialect for any of our classes ("duckdb", for example). This feels as if it will be confusing for users, as opposed to erroring and reporting the issue to the user.

It also strays away from our strict settings schema checker, which we can use to enforce this without much pain.

**Comment by RobinL** [comment]
Was thinking about this last night.  I think the one thing you might need to keep is the backend specific linkers (DuckDblinker etc).  Because for example you might need to pass spark into the spark linker, or a duckdb connection into the duckdb one.  Which is to say, I don't see any reason they use that would need pass backend specific information into the blocking rules, comparisons etc.   But there is a need for this with the linker

**Comment by ThomasHepworth** [comment]
Closing as this is now superseded by - https://github.com/moj-analytical-services/splink/issues/1679.
