### ISSUE TITLE
There is not "Data linking quick start" notebook

### ISSUE THREAD

**Issue by javidsch** [moj-analytical-services/splink#168]
https://github.com/moj-analytical-services/splink
On interactive demo, could not find **Data linking quick start: _quickstart_demo_linking.ipynb_**

**Comment by RobinL** [comment]
Hello - i was in the process of updating these to correspond to Splink 1.0.

This is now done and you can find it here:
https://github.com/moj-analytical-services/splink_demos/blob/master/quickstart_demo_linking.ipynb
