### ISSUE TITLE
Connection refused using SparkLinker

### ISSUE THREAD

**Issue by msp297** [moj-analytical-services/splink#1680]
### What happens?

Im using a Spark session to make predictions. When trying to perform the calculation of m values using the blocking parameter rules, I get the following error: ConnectionRefusedError: [Errno 111] Connection refused. I only get this for the email comparison parameter, but not for the previous calculated name comparisons.

### To Reproduce

My settings are:
settings = {
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        brl.exact_match_rule("first_name"),
        brl.exact_match_rule("name"),
    ],
    "comparisons": [
        ctl.name_comparison('first_name'),
        ctl.name_comparison("name"),
        ctl.email_comparison("contactemail", term_frequency_adjustments_full=False, include_exact_match_level=False, include_domain_match_level=True, 
                             include_username_match_level=True),    
        cl.exact_match("contactphone", term_frequency_adjustments=False),
        cl.exact_match("contactlignedirecte", term_frequency_adjustments=True),
        cl.exact_match("contactotherphone", term_frequency_adjustments=False),
    ],
    "retain_intermediate_calculation_columns" : False,
    "retain_matching_columns" : True

And then I just instantiate the linker as in the examples, estimate the u values by random sampling and start blocking parameters. The two following execute without issues: 
blocking_rule_first_name = brl.exact_match_rule("first_name")
linker.estimate_parameters_using_expectation_maximisation(blocking_rule_first_name)

blocking_rule_name = brl.exact_match_rule("name")
linker.estimate_parameters_using_expectation_maximisation(blocking_rule_name)

But the error comes when performing: 

blocking_rule_email = brl.exact_match_rule("contactemail")
linker.estimate_parameters_using_expectation_maximisation(blocking_rule_email)

And the same error comes out with the other three parameter comparisons.

### OS:

Linux

### Splink version:

3.9.8

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Closing due to SPlink 4 being released.  Feel free to reopen if still having problems
