### ISSUE TITLE
DB type error when creating ave_months_between function in postgres 9.4

### ISSUE THREAD

**Issue by sluhn-harrisr** [moj-analytical-services/splink#1685]
### What happens?

I use an older version of postgres (9.4.24), and when going to create a `PostgresLinker`, I get the following error:

```
psycopg2.errors.InvalidFunctionDefinition: return type mismatch in function declared to return double precision
DETAIL:  Actual return type is numeric.
CONTEXT:  SQL function "ave_months_between"`
```

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidFunctionDefinition) return type mismatch in function declared to return double precision
DETAIL:  Actual return type is numeric.
CONTEXT:  SQL function "ave_months_between"

[SQL:
        CREATE OR REPLACE FUNCTION ave_months_between(x date, y date)
        RETURNS float8 AS $$
        SELECT datediff(x, y)/30.4375;
        $$ LANGUAGE SQL IMMUTABLE;
        ]
```

It seems that, at least in this version of postgres, it is not automatically casting the function result to `float8` but rather to `numeric`, which causes an error.

I believe that simply changing the function definition to explicitly cast to `float8` would do the trick, as in the below snippet.

```sql
CREATE OR REPLACE FUNCTION ave_months_between(x date, y date)
RETURNS float8 AS $$
SELECT (datediff(x, y)/30.4375)::float8;
$$ LANGUAGE SQL IMMUTABLE;
```

If i manually create that function, postgres does not complain.  Of course, I am still unable to create a `PostgresLinker`, since it wants to replace that function with the original one when it's created.

### To Reproduce

You need a postgres database for this.  I do not know if the problem goes away for a newer version of postgres; as mentioned above I use 9.4.24 (I'm not able to upgrade beyond this version).

The script below should demonstrate the issue, after entering the correct connection info when creating the sqlalchemy engine.

```python
from sqlalchemy import create_engine
from splink.postgres.linker import PostgresLinker

username='???'
host='???'
dbname='???'
engine=create_engine(f"postgresql+psycopg2://{username}@{host}/{dbname}",isolation_level="AUTOCOMMIT")

settings={
    "link_type": "dedupe_only",
    "unique_id_column_name": "id"
}

pglinker = PostgresLinker('test', settings, engine=engine)
```

### OS:

Windows 10 as well as Ubuntu (via WSL on windows)

### Splink version:

3.9.8

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment]
Ah interesting - apologies, have only been testing this with newer versions of Postgres. If you are comfortable to feel free to [put in a PR with your fix](https://moj-analytical-services.github.io/splink/CONTRIBUTING.html#contributing-code) and I will take a look at it. If not then I will try to have a look into this a bit once I have some time.
