### ISSUE TITLE
`_names_of_tables_created_by_splink` is unused

### ISSUE THREAD

**Issue by OlivierBinette** [moj-analytical-services/splink#1686]
### What happens?

The Linker class attribute `_names_of_tables_created_by_splink` appears to be unused. From a file search, I see 5 matches to this variable, none of which transform the variable from it's original `set()` assignment.

This could be causing bugs or unexpected behavior.

**Context:**

I would like to build my data pre-processing and post-processing on top of Splink abstractions, as much as possible. For Athena, I might use my Linker's `query_sql()` or `create_table()` methods to create the processed tables that are ready to link. This could simplify the code and make cleanup (deleting intermediate tables) easier.

However, it's a little bit unclear or uncertain how Splink intends to keep track of tables it creates for cleanup purposes. 

### To Reproduce

Search in the entire repo:

![image](https://github.com/moj-analytical-services/splink/assets/784901/db576bdb-8fb2-4b5b-a254-cd58f850c4a6)

### OS:

Windows

### Splink version:

3.9.8

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
@ThomasHepworth looks like this can probably be deleted?  is this a relic from before we had `linker._intermediate_table_cache`?

**Comment by ThomasHepworth** [comment]
Yes, this was the historic way for recording which tables had previously been generated and has now been superseded by `linker._intermediate_table_cache`.

I think the Athena linker needs to have the garbage collection method tweaked slightly, but other than that, we should be able to remove this without any issues.
