### ISSUE TITLE
InputColumn methods could be properties

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1688]
Lots of `InputColumn` methods (`name`, `name_l`, `l_name_as_l`, ...) could be properties instead, and I think that would make the usage of the class a little nicer.

Some of them may indeed make more sense to remain as methods, and there may be some reasons why things are as they are.

**Comment by RobinL** [comment]
Yes,  I think it's because when they were first written they had an argument.

I removed the argument, at which point they should have been made properties

https://github.com/moj-analytical-services/splink/commit/87b09c8a2d747ef428a599937f6602d73e570622
