### ISSUE TITLE
Splink is not working

### ISSUE THREAD

**Issue by DevanandamS2013** [moj-analytical-services/splink#169]
I couldn't able to run Splink with my Dataset. Am using it for past 2 months but I haven't faced this error before.
Am getting this for past 2 days. Is there any configuration changes made with Splink ??

I have attached the error message with this. (Dedupe with this case and its not working for other cases either) 
![image](https://user-images.githubusercontent.com/49081926/105705240-3a782580-5f10-11eb-9f81-7b4ccc4ec673.png)

**Comment by spencertollefson** [comment]
It looks like there were breaking changes made a few days ago to the Splink() API.

You can see the CHANGELOG here:
https://github.com/moj-analytical-services/splink/blob/master/CHANGELOG.md

**Comment by RobinL** [comment]
Thanks @spencertollefson 

That's correct -  @DevanandamS2013  it looks like you've upgraded to the latest version v1.0.0, which has some breaking changes to the API.

You need to either:
Install a previous version. `pip install splink==0.4.2`. (you might need `--force-reinstall `)
or
Update your code to reflect the new API.  In this case:
`Splink(settings, df, spark).get_scored_comparisons()`

**Comment by DevanandamS2013** [comment]
Thanks alot for your help @spencertollefson @RobinL 
Yes, with deduplication it worked now with the change. Can you please let us know the syntax for link as well ??
I tried Splink(settings, df_l = df1, df_r = df2, spark). But its not working.

**Comment by RobinL** [comment]
You can see the new API in the docstring here:

https://github.com/moj-analytical-services/splink/blob/9c116c3f01a1a97257c343940f2bf7cfa044a8b7/splink/__init__.py#L44

**Comment by DevanandamS2013** [comment]
Thank you very much @RobinL
