### ISSUE TITLE
 TypeError: missing a required argument: 'spark'

### ISSUE THREAD

**Issue by yukuansong** [moj-analytical-services/splink#170]
<img width="1180" alt="Screen Shot 2021-01-28 at 5 23 19 PM" src="https://user-images.githubusercontent.com/4973298/106206268-c6e34c00-618d-11eb-980a-8f222a15cfc8.png">

The same code worked ok a couple weeks ago. It failed today with the errors shown in the attachment. This must be related to the new release. Any ideas? thanks

**Comment by RobinL** [comment]
See https://github.com/moj-analytical-services/splink/issues/169

You'll want:
```
Splink(settings, [df_l, df_r], spark)
```
