### ISSUE TITLE
[FEAT] Sorting prediction DataFrame by match_weight/probability (or more)

### ISSUE THREAD

**Issue by medwar99** [moj-analytical-services/splink#1709]
### Is your proposal related to a problem?
Post-linkage quality checks can benefit from looking into specific views of the dataset; for example, looking at those records with high/low match weights/probabilities to get insight into whether rules should be tweaked. 

The SplinkDataFrame wrapper doesn't have a `sort_values()`-like method. To see the head of a sorted view into this often means converting to a DataFrame with `as_pandas_dataframe()` before sorting and peaking at the head of the resulting DataFrame, but this can be very costly if it pulls the entire database into RAM. For example, `splink_df.as_pandas_dataframe().sort_values('match_weight').head(n=10)` spikes memory usage before limiting the number of records, and `splink_df.as_pandas_dataframe(limit=10).sort_values('match_weight')` is the incorrect behavior (limit before order). Alternatively we could perform an subsequent "select * from table order by ..." on the table.

I'm not sure whether this sorting would be beneficial for all SplinkDataFrames or just the one returned by `predict()`. The predictions are where I see the most benefit of sorting. 

### Describe the solution you'd like
**If applying to all SplinkDataFrames:**
A method within SplinkDataFrame that allows for ordering (ascending or descending) by a given field within `columns_escaped`. This would allow the database to remain memory efficient, rather than creating a new sorted table or pulling it down to a pandas DataFrame to then be sorted. 

**If altering the underlying table would cause issue, then adding functionality to the conversion methods prior to appending the limit clause may also work:** 
I tried adding `sort_values=None` and `sort_direction="ASC"` parameters to `DuckDBDataFrame.as_pandas_dataframe()` which just appends an `f'order by {sort_values} {sort_direction}'` to the `sql` prior to the addition of the limit clause. Usage would then be `splink_df.as_pandas_dataframe(limit=10, sort_values="match_weights", sort_direction="DESC")`. This does the trick but still pulls the resulting data out into a DataFrame (may be what's wanted). It also has no effect on the underlying table which may be used elsewhere (may be a good thing).

### Describe alternatives you've considered
- I tried appending this to the end of the SQL used to construct the predictions table within DuckDB (i.e. `sql_used_to_create`) and re-executed that, but this would run table creation again and potentially may have other issues I'm not checking for (i.e. `cluster_studio_dashboard`).

### Additional context

**Comment by RobinL** [comment]
Prob a bit hard to find but I think you can achieve this using https://moj-analytical-services.github.io/splink/linker.html?h=quer#splink.linker.Linker.query_sql

For big data, you'll want to return it as a Splink dataframe.  In spark that can be turned into a spark dataframe with splinkdf.as_spark_dataframe.()

**Comment by medwar99** [comment]
Ah yes, totally missed that one!
