### ISSUE TITLE
[MAINT] `linker._intermediate_table_cache` logs multiple entries when creating term frequency tables

### ISSUE THREAD

**Issue by ThomasHepworth** [moj-analytical-services/splink#1737]
### What happens?

See https://github.com/moj-analytical-services/splink/pull/1061#issuecomment-1546708437.

In short, when generating our term frequency tables we are currently recording both the physical and templated names within `linker._intermediate_table_cache`.

This in turn makes clean-up of tables more annoying than it needs to be - https://github.com/moj-analytical-services/splink/issues/1686.

### To Reproduce

```py
from splink.duckdb.duckdb_linker import DuckDBLinker
import pandas as pd

from tests.basic_settings import get_settings_dict

df = pd.read_csv("./tests/datasets/fake_1000_from_splink_demos.csv")

linker = DuckDBLinker(
    df,
    get_settings_dict(),
)

linker.compute_tf_table("first_name")
linker._intermediate_table_cache
```

### OS:

iOS

### Splink version:

v3.9.9

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ThomasHepworth** [comment]
@RobinL, I've quickly drafted up a potential solution to address this issue, available for review [here](https://github.com/moj-analytical-services/splink/compare/remove_term_frequency_templated_names_from_cache).

The proposed changes include:

1. **Removal of Templated Names from the Cache**: For example, the name `__splink__df_concat_with_tf` will no longer appear in the cache.

2. **Addition of a Method for Templated Name Checks**: This method sequentially checks a list of provided templated names. This means that if you wish to search for both `tf_first_name` and `concat_with_tf`; `__splink_df_tf_first_name` is return immediately if found; otherwise we search for `__splink_df_concat_with_tf` and return it if found. This functionality is only intended for use with term frequency tables to determine if they have been generated without requiring any SQL hashing.

3. **Term Frequency Table Registration Changes** - Given the changes above, table registration will now overwrite the originally registered tf table. i.e. if `__splink__df_concat_with_tf` already exists (with any given hashed name), we will now overwrite this table with the table being registered.

It's important to note that this update is based on the assumption (which needs verification and may be incorrect) that in any single Splink session, only one term frequency table should be assigned per column or input nodes table.

Consequently, instead of generating two tables when running `compute_tf_table` or `initialise_df_concat_with_tf`, a single table will now be generated and its corresponding templated name will be utilised for cache references.

<details>
<summary>Term Frequency Caching Demo</summary>

**Replace `compute_tf_table(...)` with `_initialise_df_concat_with_tf` to check the input nodes version.**

```py
from splink.duckdb.duckdb_linker import DuckDBLinker
import pandas as pd

from tests.basic_settings import get_settings_dict

df = pd.read_csv("./tests/datasets/fake_1000_from_splink_demos.csv")

linker = DuckDBLinker(
    df,
    get_settings_dict(),
)

# Generates our primary tf table for 'first_name'
tf_table = linker.compute_tf_table("first_name").as_pandas_dataframe()

linker.register_term_frequency_lookup(tf_table, "first_name")  # errors
linker.register_term_frequency_lookup(tf_table, "first_name", overwrite=True)  # registers

**Comment by RobinL** [comment]
Link to our discussion about this so it doesn't get lost:
https://asdslack.slack.com/archives/D02TEUPB6H3/p1700482818591709

**Comment by ThomasHepworth** [comment]
Closing as this is stale and we are content with the current caching methodology.
