### ISSUE TITLE
`cumulative_num_comparisons_from_blocking_rules_chart` fails for `link_only` AthenaLinker

### ISSUE THREAD

**Issue by alanakilleen** [moj-analytical-services/splink#1738]
### What happens?

`cumulative_num_comparisons_from_blocking_rules_chart` fails for `AthenaLinker` in `link_only` mode when input tables have different schema.

### To Reproduce

1. Create two tables in Athena with different columns. 
2. Configure an `AthenaLinker` in `link_only` mode and `input_table_or_tables` set to those two tables.
3. Define any blocking rule and run `count_num_comparisons_from_blocking_rule` for that rule.

`count_num_comparisons_from_blocking_rule` will fail with `QueryFailed: COLUMN_NOT_FOUND`. 

### OS:

n/a

### Splink version:

v3.9.9

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
If I understand the question correctly, this is expected behaviour:
https://moj-analytical-services.github.io/splink/demos/tutorials/01_Prerequisites.html

![image](https://github.com/moj-analytical-services/splink/assets/2608005/57a3bc94-b914-4f78-a3c3-1e6f79a51edd)

**Comment by alanakilleen** [comment]
Oh I see, thank you! Would make sense to add a check for that when the Linker is created? I can create a feature request for that instead.

**Comment by ThomasHepworth** [comment]
Heya👋 If the error is due to the issue above, I believe we have an outstanding discussion somewhere (I've tried to find it, but we clearly didn't label is very well).

We have also been considering adding in the ability to generate column aliases for a while, but never found the time to do so.

Please do create an issue for this and we will try to resolve it when we find the time.

**Comment by RobinL** [comment]
@ThomasHepworth I think an initial version of this could just check the columns are the same, and if not raise a warning to say the input dataframes are not conformant

**Comment by alanakilleen** [comment]
Opened https://github.com/moj-analytical-services/splink/issues/1740. Closing this ticket. Thank you!
