### ISSUE TITLE
UDFRegistration.registerJava() not whitelisted

### ISSUE THREAD

**Issue by JonathanLaidler** [moj-analytical-services/splink#1744]
Hi Splink team,

This function is not whitelisted in my databricks environment.
org.apache.spark.sql.UDFRegistration.registerJava()

Unfortunately, the latest version of Splink uses it to import some distance metric UDFs. (line 277 of spark/linker.py).

Would it be possible to please add a parameter so that I can choose to bypass this line? (since I don't need the distance metric UDFs).
Otherwise, I think I will need to revert to an older version of Splink.

Thanks in advance.

Jonny

**Comment by RobinL** [comment]
Hi Jonathan,

Yes, I think we should be able to do this.

If you're interested in contributing to Splink,  you'd want to add an additional argument here e.g. `register_udfs_automatically`:

https://github.com/moj-analytical-services/splink/blob/26950eabce0f7f8d9e8cc13155c01c08d6e0ec61/splink/spark/linker.py#L97

The argument would then activate/deactivate this line of code from running:
https://github.com/moj-analytical-services/splink/blob/26950eabce0f7f8d9e8cc13155c01c08d6e0ec61/splink/spark/linker.py#L191

Probably the new argument wants a default value that means the `self._register_udfs_from_jar()` runs, but if the user sets the value of `register_udfs_automatically` false,  then `self._register_udfs_from_jar()` is not run.

We'll try to get around to doing this sometime next week hopefully if you're not able to add it.

Thanks,

Robin

**Comment by JonathanLaidler** [comment]
Hi Robin,

Thanks for the reply. Yes, that's exactly what I was thinking.
I'd love to contribute to Splink! It'll be next week, but I'll have a go at this.

Cheers,

Jonny

**Comment by JonathanLaidler** [comment]
Linting errors now fixed, please try and merge again.
Thanks!

**Comment by RobinL** [comment]
Closed by #1774
