### ISSUE TITLE
when will splink support spark 3.0?

### ISSUE THREAD

**Issue by yliu2018** [moj-analytical-services/splink#178]
according to this issue: https://github.com/moj-analytical-services/splink/issues/167
> **reason being that we use Spark 2.4 at the moment. Once we move to Spark 3.0 this jar will be updated.**

So could you let us know when will be Spark 3.0 supported? Or is it possible to publish the udf_similarity.jar compiled in spark 3.0 in the current splink repo for us to use? Is there other change needed in the pyspark code part of the splink repo to support spark 3.0?

thanks!

**Comment by RobinL** [comment]
Hello @yliu2018 .  We are already successfully using Splink in Spark 3.0.  The only change i seem to need to make everything work is that to set up `SparkConf()` you no longer need `extraClassPath`

i.e. Spark 2.4 you needed
```
    conf.set(
        "spark.driver.extraClassPath",
        "/Users/robinl/Documents/data_linking/splink/jars/scala-udf-similarity-0.0.8.jar",
    )
    conf.set(
        "spark.jars",
        "/Users/robinl/Documents/data_linking/splink/jars/scala-udf-similarity-0.0.8.jar",
    )
```

Now you just want:

```

    conf.set(
        "spark.jars",
        "/Users/robinl/Documents/data_linking/splink/jars/scala-udf-similarity-0.0.8.jar",
    )
```

**Comment by yliu2018** [comment]
@RobinL Thanks for the explanations. Right now in the github of splink, there is no scala-udf-similarity-0.0.8.jar  (only 0.0.6, 0.0.7). Can you please publish 0.0.8.jar to the repo (which I suppose that's compiled using spark 3.0)? Thanks!
https://github.com/moj-analytical-services/splink/tree/master/jars

**Comment by RobinL** [comment]
Hiya.  We do have a later version that we'll publish soon but it's compiled in the same way as previous versions.  It's only different in that it contains additional functions.  Are you getting errors with the jar in spark 3.0?  If so, could you post the error message (and, ideally, what code you're running that causes the error)

**Comment by yliu2018** [comment]
Great! Let me try with the existing jar 0.0.7. Will report errors if there is any. Thanks!

**Comment by yliu2018** [comment]
I can do this and it works well in spark 3.0 with splink 1.0.3:
```SparkConf().set("spark.jars", "jars/scala-udf-similarity-0.0.7.jar")```
thanks!
