### ISSUE TITLE
Postgres linker fails when reading columns from information_schema

### ISSUE THREAD

**Issue by krixon** [moj-analytical-services/splink#1786]
### What happens?

When constructing a `PostgresLinker`, the following error occurs:

```
  File "[redacted]/splink/postgres/linker.py", line 34, in <listcomp>
    cols = [r["column_name"] for r in res]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 48, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str
```

The code in question is:

```
@property
    def columns(self) -> list[InputColumn]:
        sql = f"""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = '{self.physical_name}';
        """
        res = self.linker._run_sql_execution(sql).fetchall()
        cols = [r["column_name"] for r in res]
```

`res` is an SQLAlchemy `Row` object.

### To Reproduce

Based on the example code in the Postgres backend docs. I have added query logging, and set the isolation level to `AUTOCOMMIT` to work around #1785.

```
from splink.postgres.linker import PostgresLinker
from sqlalchemy import create_engine
import logging


logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

engine = create_engine("postgresql+psycopg2://postgres:password@localhost:55432/linking")
engine = engine.execution_options(isolation_level="AUTOCOMMIT")

settings = {
    "link_type": "dedupe_only",
}

# Error is triggered by the following line:
linker = PostgresLinker("people", settings, engine=engine)
```

If I change `cols = [r["column_name"] for r in res]` to `cols = [r.column_name for r in res]` the error goes away.

### OS:

iOS

### Splink version:

3.9.9

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Closed by #1908
