### ISSUE TITLE
In latest version .3 when I try to influence u and m prob they are overridden in the saved model

### ISSUE THREAD

**Issue by Freewilly3d** [moj-analytical-services/splink#179]
Is there something else that I need to do now?

**Comment by RobinL** [comment]
Please could you provide a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem you're facing - otherwise we don't know enough about what you're doing to help

**Comment by Freewilly3d** [comment]
[currentconfig.txt](https://github.com/moj-analytical-services/splink/files/6077140/currentconfig.txt)

[blklatlng_02261715 - Copy.txt](https://github.com/moj-analytical-services/splink/files/6077147/blklatlng_02261715.-.Copy.txt)

In the scenario above I find the percent's are different in the saved model than in my original config.   Is this value recalculated or not?  It doesn't appear in the logs associated with the the 10 iterations so it doesnt appear to being calculated but the saved value is different than my original config.

I'm trying to compare a number of columns that are names from different sources and strongly influence the score if there is a match and also if there is a non match.

A couple other comments:
I tried adding the additional columns I'm comparing in the comparison columns and setting them to 1 for no influence; then I did each compare of the comparison columns in the case statement .  This resulted in a significant overstatement of the initial percent and the the bayse influence of my column guesstype.  As a result I came up concatenating the names and splitting them to reference each value to get around that.  I'm interested in any other suggestions about different ways to accomplish this.  Basically I'm trying to do an  compare 2 sets of name columns comparing every combination and I want to treat each comparison as an "or" so if any of them score high it sets the gamma to 2 etc.
thanks

**Comment by RobinL** [comment]
This is controlled by:
```
"fix_u_probabilities": false,
"fix_m_probabilities": false
```
If you set this to false, the u and m values should be updated by splink as part of model estimation.
If you set to true, the u and m values will stay the same as whatever they started as (i.e. whatever values you hard code in the settings object).

Are you seeing different behaviour to this?

**Comment by Freewilly3d** [comment]
Yes what tripped my up is its in lowercase in the saved model and needs to be in mixed case in the config that your running with.
