### ISSUE TITLE
Incorrect URLs in README.md/linker.py

### ISSUE THREAD

**Issue by KyleHaynes** [moj-analytical-services/splink#1801]
### What happens?

There appears to be two references to incorrect URLs:

![image](https://github.com/moj-analytical-services/splink/assets/5267027/653c7118-3a78-4f51-aa07-2b96d0ed767c)

`splink/demos/` should be updated to `splink/demos/tutorials`?

### To Reproduce

visit https://moj-analytical-services.github.io/splink/demos/00_Tutorial_Introduction.html (doesn't work)
visit https://moj-analytical-services.github.io/splink/demos/tutorials/00_Tutorial_Introduction.html (does work)

**Comment by jdesai-care** [comment]
I see that there are other URLs in the documentation which doesn't work, e.g.

https://moj-analytical-services.github.io/splink/topic_guides/splink_fundamentals/comparison_level_library.md
https://moj-analytical-services.github.io/splink/topic_guides/demos/examples/deduplicate_50k_synthetic.ipynb
https://moj-analytical-services.github.io/splink/topic_guides/demos/examples/spark/deduplicate_1k_synthetic.ipynb

**Comment by RobinL** [comment]
Thanks very much for the report, we'll fix asap!

**Comment by RossKen** [comment]
> https://moj-analytical-services.github.io/splink/topic_guides/demos/examples/spark/deduplicate_1k_synthetic.ipynb

Hey @jdesai-care I'm just updating some links but can't find these ones in the docs. Whereabouts did you find them?

**Comment by jdesai-care** [comment]
I think most links on this page are broken.

Backends overview - Splink (moj-analytical-services.github.io)<https://moj-analytical-services.github.io/splink/topic_guides/splink_fundamentals/backends/backends.html>




________________________________

**Comment by RobinL** [comment]
@RossKen is this closed by https://github.com/moj-analytical-services/splink/pull/1805?

**Comment by RossKen** [comment]
Yes this is now fixed
