### ISSUE TITLE
truth_space_table_from_labels_table throws error with Pyspark

### ISSUE THREAD

**Issue by WillHoylesONS** [moj-analytical-services/splink#1822]
### What happens?

Following the steps to call the above function as listed in the [documentation](https://moj-analytical-services.github.io/splink/linker.html#splink.linker.Linker.truth_space_table_from_labels_table) throws an error when using Pyspark in a Jupyter Notebook running Python 3 on Vertex AI.

The error doesn't occur when following the same steps in a locally hosted Jupyter Notebook running Python 3.8.3 and DuckDB rather than Pyspark.

### To Reproduce

Initially there was an error being thrown because Pyspark was outputting blocking rule strings with a grave/backtick rather than quotation marks or apostrophes. I wrote the following function to fix that which seemed to work:
`def fix_blocking_rule_strings(linker):
    for rule in range(len(linker._settings_obj._blocking_rules_to_generate_predictions)):
        linker._settings_obj._blocking_rules_to_generate_predictions[rule].blocking_rule_sql = (
            str(linker._settings_obj._blocking_rules_to_generate_predictions[rule].blocking_rule_sql).replace("[backtick]","\'"))
    return linker`
(replace [backtick] with the backtick symbol. Doing so here breaks the formatting)

However, the function still fails further on at the line:
`    dataframe = linker._sql_to_splink_dataframe_checking_cache(
        sql_gen,
        output_tablename_templated,
        True,
    )`

Where it returns a SplinkException: "Error executing the following sql for table `__splink__truth_space_table`(__splink__truth_space_table_8e8b2472a)" 

The sql it refers to is too long to copy here but is generated elsewhere in Splink.

### OS:

Debian 11

### Splink version:

3.9.10

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Thanks for the report.  Are you able to post the incorrect blocking rule SQL that's being generated with back ticks?  The backtick in Spark is used to escape column identifiers and so its inclusion is deliberate (though that doesn't mean in this particular instance it's correct) - so it feels like this could bug be related to how we're escaping column names.  

So like:

In Spark SQL:

```sql
SELECT `first name` FROM your_table
```

Is equivalent to this in DuckDB:

```sql
SELECT "first name" FROM your_table
```

**Comment by WillHoylesONS** [comment]
Hi Robin,

So the error I get with the backticks is 'ParseError: Expecting ) Line 1, Col: 21.
  (SUBSTR(l.`first_name`, 1, 1) = SUBSTR(r.`first_name`, 1, 1)) AND (l.`birth_place` = r.`birth_place`) AND (l.`dob_year` ='

The blocking rule sql that's generated is:
(SUBSTR(l.`first_name`, 1, 1) = SUBSTR(r.`first_name`, 1, 1)) AND (l.`birth_place` = r.`birth_place`) AND (l.`dob_year` = r.`dob_year`)
(l.`surname` = r.`surname`) AND (l.`dob_year` = r.`dob_year`)
l.`first_and_surname` = r.`first_and_surname`
(l.`gender` = r.`gender`) AND (l.`surname` = r.`surname`)
(SUBSTR(l.`first_name`, 1, 1) = SUBSTR(r.`first_name`, 1, 1)) AND (l.`surname` = r.`surname`)
(SUBSTR(l.`first_name`, 1, 1) = SUBSTR(r.`first_name`, 1, 1)) AND (SUBSTR(l.`surname`, 1, 1) = SUBSTR(r.`surname`, 1, 1)) AND (l.`gender` = r.`gender`)

Cheers, Will

Will Hoyles (he/him)| Data Scientist | Office for National Statistics | Swyddfa Ystadegau Gwladol
+44 (0)7772 512519 | ***@***.******@***.***> | www.ons.gov.uk<http://www.ons.gov.uk/> | @ONS<http://twitter.com/ONS> | @ONSFocus<https://twitter.com/ONSfocus>

**Comment by RobinL** [comment]
Thanks.  The backticks in the sql looks ok to me.  I wonder whether there may be a missing comma or something like that in your settings object (in the 'blocking_rules_to_generate_predictions' part).  Are you able to post the code for your settings?

**Comment by WillHoylesONS** [comment]
I don’t think it’s that because I’ve used the same settings when running it locally with DuckDB and the parse error goes away when I replace the backticks with quote marks and is replaced by the SplinkException.

Here's the code for my blocking rules and settings:
```python
blocking_rule_1 = block_on(["surname", "dob_year"])
blocking_rule_2 = block_on(["first_and_surname"])
blocking_rule_3 = block_on(["substr(first_name, 1,1)", "surname"])
blocking_rule_4 = block_on(["substr(first_name, 1,1)", "birth_place", "dob_year"])
blocking_rule_5 = block_on(["gender", "surname"])
blocking_rule_6 = block_on(["substr(first_name, 1,1)", "substr(surname, 1,1)", "gender"])
blocking_rules = [blocking_rule_4, blocking_rule_1, blocking_rule_2, blocking_rule_5, blocking_rule_3, blocking_rule_6]

settings = {
            "link_type": "dedupe_only",
            "comparisons" : [
               ctl.name_comparison("full_name"),
               ctl.name_comparison("first_and_surname"),
               ctl.name_comparison("first_name", term_frequency_adjustments=True),
               ctl.name_comparison("surname"),
               #ctl.date_comparison("dob", cast_strings_to_date=True, date_format="%Y %m %d"),
               cl.exact_match("gender", term_frequency_adjustments=True), 
               cl.levenshtein_at_thresholds("birth_place", term_frequency_adjustments=True),
               cl.levenshtein_at_thresholds("occupation"),
               ctl.postcode_comparison("postcode_fake"),
               cl.levenshtein_at_thresholds("dob_year"),
               cl.exact_match("dob_month", term_frequency_adjustments=True),
               cl.exact_match("dob_day", term_frequency_adjustments=True) 
               ],
            "blocking_rules_to_generate_predictions" : blocking_rules,
            "retain_intermediate_calculation_columns" : True,
            "retain_matching_columns" : True
            } ```

**Comment by RobinL** [comment]
Agreed - can't see anything wrong there. If you just use a couple of the blocking rules (or even just one), do you still get the error? e.g. setting

```
blocking_rules = [blocking_rule_1, blocking_rule_2]
```

Where you say:
```
The sql it refers to is too long to copy here but is generated elsewhere in Splink.
```

Are you able to look through the SQL and find the part that's reporting the specific error - that may help me track down the cause.

I think the `'` is a bit of a red herring because it serves a different purpose in Spark SQL:

- The `'` (single quote) character is used for specifying string literals. When you enclose a sequence of characters in single quotes, Spark SQL interprets it as a string. For example, `'example'`.

- The `` ` `` (backtick) character is used for enclosing identifiers, such as column names or table names, especially when they contain special characters or are reserved keywords. It allows you to use practically any character in identifiers. For instance, `` `select` `` could be a valid column name when enclosed in backticks.

**Comment by WillHoylesONS** [comment]
The error comes up regardless of the number or type of blocking rules. It always catches on the first rule with the missing ) exception. When I replace the backticks with quotes I get the SplinkException above and the following:
```Error was: [DATATYPE_MISMATCH.BINARY_OP_DIFF_TYPES] Cannot resolve "(clerical_match_score >= 0.5)" due to data type mismatch: the left and right operands of the binary operator have incompatible types ("BOOLEAN" and "DECIMAL(1,1)") ```

**Comment by RobinL** [comment]
Aha - so I think this is probably not to do with the blocking rules.  At a guess if you use your current settings and call predict () it will work.  It looks like it's a bug with something to do with the threshold and the truth space from labels function.  I'll investigate this further when I have a moment

**Comment by cinnq346** [comment]
I think https://github.com/moj-analytical-services/splink/pull/1938 resolved this issue.
