### ISSUE TITLE
[Splink 4] DateComparison - pass type?

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#1862]
There is a slight issue with how we are dealing with columns in `DateComparison` for Splink 4.

The trouble is that we have (potentially) a mixture of date-like and string-like levels, and we can be dealing with either a string _or_ a date column. So (in some backends - noteably postgres) we can have errors in any configuration:

* `DateComparison("date_col")` has an error as our string-distance function doesn't accept `(DATE, DATE)`
* `DateComparison("str_col")` has an error as our date function doesn't accept `(text, text)`

We can convert strings to dates in `DateComparison` using `try_parse_date` if we _know_ we have a string column, but atm that is only (partially) implied by `invalid_dates_as_null`. We could also implement our date functions to accept text, and our distance functions to accept strings, but that does not seem very robust (and could require work for each backend).

I think probably the cleanest way is tweaking the interface a bit so that we specify whether we are dealing with a text or date column, and then we can use `ColumnExpression` to perform the relevant transforms for each level.

**Comment by RobinL** [comment]
This is fixed in the splink4 release with input_is_string=bool
