### ISSUE TITLE
Splink4: database_api contains imports that are not installed by default (e.g. pyspark)

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#1932]
![image](https://github.com/moj-analytical-services/splink/assets/2608005/d2fdaf62-b6ed-4bc8-bf0f-cbbee08da9eb)
https://github.com/moj-analytical-services/splink/blob/4271722acd153d792f4ef9b9f68e09c537516959/splink/database_api.py#L14

**Comment by ADBond** [comment]
Think it would be probably good to break this module up eventually anyhow, maybe something like

database_api/
├─ __init__.py  # imports `DuckDBAPI`, `SparkAPI` etc
├─ database_api.py  # core definition
├─ duckdb_api.py  # DuckDBAPI
...

but probably want to think a bit about the whole module structure to see what will make the most sense

**Comment by RobinL** [comment]
Has been fixed in splink4
