### ISSUE TITLE
FYI: you're using an old version of poetry

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1986]
I noticed poetry.lock says `generated by Poetry 1.4.2`, which is nearing a year old. If you updated, maybe resolving would be faster, or it might result in different packages. As I worked on https://github.com/moj-analytical-services/splink/pull/1968 the diff in the the poetry.lock file was quite different simply due to me using poetry 1.7.1, so it was hard to separate the changes due to the looser dependency ranges, and simply due to a newer version of poetry.

**Comment by RobinL** [comment]
Splink4 should have resolve any issues with lockfile
