### ISSUE TITLE
Sqlglot 23.0.0 breaks EM Training

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#2072]
### What happens?

Via `_get_comparison_levels_corresponding_to_training_blocking_rule` and `ComparisonLevel._is_exact_match` we end up with the error.

```sh
if identifiers[0] == identifiers[1]:
       ~~~~~~~~~~~^^^
IndexError: list index out of range
```

Working on v22.2.1 (as in lockfile) - not sure of the exact `sqlglot` version where this breaks

### To Reproduce

With `sqlglot==23.0.0`:

```py
import splink.duckdb.comparison_library as cl
from splink.duckdb.linker import DuckDBLinker
from splink.datasets import splink_datasets

settings = {
    "link_type": "dedupe_only",
    "unique_id_column_name": "unique_id",
    "comparisons": [
        cl.levenshtein_at_thresholds(
            "first_name", [2], term_frequency_adjustments=True
        ),
        cl.levenshtein_at_thresholds("surname", [1], term_frequency_adjustments=True),
    ],
}

df = splink_datasets.fake_1000

linker = DuckDBLinker(df, settings)
blocking_rule = "l.first_name = r.first_name"
training_session_fn = linker.estimate_parameters_using_expectation_maximisation(
    blocking_rule
)
```

### OS:

Debian

### Splink version:

3.9.13

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
![image](https://github.com/moj-analytical-services/splink/assets/2608005/f450f3b1-5ab4-4e93-aabb-8caaf672a144)
https://github.com/tobymao/sqlglot/commit/8f09dcef858225b1b1601c6b89213c26fb1c7464
