### ISSUE TITLE
IndexError: List index out of range when calling linker.estimate_parameters_using_expectation_maximisation(training_blocking_rule)

### ISSUE THREAD

**Issue by sthamodh** [moj-analytical-services/splink#2084]
### What happens?

Hi,

The following code is picked up from the example page here: [spark example](https://moj-analytical-services.github.io/splink/demos/examples/spark/deduplicate_1k_synthetic.html)

I have had this code work many times before without any issues.

The error I get is from the expectation maximization step as shown below

![list_index_error_part1](https://github.com/moj-analytical-services/splink/assets/156929377/e57c9c42-7c91-4319-80b8-1642b0fe11bd)

I did a little snooping around and was able to trace back to the step below and when I ran this piece of code after the SparkLinker step, I get the same error as shown in the screenshots below.

`linker._settings_obj._get_comparison_levels_corresponding_to_training_blocking_rule("l.first_name = r.first_name and l.surname = r.surname")`

![list_index_error_part2](https://github.com/moj-analytical-services/splink/assets/156929377/313f452e-edd8-4be8-9beb-b99a91e5bcaa)

![list_index_error_part3](https://github.com/moj-analytical-services/splink/assets/156929377/dee9968a-d362-4f40-9ba0-c5f9caa281e3)

I have no idea why this would happen and all of the developed code from my solution (deduplicating corporate addresses) also fails in this step.

### To Reproduce

1. I used the [spark example](https://moj-analytical-services.github.io/splink/demos/examples/spark/deduplicate_1k_synthetic.html)
2. I ran it on a single user cluster on databricks with 12.2 LTS ML as the runtime. Here is a screenshot of the cluster configuration:

![cluster_configuration](https://github.com/moj-analytical-services/splink/assets/156929377/14d6e6a9-d50a-454a-8f44-b0707111299f)
 

### OS:

Databricks runtime version: 12.2 LTS ML (includes Apache Spark 3.3.2, Scala 2.12)

### Splink version:

3.9.13

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment]
See [this comment](https://github.com/moj-analytical-services/splink/issues/2076#issuecomment-2007755672)

**Comment by RobinL** [comment]
Closed by https://github.com/moj-analytical-services/splink/pull/2079
