### ISSUE TITLE
[FEAT] Add GitHub action to sort/update custom dictionary

### ISSUE THREAD

**Issue by zslade** [moj-analytical-services/splink#2100]
### Is your proposal related to a problem?

`custom_dictionary.txt` is updated as part of the manual spellchecking process but it's time consuming to add words in alphabetical order.

Related to PR: #2025 

### Describe the solution you'd like

Set up a GitHub Action to automatically alpha-sort the custom dictionary when updates to it are merged into `master` and/or `splink4_dev`.
Removing duplicates from the dictionary could also be done as part of this Action.

This information also needs to be reflected in the documentation on using the spellchecker.

**Comment by RobinL** [comment]
I think this is possibly overkill in terms of infra complexity. 

When I added some terms I used the sort command in vs code:
![image](https://github.com/moj-analytical-services/splink/assets/2608005/facbaa60-fbd0-4711-9eb5-f75fe6ca7bad)

**Comment by zslade** [comment]
Makes sense, thank you. Happy for this issue to be closed and I can just update the docs accordingly 👍

**Comment by RobinL** [comment]
thank you!  (sorry was just doing a bit of an issue review this morning)
