### ISSUE TITLE
New TF adjustments (v2.0.0) need adding to waterfall charts

### ISSUE THREAD

**Issue by samnlindsay** [moj-analytical-services/splink#217]
Currently the waterfall charts only show how the `match_probability` is calculated, not showing the extent of the TF adjustment made to that final probability. Now each column can have two components in the waterfall chart: the baseline BF contribution for a match, and the TF adjustment for the specific value.

Whether or not TF adjustments are even turned on, the potential impact on each column can easily be included in the data passed to the waterfall chart.  Potentially worth showing whether TF adjustments _could_ account for significant differences in final match weights.

**Comment by RobinL** [comment]
I think we want to write this so there are two options:

- The column-specific tf adjustments exist in the input dataset and the waterfall can therefore show the column-specific adjustments
- The user provides only the final match_probability/match_weight and the comparison vector.  In which case we can compute only a single 'all-in' tf adjustment, which is just the difference between the match_weight computed from the average m and u values (which we can compute from the comparison vector and splink settings), and the final match_weight

**Comment by RobinL** [comment]
Closed by #278
