### ISSUE TITLE
Blocking rules are ignored by Splink model

### ISSUE THREAD

**Issue by Rebecasarai** [moj-analytical-services/splink#227]
Dear team,

I wanted to congratulate you for the great work done with Splink! Currently, I'm using it for a deduplication project with relatively large datasets (Around 600k rows each dataset, the smallest ones can be around 50k).

I'm setting a configuration file for Splink as:

```json
{
    "link_type": "dedupe_only",
    "blocking_rules": [
        "l.postal_code = r.postal_code AND l.col_example_1 = r.col_example_1 AND l.col_example_2 = r.col_example_2 AND l.col_example_3 != r.col_example_3 AND l.province = r.province"
    ],
    "comparison_columns": [
        {
            "col_name": "col_example_4",
            "data_type": "numeric",
            "num_levels": 2,
            "case_expression": "Catch the nulls with -1, if identical 1, otherwise 0."
        },
        {
            "col_name": "col_example_5",
            "data_type": "numeric",
            "num_levels": 2,
            "case_expression": "Catch the nulls with -1, if identical 1, otherwise 0."
        },
        {
            "col_name": "col_example_6_with_inverse_correlation",
            "data_type": "numeric",
            "num_levels": 3,
            "case_expression": "Catch the nulls, set levels for: 2 if they are identical, 1 if they are in a range of numeric difference, otherwise 0."
        },
        {
            "col_name": "col_example_7_with_inverse_correlation",
            "data_type": "numeric",
            "num_levels": 3,
            "case_expression": "Catch the nulls, set levels for: 2 if they are identical, 1 if they are in a range of numeric difference, otherwise 0."
        },
        {
            "col_name": "col_example_8",
            "data_type": "string",
            "num_levels": 3,
            "case_expression": "Catch nulls and set levels with jaro_winkler_sim()"
        },
        {
            "num_levels": 2,
            "case_expression": "Custom SQL expression: if col_example_9 is a certain type then take col_example_10 into account",
            "custom_columns_used": [
                "col_example_9",
                "col_example_10"
            ],
            "data_type": "string",
            "custom_name": "custom_col_example"
        },
    ],
    "additional_columns_to_retain": [
        "id_col_example",
        "id_col_for_item",
        "date_col"
    ],
    "em_convergence": 0.01
 }
```

Note that `col_example_6_with_inverse_correlation` and ` col_example_7_with_inverse_correlation` have an **inverse/negative correlation**: When the first one has a value, then the other is null and viceversa.

When checking the matching results, I see that the blocking rules are ignored. 

For example, **postal_code isn't the same in all records segmented into an estimated matching group (Pair or group of duplicates)**. In almost all matching groups there is at least 1 record that doesn't follow the blocking rules.

If `blocking_rules` avoid comparisons, why are these comparisons between different postal codes still happening? 

Kind regards,
Rebeca

**Comment by RobinL** [comment]
Hi.  Thanks for the feedback.

The first two things I'd look at here are:

1. Is it possible this is an issue with nulls?  It doesn't sound like it.  But if a null postcode was encoded as a blank string `""`, then the blocking rule would contain records where both postcodes were a blank string

2. Have a look at the SQL that Splink is generating to see if it looks right.  If you look at [this](https://github.com/moj-analytical-services/splink_demos/blob/master/quickstart_demo_deduplication.ipynb) you'll see the cell:

```
import logging

logging.basicConfig()  # Means logs will print in Jupyter Lab

# Set to DEBUG if you want splink to log the SQL statements it's executing under the hood
logging.getLogger("splink").setLevel(logging.INFO)
```

If you change that to:

````
import logging
logging.basicConfig() 
logging.getLogger("splink").setLevel(logging.DEBUG)
```

Then Splink will output the SQL commands that it's issuing to Spark in the log.

If you take a look at that output, or paste it in this issue, this might help us get to the bottom of it

Finally, if it's possible to post an example of your data so we can try to reproduce the issue, we can also look further.

**Comment by RobinL** [comment]
Another thing worth trying:

If you just block on
`l.postal_code = r.postal_code `

Does that give strange results?

(If this generates too many comparisons, you could try this TEST on a sample of the data)

**Comment by Rebecasarai** [comment]
Dear @RobinL ,

Thank you for your reply. 

> The first two things I'd look at here are:
> 
> Is it possible this is an issue with nulls? It doesn't sound like it. But if a null postcode was encoded as a blank string "", then the blocking rule would contain records where both postcodes were a blank string

I was checking on this in one small dataset in particular.
I summed up the NaN values (Nulls) and got that "There are 5,319 null postal codes from 41,299 total records in this dataset.":
![image](https://user-images.githubusercontent.com/25002245/140518897-e984db7b-21c7-4320-882d-72ca4be6b5e1.png)
So a bit more than 10% of the values are nulls.

In the case of empty strings as `''`, there are no occurrence of this. 0 rows have a postal code of `''`.
![image](https://user-images.githubusercontent.com/25002245/140519161-a57e030d-9e37-4004-b970-d8517660e48a.png)


> Have a look at the SQL that Splink is generating to see if it looks right. If you look at this you'll see the cell: 
>  ...
> Then Splink will output the SQL commands that it's issuing to Spark in the log.
> 
> If you take a look at that output, or paste it in this issue, this might help us get to the bottom of it

Yes I added the line and obtained the following debbuging messages (I also reduced the number of bloking rules to 3 for testing and added probability weights in hopes to improve the results):
```
DEBUG:splink.blocking:
select
l.unique_id as unique_id_l, r.unique_id as unique_id_r, l.n_b as n_b_l, ...,
'0' as match_key
from df as l
inner join df as r
on
l.postal_code = r.postal_code AND l.type_op= r.type_op AND l.type= r.type

where l.unique_id < r.unique_id

DEBUG:splink.gammas:
    select unique_id_l, unique_id_r, n_b_l, n_b_r, CASE WHEN (n_b_l IS NULL     OR     n_b_r IS null) THEN -1
 WHEN n_b_l = n_b_r THEN 1
 ELSE 0
 END  as gamma_n_b, n_d_l, n_d_r, CASE WHEN (n_d_l IS null OR n_d_r IS null) THEN -1
 WHEN n_d_l = n_d_r THEN 1
 ELSE 0
 END  as gamma_n_d, price_1_l, price_1_r, CASE WHEN (price_1_l IS NULL     OR     price_1_r IS NULL) THEN -1
 WHEN price_1_l = price_1_r THEN 2
 WHEN  (price_1_l <= (1.02 * price_1_r) and price_1_l >= (0.98 * price_1_r)) OR (price_1_r <= (1.02 * price_1_l) and price_1_r >= (0.98 * price_1_l)) THEN 1
 ELSE 0
 END  as gamma_price_1, price_2_l, price_2_r, CASE WHEN (price_2_l IS NULL     OR     price_2_r IS NULL) THEN -1
 WHEN price_2_l = price_2_r THEN 2
 WHEN  (price_2_l <= (1.02 * price_2_r) and price_2_l >= (0.98 * price_2_r)) OR (price_2_r <= (1.02 * price_2_l) and price_2_r >= (0.98 * price_2_l)) THEN 1
 ELSE 0
 END  as gamma_price_2, mun_l, mun_r, CASE WHEN (mun_l IS NULL     OR     mun_r IS NULL) THEN -1
 WHEN mun_l = mun_r THEN 2
 WHEN jaro_winkler_sim(mun_l, mun_r) > 0.95 THEN 2
 WHEN (jaro_winkler_sim(mun_l, mun_r) <= 0.95 AND jaro_winkler_sim(mun_l, mun_r) > 0.79) THEN 1
 ELSE 0
 END  as gamma_mun, anun_name_l, anun_name_r, type_anun_l, type_anun_r, CASE 
WHEN type_anun_l is null or type_anun_r is null then -1
 WHEN type_anun_l = type_anun_r AND type_anun_l != 'SPECIFIC_VALUE' AND anun_name_l = anun_name_r then 1
 ELSE 0
END  as gamma_anun_name_custom_col, n_sup_l, n_sup_r, CASE WHEN (n_sup_l IS NULL     OR     n_sup_r IS NULL) THEN -1
 WHEN n_sup_l = n_sup_r THEN 2
 WHEN  (n_sup_l <= (1.05 * n_sup_r) and n_sup_l >= (0.95 * n_sup_r)) OR (n_sup_r <= (1.05 * n_sup_l) and n_sup_r >= (0.95 * n_sup_l)) THEN 1
 ELSE 0
 END  as gamma_n_sup, id_item_l, id_item_r, cod_portalinmo_l, cod_portalinmo_r, fec_lote_l, fec_lote_r, match_key
    from df_comparison

DEBUG:splink.expectation_step:
    -- We use case statements for these lookups rather than joins for performance and simplicity
    select unique_id_l, unique_id_r, n_b_l, n_b_r, gamma_n_b, case 
WHEN gamma_n_b = -1 THEN cast(1 as double)
when gamma_n_b = 0 then cast(0.90000000000000002220446049250313081 as double)
when gamma_n_b = 1 then cast(0.10000000000000000555111512312578270 as double) 
end 
as prob_gamma_n_b_non_match, case 
WHEN gamma_n_b = -1 THEN cast(1 as double)
when gamma_n_b = 0 then cast(0.10000000000000000555111512312578270 as double)
when gamma_n_b = 1 then cast(0.90000000000000002220446049250313081 as double) 
end 
as prob_gamma_n_b_match, n_d_l, n_d_r, gamma_n_d, case 
WHEN gamma_n_d = -1 THEN cast(1 as double)
when gamma_n_d = 0 then cast(0.90000000000000002220446049250313081 as double)
when gamma_n_d = 1 then cast(0.10000000000000000555111512312578270 as double) 
end 
as prob_gamma_n_d_non_match, case 
WHEN gamma_n_d = -1 THEN cast(1 as double)
when gamma_n_d = 0 then cast(0.10000000000000000555111512312578270 as double)
when gamma_n_d = 1 then cast(0.90000000000000002220446049250313081 as double) 
end 
as prob_gamma_n_d_match, price_1_l, price_1_r, gamma_price_1, case 
WHEN gamma_price_1 = -1 THEN cast(1 as double)
when gamma_price_1 = 0 then cast(0.84999998637608031870627200987655669 as double)
when gamma_price_1 = 1 then cast(0.10000001021793991640151944011449814 as double)
when gamma_price_1 = 2 then cast(0.05000000340597976489220855000894517 as double) 
end 
as prob_gamma_price_1_non_match, case 
WHEN gamma_price_1 = -1 THEN cast(1 as double)
when gamma_price_1 = 0 then cast(0.01964285714285718409399805750581436 as double)
when gamma_price_1 = 1 then cast(0.18035714285714310456398834503488615 as double)
when gamma_price_1 = 2 then cast(0.79999999999999971134201359745929949 as double) 
end 
as prob_gamma_price_1_match, price_2_l, price_2_r, gamma_price_2, case 
WHEN gamma_price_2 = -1 THEN cast(1 as double)
when gamma_price_2 = 0 then cast(0.84999998637608031870627200987655669 as double)
when gamma_price_2 = 1 then cast(0.10000001021793991640151944011449814 as double)
when gamma_price_2 = 2 then cast(0.05000000340597976489220855000894517 as double) 
end 
as prob_gamma_price_2_non_match, case 
WHEN gamma_price_2 = -1 THEN cast(1 as double)
when gamma_price_2 = 0 then cast(0.01964285714285718409399805750581436 as double)
when gamma_price_2 = 1 then cast(0.18035714285714310456398834503488615 as double)
when gamma_price_2 = 2 then cast(0.79999999999999971134201359745929949 as double) 
end 
as prob_gamma_price_2_match, mun_l, mun_r, gamma_mun, case 
WHEN gamma_mun = -1 THEN cast(1 as double)
when gamma_mun = 0 then cast(0.84999998637608031870627200987655669 as double)
when gamma_mun = 1 then cast(0.10000001021793991640151944011449814 as double)
when gamma_mun = 2 then cast(0.05000000340597976489220855000894517 as double) 
end 
as prob_gamma_mun_non_match, case 
WHEN gamma_mun = -1 THEN cast(1 as double)
when gamma_mun = 0 then cast(0.05000000000000004440892098500626162 as double)
when gamma_mun = 1 then cast(0.25000000000000033306690738754696213 as double)
when gamma_mun = 2 then cast(0.69999999999999962252417162744677626 as double) 
end 
as prob_gamma_mun_match, anun_name_l, anun_name_r, type_anun_l, type_anun_r, gamma_anun_name_custom_col, case 
WHEN gamma_anun_name_custom_col = -1 THEN cast(1 as double)
when gamma_anun_name_custom_col = 0 then cast(0.90000000000000002220446049250313081 as double)
when gamma_anun_name_custom_col = 1 then cast(0.10000000000000000555111512312578270 as double) 
end 
as prob_gamma_anun_name_custom_col_non_match, case 
WHEN gamma_anun_name_custom_col = -1 THEN cast(1 as double)
when gamma_anun_name_custom_col = 0 then cast(0.10000000000000000555111512312578270 as double)
when gamma_anun_name_custom_col = 1 then cast(0.90000000000000002220446049250313081 as double) 
end 
as prob_gamma_anun_name_custom_col_match, n_sup_l, n_sup_r, gamma_n_sup, case 
WHEN gamma_n_sup = -1 THEN cast(1 as double)
when gamma_n_sup = 0 then cast(0.59821428571428580944768782501341775 as double)
when gamma_n_sup = 1 then cast(0.20000000000000039968028886505635455 as double)
when gamma_n_sup = 2 then cast(0.20178571428571381862759892555914121 as double) 
end 
as prob_gamma_n_sup_non_match, case 
WHEN gamma_n_sup = -1 THEN cast(1 as double)
when gamma_n_sup = 0 then cast(0.04285714285714284366157755812309915 as double)
when gamma_n_sup = 1 then cast(0.25000000000000000000000000000000000 as double)
when gamma_n_sup = 2 then cast(0.70714285714285718409399805750581436 as double) 
end 
as prob_gamma_n_sup_match, id_item_l, id_item_r, cod_portalinmo_l, cod_portalinmo_r, fec_lote_l, fec_lote_r
    from df_with_gamma

DEBUG:splink.expectation_step:
select (cast(0.3 as double) * prob_gamma_n_b_match * prob_gamma_n_d_match * prob_gamma_price_1_match * prob_gamma_price_2_match * prob_gamma_mun_match * prob_gamma_anun_name_custom_col_match * prob_gamma_n_sup_match)/(( cast(0.3 as double) * prob_gamma_n_b_match * prob_gamma_n_d_match * prob_gamma_price_1_match * prob_gamma_price_2_match * prob_gamma_mun_match * prob_gamma_anun_name_custom_col_match * prob_gamma_n_sup_match) + (cast(0.7 as double) * prob_gamma_n_b_non_match * prob_gamma_n_d_non_match * prob_gamma_price_1_non_match * prob_gamma_price_2_non_match * prob_gamma_mun_non_match * prob_gamma_anun_name_custom_col_non_match * prob_gamma_n_sup_non_match)) as match_probability, unique_id_l, unique_id_r, n_b_l, n_b_r, gamma_n_b, n_d_l, n_d_r, gamma_n_d, price_1_l, price_1_r, gamma_price_1, price_2_l, price_2_r, gamma_price_2, mun_l, mun_r, gamma_mun, anun_name_l, anun_name_r, type_anun_l, type_anun_r, gamma_anun_name_custom_col, n_sup_l, n_sup_r, gamma_n_sup, id_item_l, id_item_r, cod_portalinmo_l, cod_portalinmo_r, fec_lote_l, fec_lote_r
from df_with_gamma_probs

DEBUG:splink.maximisation_step:
select gamma_n_b, gamma_n_d, gamma_price_1, gamma_price_2, gamma_mun, gamma_anun_name_custom_col, gamma_n_sup, sum(match_probability) as expected_num_matches, sum(1- match_probability) as expected_num_non_matches, count(*) as num_rows
from df_e
group by gamma_n_b, gamma_n_d, gamma_price_1, gamma_price_2, gamma_mun, gamma_anun_name_custom_col, gamma_n_sup

DEBUG:splink.maximisation_step:
select cast(sum(expected_num_matches)/sum(num_rows) as float) as new_lambda
from df_intermediate

DEBUG:splink.maximisation_step:
        select
        gamma_n_b as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_n_b != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_n_b != -1) as float) as new_probability_non_match,
        'n_b' as column_name
        from df_intermediate
        where gamma_n_b != -1
        group by gamma_n_b

union all

        select
        gamma_n_d as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_n_d != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_n_d != -1) as float) as new_probability_non_match,
        'n_d' as column_name
        from df_intermediate
        where gamma_n_d != -1
        group by gamma_n_d

union all

        select
        gamma_price_1 as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_price_1 != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_price_1 != -1) as float) as new_probability_non_match,
        'price_1' as column_name
        from df_intermediate
        where gamma_price_1 != -1
        group by gamma_price_1

union all

        select
        gamma_price_2 as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_price_2 != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_price_2 != -1) as float) as new_probability_non_match,
        'price_2' as column_name
        from df_intermediate
        where gamma_price_2 != -1
        group by gamma_price_2

union all

        select
        gamma_mun as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_mun != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_mun != -1) as float) as new_probability_non_match,
        'mun' as column_name
        from df_intermediate
        where gamma_mun != -1
        group by gamma_mun

union all

        select
        gamma_anun_name_custom_col as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_anun_name_custom_col != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_anun_name_custom_col != -1) as float) as new_probability_non_match,
        'anun_name_custom_col' as column_name
        from df_intermediate
        where gamma_anun_name_custom_col != -1
        group by gamma_anun_name_custom_col

union all

        select
        gamma_n_sup as gamma_value,
        cast(sum(expected_num_matches)/(select sum(expected_num_matches) from df_intermediate where gamma_n_sup != -1) as float) as new_probability_match,
        cast(sum(expected_num_non_matches)/(select sum(expected_num_non_matches) from df_intermediate where gamma_n_sup != -1) as float) as new_probability_non_match,
        'n_sup' as column_name
        from df_intermediate
        where gamma_n_sup != -1
        group by gamma_n_sup

INFO:splink.iterate:Iteration 0 complete
```

This is for the first iteration. 

I anonymized the column names for sharing purposes.

**Comment by Rebecasarai** [comment]
Dear @RobinL , to continue:

> Finally, if it's possible to post an example of your data (just a few rows, which you can make up, but exhibit the issue) so we can try to reproduce the issue, we can also look further.

Yes, I managed to anonymize a sample of 10% of a dataset of around 50k. In other words, I sampled 5k rows from this dataset, which can be found here: [Anonymized dataset for deduplication in Kaggle](https://www.kaggle.com/rebecahere/anonymized-dataset )

The column names have been changed and most of the values have been replaced, following the original probability distribution of that 5k sample.

**Comment by Rebecasarai** [comment]
> Another thing worth trying:
> 
> If you just block on `l.postal_code = r.postal_code `
> 
> Does that give strange results?
> 
> (If this generates too many comparisons, you could try this TEST on a sample of the data)

And finally, yes, I tried this, and in the results I still get different postal codes in one group:

![image](https://user-images.githubusercontent.com/25002245/140526906-c739c4ef-b153-4a12-b461-77c9e0d3b5a1.png)

That negative number represents a postal code id

**Comment by RobinL** [comment]
Thanks.   The first statement is the one that generates record comparisons - i.e. this is the statement that should impose the constraint that Splink should generate only records comparisons which have a matching postcode:
```
DEBUG:splink.blocking:
select
l.unique_id as unique_id_l, r.unique_id as unique_id_r, l.n_b as n_b_l, ...,
'0' as match_key
from df as l
inner join df as r
on
l.postal_code = r.postal_code AND l.type_op= r.type_op AND l.type= r.type
where l.unique_id < r.unique_id
```

Splink then uses the result of this statement for all subsequent steps.  i.e. this should be the source of the problem.


If you run just that statement in Spark (using `spark.sql()`), do you still see the problem. i.e. do you still see that :
> postal_code isn't the same in all records segmented into an estimated matching group 

If so, it could be something to do with data types.  Whenever we use Splink we're blocking on string fields, so we've never really tried other data types.  In the test data you helpfully posted, postcode contains values like `3.800779753845739e+16`.  I wonder if there could be anything to do with numeric precision going on here...

**Comment by Rebecasarai** [comment]
Dear @RobinL ,

Thank you for your reply.

I checked on the results performing the same SQL query with `spark.sql()`.

In this case, the postal_codes are equal. Meaning, the comparisons are performed correctly.

![image](https://user-images.githubusercontent.com/25002245/140663742-bf4144b6-8bf4-45ab-972b-09ffad18e547.png)

![image](https://user-images.githubusercontent.com/25002245/140663758-41364be8-50e4-45bf-8426-fd2440f0615d.png)

![image](https://user-images.githubusercontent.com/25002245/140663801-51b91927-36d6-4694-bb5c-dcfcee0b66fb.png)

When pasting the SQL sentence to `spark.sql()`, I added the r.postal_code and l.postal_code in the select line so I could directly access it when checking if they are equal or not.

In the original SQL, this isnt the case. The postal codes are only referenced in the JOIN rule. 

```SQL
inner join df as r
on
l.region_id_cp = r.region_id_cp AND ...
```

**Comment by RobinL** [comment]
Really difficult to figure out what's going wrong here - sorry.  Are you able to provide an executable example with a few rows of data that reproduces the problem?

**Comment by Rebecasarai** [comment]
Hi,

When debugging in detail, I found that that the first results returned bu Splink follow the blocking_rules and it's when the graphframes are used to compute the estimated groups when the records are mixed up, and different postal codes are joined together in the same group.


When checking if postal codes and another blocking column are equal from each side in `df_e`:
![image](https://user-images.githubusercontent.com/25002245/140954984-b52c1e4d-b810-414e-987f-48c1f1ee8fbf.png)
The postal codes are the same in each comparison and resulting table rows.

So far so good. Then when the nodes and edges are computed to put the duplicates into groups it's when this weird data appears.
These are the SQLs to compute nodes and edges:
![image](https://user-images.githubusercontent.com/25002245/140955996-01e39374-f5df-4687-9d25-1bb4e28c4c41.png)
![image](https://user-images.githubusercontent.com/25002245/140955923-1f926c4c-45f9-4c53-90e9-7abb268dd98e.png)

And the SQL to compute results:
![image](https://user-images.githubusercontent.com/25002245/140956189-caf01d29-2080-41aa-98f3-5f750d7fb9fa.png)

Lastly, in the final resulting dataframe the postal codes are different among the estimated groups
![image](https://user-images.githubusercontent.com/25002245/140957020-f1d078fa-cac8-43d4-b7ca-45b8bd310f2b.png)

So in this case, it's a matter of settings these graphframes correcly.

When I do these calculations locally in a dev Docker enviroment, they work and all postal codes are equal (Splink does fewer interations).

I'm not completly sure of why these are failing in the pre-production enviroment yet.

**Comment by RobinL** [comment]
Nice 🕵️‍♀️.    I don't suppose it's it possible that your unique ids are not unique? 

Technically graphframes is not part of the Splink codebase (at least not in version below 2.0), so I'm not sure under what circumstances it would break like this.  

If:
- All edges going in have matching postcode
- The unique id field is truly unique

Then the resultant clusters should be guaranteed to have a single postcode.

That said, we've never experienced any issues with it and have used it quite extensively.

As of Splink 2.0, there is a new `splink.cluster.clusters_at_thresholds` function [here](https://github.com/moj-analytical-services/splink/blob/6cec2cc5f894b4f7ca8916717feefc0bdbef90b2/splink/cluster.py#L132) that you could try.  

Interesting you're doing:
`# deduplicate the component assignments`
Is there a reason for that?

**Comment by Rebecasarai** [comment]
Dear  @RobinL ,

Thank you for your reply,

I add a unique_id th following way:

```python
df = df.withColumn(
        "unique_id",
        F.monotonically_increasing_id()
    )
```

This way it's a unique 64-bit integer id. The generated ID is guaranteed to be monotonically increasing and unique, but not consecutive. 

So the minimum id number is 0 and the maximum over 1,709,396,984,000.

I inspected more in detail and used the `clusters_at_thresholds()` function. Great update that makes things easier. Right now this function isn't working in pre-prod either. 

The mixed data come right in this point, after performing the graphframe calculations when postal codes turn out different in the clustered results.

```python
# Cluster duplicates in groups
thresholds = {"estimated_group": 0.9}
results_df = clusters_at_thresholds(df, df_e, thresholds, linker.model, spark)
```

The debugging message of `clusters_at_thresholds()` are:

```output
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Start connected components with run ID XXXX.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Using XX/SPARK_CHECKPOINT_FOLDER/5c8669bc-96a7-4dd8-985d-63e7520ad144/connected-components-98a29a32 for checkpointing with interval 2.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Preparing the graph for connected component computation ...
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Found 1 edges after preparation.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Sum of assigned components in iteration 1: 1.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Sum of assigned components in iteration 2: 1.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Connected components converged in 2 iterations.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Join and return component assignments with original vertex IDs.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Start connected components with run ID 756518d8.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Using XX/SPARK_CHECKPOINT_FOLDER/5c8669bc-96a7-4dd8-985d-63e7520ad144/connected-components-756518d8 for checkpointing with interval 2.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Preparing the graph for connected component computation ...
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Found 62589 edges after preparation.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 1: 8283480089321191.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 2: 4025123094281063.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 3: 2278978369136813.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 4: 2105504638752383.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 5: 2104946292921868.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 6: 2104946292921868.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Connected components converged in 6 iterations.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Join and return component assignments with original vertex IDs.
```


I'm going to try change the way the ids are added to the columns to have sequential ids and see that it might be because of this: the large unique_id numbers.

**Comment by Rebecasarai** [comment]
Althought now that I see the output text of `clusters_at_thresholds()`, it seems like it's doing it twice. 

There are two messages with "CC":
`[CC 98a29a32]` and `[CC 756518d8]`.

```
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Found 1 edges after preparation.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 98a29a32] Sum of assigned components in iteration 1: 1.
...
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Found 62589 edges after preparation.
 INFO org.graphframes.lib.ConnectedComponents$: [CC 756518d8] Sum of assigned components in iteration 1: 8283480089321191.
```

Is this normal?

**Comment by RobinL** [comment]
I think there's a possibility that `F.monotonically_increasing_id()` is the source of the problem. We've certainly had problems with 'non-deterministicness' of this function before.

One thing you could try is:
Step 1:  assign an id using `monotonically_increasing_id` _and then save the data out to a parquet file_.  (If memory serves, it _does_ produce a unique id, but if you're using it with an iterative algorithm it can 'change'.  )
Step 2:  Load the parquet file in, (double check the ID is actually unique - I think it will be), and run everything from that point

**Comment by mamonu** [comment]
IMO @RobinL is right to suspect the `F.monotonically_increasing_id()` function. This is unfortunately a known issue
tripping up people in the Spark ecosystem

Someone has even written a blog post about this. 
[spark-surprises-for-the-uninitiated](https://godatadriven.com/blog/spark-surprises-for-the-uninitiated/)

**Comment by Rebecasarai** [comment]
Dear @RobinL 


> I think there's a possibility that `F.monotonically_increasing_id()` is the source of the problem. We've certainly had problems with 'non-deterministicness' of this function before.
> 
> One thing you could try is: Step 1: assign an id using `monotonically_increasing_id` _and then save the data out to a parquet file_. (If memory serves, it _does_ produce a unique id, but if you're using it with an iterative algorithm/long lineage in Spark it can 'change'. ) Step 2: Load the parquet file in, (double check the ID is actually unique - I think it will be), and run everything from that point

I tried this and found out that the data indeed "changed". The saved dataframe as a parquet file right after adding the `F.monotonically_increasing_id()` was different than the one just a couple of lines after in the code.

I passed the parqeut file to the `clusters_at_thresholds()` function and it worked! 🎉  The blocking rules work and all the resulting groups have the same postal_code. 



> IMO @RobinL is right to suspect the `F.monotonically_increasing_id()` function. This is unfortunately a known issue tripping up people in the Spark ecosystem
> 
> Someone has even written a blog post about this. [spark-surprises-for-the-uninitiated](https://godatadriven.com/blog/spark-surprises-for-the-uninitiated/)
> 
> In addition to make things more complicated...in the graphframes package this conversation about a relevant issue has taken place : [graphframes/graphframes#159](https://github.com/graphframes/graphframes/issues/159)
> 
> the outcome of all this is: only by explicitly caching and/or saving at the right time (eg once _after_ running the `monotoniclly_inc_id` function and perhaps once more _before_ running cc we can be sure that the results will be correct.

Thank you for this information @mamonu , the cause comes from `F.monotonically_increasing_id()` indeed. And as you said saving it after adding those id works. 😃 

Now I'm checking the results and seeing a few clustered groups that have a large number of false duplicates (All respecting the blocking rules) and I wonder if it's because I'm not caching before running cc or because of the comparison columns and the m and u probabilities.

In the other hand, the groups with fewer number of duplicates (2 to 6 records per group) are, so far I could check, all correct. ✔️ 

I wanted to thank you for the help! @mamonu @RobinL 

Kind regards,
Rebeca

**Comment by RobinL** [comment]
Pleasure to help.  We should probably add something to the docs about generating a unique_id in Spark, as I fell into this trap a while ago too - it's very counterintuitive so a difficult bug to spot.

Thanks for providing easy to understand and clear descriptions of what you were doing and what was going wrong.
