### ISSUE TITLE
link only slower in splink > 1.0 (following df_or_dfs) relative to 0.x releases

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#249]
I updated Splink to 1.0, was 0.4.2 before, and now the Splink match takes 3 times longer. 

I just changed the required typo which are,
- changing the parameter df = df, to df_or_dfs=[]
- adding a source_column lit with the source name 

The settings and the data is the same.
I have no idea why that happen and I don't know where to look for to tackle the issue.

_Originally posted by @Khallil in https://github.com/moj-analytical-services/splink/discussions/218_

**Comment by RobinL** [comment]
I've just had a look at the code and I think I can see why this might be the case.  [Before](https://github.com/moj-analytical-services/splink/blob/d354b38b3a7efedb446275d5affcdeed76f56071/splink/blocking.py#L141), [after](https://github.com/moj-analytical-services/splink/blob/master/splink/blocking.py#L99)

I'm going to convert this into an issue and we can think about whether we can revert back to the previous approach.  Unfortunately it's not trivial because in 1.0, `link_only` supports >2 datasets, and the performance gain I think happens specifically for the two dataset case (which I admit is most common).

**Comment by JoshuaBWT** [comment]
Hi @RobinL, would it be possible to get a comment on my question above?

Thanks & best regards,
Joshua

**Comment by RobinL** [comment]
Ah - my bad,  updated the discussion but not the issue, see here:
https://github.com/moj-analytical-services/splink/discussions/218

In summary:
- This will not land in a `2.x` Splink release
- It already exists in the forthcoming Splink version 3
- You can try version 3 by installing a [pre-release](https://pypi.org/project/splink/#history), or in the new demos [here](https://github.com/moj-analytical-services/splink_demos/tree/splink3_demos).

**Comment by JoshuaBWT** [comment]
That sounds great. I will give it a go and eventually share some feedback

0.x is fine and all but staying close to whatever is the latest release is what we aim for. All the benchmarking & advanced parsing features look really good as well

**Comment by RobinL** [comment]
Closed by #278.  Splink 3 contains logic that dels specifically with the link only two dataset case.  This essentially restores the performance you were seeing in 0.4.2
