### ISSUE TITLE
[Term frequency adjustments ] Would like the ability to include pre-computed term frequency adjustments (e.g. from the general population)

### ISSUE THREAD

**Issue by pierpaolocreanza** [moj-analytical-services/splink#2502]
### Is your proposal related to a problem?
(1) Splink only allows to include term frequency adjustments based on a column that is actively used in the comparison level;
(2) Splink wants to compute the tf adjustments itself, so one cannot feed it pre-computed term frequencies penalties

This is limited in a few real world scenarios:
(a) one wants to do term frequency adjustments based on a column that should now itself be included in a comparison (i.e. maybe I want to define TF adjustments based on a stripped or more aggressively cleaned version of a full name, but still want to use a more granular version of comparison)
(b) most relevant for me, one may want to use term frequencies in a different (larger) population to inform splink matches! 
 - A dataset may be highly selected, but one may want to use tf adjustments baed on the whole population / census data.
 - Or, a dataset may have repeated observations for the same name that derive from repeated output. So they are "frequent" but not because the name itself is frequent.
A concrete example is a dataset of novelists and their novels. One Arthur Conan Doyle may appear many times because he's written many books, but that doesn't mean that Arthur Conan Doyle is a common name that should suffer a large penalty. Wheres "William Smith" is probably frequent because the name is common.

### Describe the solution you'd like
The ability to add custom, pre-computed term frequencies penalties (T_x in the notation here: https://moj-analytical-services.github.io/splink/topic_guides/comparisons/term-frequency.html#toy-example)

### Describe alternatives you've considered
I've tried to override the relevant Splunk internals, but it gets really messy and it's hard to backward induce the whole pipeline.

**Comment by ADBond** [comment]
Unless I am misreading things I think that [Linker.table_management.register_term_frequency_lookup](https://moj-analytical-services.github.io/splink/api_docs/table_management.html#splink.internals.linker_components.table_management.LinkerTableManagement.register_term_frequency_lookup) should do what you are after. You can supply it with the name of a table in your backend with values and frequencies, which will then be used when it comes to the linkage.

Perhaps we could signpost this function a bit better in the docs

**Comment by pierpaolocreanza** [comment]
Hi! Yes, that is precisely what I wanted--thanks very much! Apologies for not spotting it on my own. But yes, it would be helpful it were referenced in the term frequencies User Guide.
