### ISSUE TITLE
ModuleNotFoundError: No Module named 'splink.duckdb'

### ISSUE THREAD

**Issue by jpasner** [moj-analytical-services/splink#2536]
### What happens?

Hello Everyone and thank you for taking a look at my problem!

I'm developing a project at Georgetown University trying to use Splink and can't seem to get your package up and running. In my python code I call `from splink.duckdb.Linker import DuckDBLinker` but get the error `ModuleNotFoundError: No module named 'splink.duckdb` inside of a python 3.9.6 venv I created with the splink package installed via pip. I've also tried the same thing using a python 3.13.0 venv.

![Image](https://github.com/user-attachments/assets/2aadd99b-894c-4b3b-a62e-c0cc3059ef18)

### To Reproduce

To demonstrate this issue I re-installed the package using a Python 3.9.6 venv and got the follow error when trying to import splink.duckdb

![Image](https://github.com/user-attachments/assets/25fad8ae-b784-475a-b732-6eb5437a14e7)

I also tried to do this on my personal laptop and had the same issue. This maybe something stupid I'm doing on my end but I can't seem to get this to work so I figured I'd reach out. 

### OS:

MacOS Sonoma 14.6

### Splink version:

4.0.5

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] I agree

**Comment by jpasner** [comment]
Looks like I was following a tutorial that may have led me down the wrong path. Apologies for the confusion. Closing for now.

**Comment by aymonwuolanne** [comment]
This error is because the syntax `from splink.duckdb.linker import DuckDBLinker` is for Splink 3.x.y, but you've got Splink 4 installed. You could either install the older version of Splink e.g. `pip install splink==3.9`, or update your scripts to use the new syntax (see the documentation pages for how it works in version 4). 

Happy splinking

**Comment by jpasner** [comment]
I see, thank you for this clarification, I wouldn't have noticed this otherwise!
