### ISSUE TITLE
AnalysisException: Recursive view `df` detected (cycle: `df` -> `df`)

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#258]
https://community.databricks.com/s/question/0D53f00001Qugr7CAB/upgrading-from-spark-24-to-32-recursive-view-errors-when-using

This appears to be a bug introduced in Spark `3.2.0`.

For the moment we recommend using a different version of Spark.  We're not intending to fix this in Splink unless the Spark maintainers confirm this is a deliberate change (seems unlikely because it breaks backward compatibility)

**Comment by RobinL** [comment]
Issue raised against main Spark project here: https://issues.apache.org/jira/browse/SPARK-37690

**Comment by RobinL** [comment]
Added a comment against the issue above.  Copying here for infp:

Someone [here](https://community.databricks.com/s/question/0D53f00001Qugr7CAB/upgrading-from-spark-24-to-32-recursive-view-errors-when-using) has suggested this is an intentional breaking change introduced in Spark 3.1:

From [Migration Guide: SQL, Datasets and DataFrame - Spark 3.1.1 Documentation (apache.org)](https://spark.apache.org/docs/3.1.1/sql-migration-guide.html)

> In Spark 3.1, the temporary view will have same behaviors with the permanent view, i.e. capture and store runtime SQL configs, SQL text, catalog and namespace. The capatured view properties will be applied during the parsing and analysis phases of the view resolution. To restore the behavior before Spark 3.1, you can set spark.sql.legacy.storeAnalyzedPlanForView to true.

 

Grateful if someone could clarify.  Worth noting that the example code works in Spark 3.1.2, just not 3.2.0.  It's not obvious to me the above quote implies `createOrReplaceTempView` would fail in the example code posted in the issue.

**Comment by ericmanning** [comment]
FYI -- changing all of the references to `df` across `term_frequencies.py` to something like `df_no_tf` fully resolves this issue in Spark 3.2.

**Comment by Kri-Sha** [comment]
> Added a comment against the issue above. Copying here for info:
> 
> Someone [here](https://community.databricks.com/s/question/0D53f00001Qugr7CAB/upgrading-from-spark-24-to-32-recursive-view-errors-when-using) has suggested this is an intentional breaking change introduced in Spark 3.1:
> 
> From [Migration Guide: SQL, Datasets and DataFrame - Spark 3.1.1 Documentation (apache.org)](https://spark.apache.org/docs/3.1.1/sql-migration-guide.html)
> 
> > In Spark 3.1, the temporary view will have same behaviors with the permanent view, i.e. capture and store runtime SQL configs, SQL text, catalog and namespace. The capatured view properties will be applied during the parsing and analysis phases of the view resolution. To restore the behavior before Spark 3.1, you can set spark.sql.legacy.storeAnalyzedPlanForView to true.

Unfortunately, setting spark.sql.legacy.storeAnalyzedPlanForView to true did NOT resolve the issue. I am still seeing 'AnalysisException: Recursive view `Daily_ControlResults_DF` detected'
