### ISSUE TITLE
Possibility of using DuckDB as alternative backend

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#259]
Had a v. useful chat with the DuckDB team on their [Discord channel](https://discord.com/invite/tcvwpjfnZx).  Cross posted here so we don't lose it.  [Link to message](https://discord.com/channels/909674491309850675/921073327009853451/921787010451144704)

Basic conclusion is that at some point I'd really like to try DuckDB to see how big data it could handle for record linkage.

RobinL — Today at 3:32 PM
Hello!  I'm a big fan of DuckDB and Arrow. Despite years of experience in pandas, I find I use it much less now DuckDB exists .   I wonder if I could ask one point of clarification about the links between DuckDB and Arrow.  Am I right in saying that DuckDB does not use Apache Arrow's C++ compute layer?  The C++ engine is mentioned in the 'DuckDB quacks Arrow' blog post (https://arrow.apache.org/blog/2021/12/03/arrow-duckdb/), but then the blog post suggests that DuckDB computation is done 'while taking advantage of DuckDB’s parallel vectorized execution engine'. Have I got this right?   If so, I wondered what the rationale was for not using Arrow's C++ engine, or if there were plans to use it in future when it's more complete.  It's not a blocker for me using DuckDB - I just struggle sometimes to understand Arrow and its relation to other projects. Apologies if this is documented somewhere obvious that I've missed. 

Hannes — Today at 3:38 PM
Yes you are right I saying that DuckDB is not using arrows compute engine
And it’s unlikely that will change

__Alex__ — Today at 3:39 PM
Great question! DuckDB doesn't use the Arrow C++ engine for a few reasons, but the main one is that I believe DuckDB was built first! As for switching to it, I think we haven't yet seen enough reasons to switch. DuckDB is already really fast!
At some point, Arrow may be a good starting point for new DB engines, but they are still a little ways away. Plus DuckDB is innovating really fast, so I don't think Arrow is even catching up at the moment (although they are doing great work!)

RobinL — Today at 3:51 PM
Thanks.  That's really useful.  I figured it was partly a timing issue since DuckDB's compute features seemed to be ahead of Arrow's .  Could I ask one more follow up (sorry!).  The blog post also mentions 'analysis of larger than memory datasets'.  Is this being enabled by predicate/filter pushdown, or is it more sophisticated?  I know that Arrow have plans to allow 'chunking' of analytical workloads in a way similar to Apache Spark. (e.g. to compute an aggregate on a massive table, you can do partial aggregates on (say) 1% chunks of the full data, and the combine partial aggregates, so you only ever need 1% + a bit in memory at once).

[By way of background, I'm the author of a FOSS probabilistic record linkage package which uses Spark SQL as a backend.  Users often struggle installing Spark, and I keep wondering whether I should offer DuckDB as an alternative compute backend, which would be simpler for users with relative small data.]

__Alex__ — Today at 3:53 PM
Another awesome question! No apologies needed - that's what this channel is for!
DuckDB does do predicate pushdown, but that's just a part of working with larger than memory. DuckDB also streams batches of rows/vectors through its computation. That allows it to read data into memory, use it for whatever purpose (scan it to look for things that match a join criteria, or compute an aggregate), then release that memory again and grab a new batch
So yes, it does streaming computation! The part I really like is that it's transparent to the user - no need to define a partitioning scheme.
That's because DuckDB uses threads so the memory is shared across all of your processing cores

hawkfish — Today at 4:00 PM
It can also spool data to disk for sorting. We are working on using this capability in other operations e.g., I’m looking at inequality joins, where one side is sorted and read into memory as needed.

**Comment by drorspei** [comment]
Hi hi

I wanted to use splink with duckdb so I forked and made linking work (didn't try dedupe or anything else).

It's pretty fast, it was worth it.

https://github.com/drorspei/splink

There's a new `DuckSplink` class, that takes duckdb relations instead of spark dataframes, and a duckdb connection instead of a spark session.

**Comment by RobinL** [comment]
Amazing!  I will take a look at this properly.  I'm currently working on splink v3, currently in a separate repo, which will take this one step further by abstracting over the SQL backend so the user can choose the whatever SQL execution engine they want.  I'm read your implementation with interest because I'm not a duckdb expert, so very interested in the best way to use it for these calculations

**Comment by RobinL** [comment]
Note that development of a DuckDB linker is progressing nicely on the [splink3 branch](https://github.com/moj-analytical-services/splink/tree/splink3).  We have a working version if people want to give it a go in very early alpha

**Comment by RobinL** [comment]
Closed by #278 .  DuckDB is one of the backend options in Splink3
