### ISSUE TITLE
Cannot find graphframes jar when running code on databricks

### ISSUE THREAD

**Issue by aliwicks** [moj-analytical-services/splink#266]
Hi,

I have a persistent issue when testing running splink demo code from within the DataBricks notebook environment. 

Everything works until the final line of code that executes 'external clusters_at_thresholds()' function. It fails saying that spark cannot find the external graphframes jar even though I have successfully installed it to the cluster (I tried it both installing manually to cluster and using maven package).
<img width="1073" alt="Screen Shot 2022-02-01 at 12 10 43" src="https://user-images.githubusercontent.com/42868426/151966194-3c348ad7-5d63-46fd-b31d-06eaf725b4df.png">

I have tried following all the troubleshooting steps suggested in the output including installing latest version of graphframes jar (graphframes_0_8_1_spark3_0_s_2_12) that is compatible with spark 3.1 (which is the spark version I'm using within DataBricks). The spark context I use is when trying to point to my manually installed graphframes JAR is:
<img width="1125" alt="Screen Shot 2022-02-01 at 12 04 28" src="https://user-images.githubusercontent.com/42868426/151965462-97574890-b6a2-4cb6-bb9e-3656e3da3960.png">

I mounted the graphframes JAR in the Datbricks File System (dbfs) at:
<img width="811" alt="Screen Shot 2022-02-01 at 12 28 23" src="https://user-images.githubusercontent.com/42868426/151968324-5ab72731-283b-47dc-a7df-c8a90cab009c.png">

Have also tried following suggestions in-line with #257 which was a jar/databricks related issue, but no luck.

Any help/suggestions would be much appreciated!

Thanks!

**Comment by RobinL** [comment]
Thanks for the report.   The code that's creating the error is (from [here](https://github.com/moj-analytical-services/splink/blob/a4b836d8d6848da2223f3cb1199748bdf8bf589a/splink/cluster.py#L68)) is

```
    all_config = spark.sparkContext.getConf().getAll()

    config_keys = [
        "spark.submit.pyFiles",
        "spark.repl.local.jars",
        "spark.jars.packages",
        "spark.jars",
        "spark.app.initial.file.urls",
        "spark.files",
        "spark.app.initial.jar.urls",
    ]

    graphframe_jar_registered = False
    for (key, value) in all_config:
        if key in config_keys:
            if "graphframes" in value:
                graphframe_jar_registered = True
```

Reading this code, I would expect `"graphframes"` to be found in the `spark.jars` config option that you've set but this appears not to be the case.  What is the value in the `spark.jars` key of `all_config = spark.sparkContext.getConf().getAll()`?

**Comment by aliwicks** [comment]
Thanks for the swift reply!

Actually I can't see any of the config_keys you listed in all_config:
<img width="471" alt="Screen Shot 2022-02-01 at 14 07 45" src="https://user-images.githubusercontent.com/42868426/151983417-d7a976b6-ab6e-49bd-88b9-2a2f3c32d07c.png">

The first few lines of all_config look like:

<img width="684" alt="Screen Shot 2022-02-01 at 14 16 24" src="https://user-images.githubusercontent.com/42868426/151984829-3edf38ed-2633-4128-9cfc-f967121f3f0a.png">

Is there some obvious step I have missed?

**Comment by RobinL** [comment]
Interesting.  If you iterate over all the keys in your `all_config`, is there one which contains the path of the `graphframes` jar?  If so, we might just need to add a 'databricks specific' key to the `config_keys` list.

i.e. i'm thinking about a key maybe like `spark.databricks.jarlocation` or something like that

**Comment by aliwicks** [comment]
No there aren't any keys that reference graphframes or its path. So if I run:
<img width="1090" alt="Screen Shot 2022-02-01 at 17 22 20" src="https://user-images.githubusercontent.com/42868426/152018260-2b8e4409-97e3-4f4b-acd7-f67a38b4fdb1.png">
I get no reference to the graphframes jar in the config, neither databricks specific or normal. 

I can explicitly add it to the config as you can see via the top line of the output: 
<img width="1090" alt="Screen Shot 2022-02-01 at 17 12 03" src="https://user-images.githubusercontent.com/42868426/152016691-704e593d-47cc-4001-84f3-b02ff0730189.png">

but then if I create a new spark session on the back of this (intended for use with splink) it doesn't retain my graphframes related config as can be seen in below output:
<img width="1079" alt="Screen Shot 2022-02-01 at 18 13 34" src="https://user-images.githubusercontent.com/42868426/152026651-a61a134a-c888-4892-b931-1315c26efd14.png">

Appreciate this might be a difficult one for you to help debug, without Databricks access.

**Comment by RobinL** [comment]
Thanks.  Do you think graphframes itself is working OK, outside of Splink?  

For instance, does this work:  (from [here](https://graphframes.github.io/graphframes/docs/_site/user-guide.html))
```
from graphframes.examples import Graphs
g = Graphs(sqlContext).friends()  # Get example graph

result = g.connectedComponents()
result.select("id", "component").orderBy("component").show()
```

**Comment by aliwicks** [comment]
Yeah, I did test graphframes before and it seems to work fine on its own.

Clearing the kernel and just running the above code with the extra setCheckpointDirectory() line added and it seems to work fine:
<img width="602" alt="Screen Shot 2022-02-02 at 09 48 21" src="https://user-images.githubusercontent.com/42868426/152130976-88ee5e99-4af9-443d-82c6-47a80ea27689.png">

(I have tried added this setCheckpointDirectory() line when configuring for use with splink code but no luck and get the same missing graphframes error message)

**Comment by RobinL** [comment]
Thanks.  So I think we're just shooting ourself in the foot here.  Splink is attempting to be helpful and checking whether graphframes in installed so it can give the user a sensible error message.  

But the check isn't working in the databricks case, meaning Splink errors out for you, when in fact, if it just continued to run, everything would work fine.

As a very quick and dirty fix, you can comment out lines 86 and 87 here and i think it probably should work:
https://github.com/moj-analytical-services/splink/blob/eb72e8a344850bae68c2cacebb5f1658d2651e9d/splink/cluster.py#L87

It'd be good if we could find a way of making this check work within databricks, though.  

Ideally I want to avoid the 'nuclear' option of just trying to run a piece of graphframes example code, and erroring out if it doesn't work, since this would be bad for performance.

**Comment by mamonu** [comment]
@RobinL I think if we use 
[[pyspark.SparkContext.getCheckpointDir]](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.SparkContext.getCheckpointDir.html)

we can check 
a) whether its a databricks installation and then 
b) not raise an exception

I will try to put a fix PR for this...

**Comment by aliwicks** [comment]
Hi guys,

After a bit of digging and using your suggestions to help lead me, I have managed to fix the problem.

So you can set the spark configuration at the cluster level by following the steps in the "Spark Configuration" section of this link: [https://docs.databricks.com/clusters/configure.html#spark-configuration](url). Then if you also add this line to the notebook at set up:

spark.sparkContext.setCheckpointDir("dbfs:/graphframes_tempdir/")

the clusterAtThresholds() function runs succesffully.

Not entirely clear why setting the config via the notebook [https://kb.databricks.com/data/get-and-set-spark-config.html](url) isn't working for me with splink but I don't think this is the recommended way of changing config settings in databricks anyway. 

Perhaps something to do with the fact that a default spark session is automatically created for you when you spin up a databricks cluster and the splink graphframes check is not checking what we think it is in the databricks case? 

Screenshots of code run and it working:
<img width="609" alt="Screen Shot 2022-02-03 at 09 40 17" src="https://user-images.githubusercontent.com/42868426/152317842-7b0d463f-ab5b-40f4-b9c1-d7ea222ef0a5.png">


<img width="1094" alt="Screen Shot 2022-02-03 at 09 42 23" src="https://user-images.githubusercontent.com/42868426/152318025-a87ace20-71f1-46c6-a7ad-1c3a5746eb2f.png">

I'm new to databricks (and spark) hence why it took prob a bit more time than a databricks whizz to work out that I needed to try configuring at the cluster level. Thanks for your help and patience :)

If there is anything else you want me to quickly test regarding this issue let me know and happy to help!

Cheers!

**Comment by mamonu** [comment]
@aliwicks can you try running

`spark._jsc.sc().getCheckpointDir().get()`

after defining the checkpoint? If it comes with `dbfs:/blahblah` like I expect ... 
then this will be easy to fix without messing with something else at the same time

**Comment by aliwicks** [comment]
Yep its as you expected:

<img width="638" alt="Screen Shot 2022-02-03 at 12 16 34" src="https://user-images.githubusercontent.com/42868426/152341173-4975abec-1d59-4b63-bd20-af6e0772809c.png">

**Comment by AdamFinny** [comment]
I use databricks and I had exactly the same issue, commenting out the check worked for me. And to confirm, I get dbfs:/... as well

**Comment by mamonu** [comment]
issued PR #272  for a quick fix

**Comment by RobinL** [comment]
@aliwicks  just to say thanks so much for testing things for us and providing the detail

**Comment by mamonu** [comment]
new release 2.1.5 on PYPI that hopefully fixes this issue 😺  👌 
please upgrade with
`pip install splink==2.1.5`
and test if possible on the dbricks environment  (once this is verifiably working then i can close this issue)
but it should work i think.

**Comment by aliwicks** [comment]
Yeah so I tested for the case of a manual jar installation of graphframes0.8.1_spark3_s2.12.jar to the cluster:
<img width="1279" alt="Screen Shot 2022-02-04 at 12 55 17" src="https://user-images.githubusercontent.com/42868426/152533974-db10114d-6cc2-4fa4-b39d-96bdef1693a8.png">

and also installing the same graphframes package version by pointing it to maven:
<img width="1279" alt="Screen Shot 2022-02-04 at 12 58 20" src="https://user-images.githubusercontent.com/42868426/152534091-dd6479b8-22b1-48c3-bcd9-e281d4c338d9.png">

and then if your run all the code remembering to include the below setCheckpointDir() line of code at set up:
<img width="773" alt="Screen Shot 2022-02-04 at 12 54 36" src="https://user-images.githubusercontent.com/42868426/152534191-b64e726e-e648-406a-9345-c74f7fd8b485.png">
 
it works for both these cases using splink 2.1.5:
<img width="1013" alt="Screen Shot 2022-02-04 at 12 54 56" src="https://user-images.githubusercontent.com/42868426/152535582-c6de2120-c56f-479f-b366-0ba6cff87c2f.png">

Any other questions just shout.


Thanks again @RobinL @mamonu,

Ali

**Comment by mamonu** [comment]
Great news and thanks for testing it.
Closing this issue now but either comment on this one or open a new one if there is a problem 👍
