### ISSUE TITLE
sqlglot is not reliably producing spark SQL in _parse_top_level_case_statement_from_sql

### ISSUE THREAD

**Issue by nerskin** [moj-analytical-services/splink#269]
Hi,

I've been looking into `splink` as something that we might eventually use for large-scale probabilistic linkage projects at the Australian Bureau of Statistics, where I work. I've been impressed with what I've seen so far!

 In the course of my investigations I've hit a bug that affects how case statements are passed on to spark from the settings object. This bug is triggered when I try to use the spark sql function `SIZE` in case expressions for comparing array-valued variables.

Some self-contained python code that produces the issue is:

```
from splink import Splink

import pyspark

from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .getOrCreate()
   
data1 = [{"address":["123 ABC Street","456 DEF Street"],"source_dataset":1,"unique_id":1}]
data2 = [{"address":["456 DEF Street","789 GHI Street"],"source_dataset":2,"unique_id":1}]

df1 = spark.createDataFrame(data1)
df2 = spark.createDataFrame(data2)

settings = {
    "link_type": "link_only",
    "blocking_rules": [],
    "comparison_columns": [
        {
            "col_name": "address",
            "case_expression":"""case
            when address_l is null or address_r is null then -1
            when size(array_intersect(address_l,address_r)) > 0 then 1
            else 0
            end"""#essentially the same as splink.case_statements.sql_gen_case_stmt_array_intersect_2
        }
    ],
    "additional_columns_to_retain": [],
    "em_convergence": 0.02,
    "max_iterations": 2,
}
```

This generates an error with the message "AnalysisException: "Undefined function: 'ARRAY_SIZE'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 4 pos 9"."

I've tracked the problem down to line 67 of parse_case_statement.py where the sqlglot.expressions.If object is converted back to a SQL string using its `sql` method. The case statement becomes "CASE WHEN ARRAY_SIZE(ARRAY_INTERSECT(address_l, address_r)) > 0 THEN 1 END", which is not valid spark code - the ARRAY_SIZE function should just be SIZE. Valid spark SQL can be produced by replacing line 67 of parse_case_statement.py with `i.sql(dialect='spark')` (currently the dialect argument is left at its default, which is `None`), but this produces an `IF` statement rather than a `CASE` statement, which breaks things further downstream because other parts of the splink codebase rely on directly manipulating the text of `CASE` expressions.

Regards,
Nicholas Erskine

**Comment by RobinL** [comment]
Thanks.  We've come across a couple of other similar bugs caused by `sqlglot`.    Probably I was too hasty in adding it into Splink without testing a large enough range of SQL.

Probably best for you to use Splink 2.0.4 for now.  I'll see if I can do a PR to fix this in sqlglot.
