### ISSUE TITLE
`sqlglot` fixes

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#323]
Things that would be good to fix in SQLGlot:

## union all problem
```
import sqlglot 
sql = """
with a as (
(select * from table_a limit 10)
union all
(select * from table_b limit 10)
)
select * from a
"""

sqlglot.transpile(sql, read="spark", write="duckdb")
```

```
> ['WITH a AS (SELECT * FROM table_a LIMIT 10 UNION ALL (SELECT * FROM table_b LIMIT 10)) SELECT * FROM a']

```

The problem here is that UNION ALL when used with LIMIT needs each table in enclosing brackets i.e. the above should be:
```
> ['WITH a AS ((SELECT * FROM table_a LIMIT 10) UNION ALL (SELECT * FROM table_b LIMIT 10)) SELECT * FROM a']
```

**Comment by RobinL** [comment]
## concat problem

`concat` is not a sqlite function, you have to do `col_a || col_b`, but translation does not occur

**Comment by RobinL** [comment]
## Casting problem

Introduced a bug that caused Splink to break  between [1.23.1 and 1.24.0](https://github.com/tobymao/sqlglot/compare/v1.23.1...v1.24.0) - sqlite does not have a try_cast function

**Comment by tobymao** [comment]
casting problem in sqlite is fixed
