### ISSUE TITLE
Difference between dialects not solvable by `sqlglot`

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#324]
## concat problem

`concat` means different things in duckdb and pyspark.  

In `pyspark`, `concat(a,b)` returns null if a or b is null
In `duckdb`, `concat(a,b)` treats null as `''` when it concats

This could create problems for computing the number of comparisons generated by a blocking rules

**Comment by tobymao** [comment]
@RobinL this can be fixed in sqlglot, you need make this a first class concept and have each output the correct IR. this is similar to the different treatments of dates between duckdb and pyspark

**Comment by RobinL** [comment]
Thanks @tobymao  - that's very useful to know.

I've been roughly making notes of SQL transpilation issues here and [here](https://github.com/moj-analytical-services/splink/issues/323) so we can triage the ones we want to try and do PRs to `sqlglot` for.  Didn't want to litter issues in `sqlglot` itself until we can express them a bit more concisely and hopefully offer PRs.

Another thing we'd like to do is add support for Microsoft SQL server.  If we were to do this, this is something we are more likely to be able to do incrementally, rather than a 'big bang' PR that adds full support.  Is that way of working something you'd be amenable to? 

No obligation whatsoever, but if it'd be useful to discuss how we can contribute (and what we're using `sqlglot` for) I'm at:
```
a = ".gov.uk"
print("robin.linacre@digital.justice" + a)
```
Otherwise we're happy to continue doing sporadic PRs as and when we find time.

**Comment by tobymao** [comment]
i'll send you an email
