### ISSUE TITLE
Is it possible to get Splink working with a real-time data?

### ISSUE THREAD

**Issue by mmarinm** [moj-analytical-services/splink#386]
I don't see it in examples but I am curious if Splink would work with kafka and spark streaming api?

**Comment by mamonu** [comment]
It certainly works with batch data. 
So if you consider streaming data as constantly updating mini batches then yes it would.
Of course we havent used it in such a way (with streaming api) but if you would like to try a small example it would be interesting to see it  👍

**Comment by RobinL** [comment]
Splink3 (which is currently under development) has support for real time and incremental linkage.

Note this is not  explicitly geared to kafka or spark streaming - I don't know enough about technologies to know whether it's a perfect fit.

You can see a demo here:
https://github.com/moj-analytical-services/splink_demos/blob/splink3_demos/real_time_record_linkage.ipynb

**Comment by mmarinm** [comment]
Thanks I saw that, I don't think duckdb works for streaming use-case. I am interested in doing demo with spark streaming. I might open PR with example if I get it to work.

**Comment by RobinL** [comment]
Thanks.  Worth noting that the splink3 real time demo will also work with spark - you just need to substitute 

```
from splink.duckdb.duckdb_linker import DuckDBLinker
```

for 

```
from splink.spark.spark_linker import SparkLinker
```

and everything else stays the same.  (Still has the caveat that i'm not sure whether it's compatible with Spark streaming)
