### ISSUE TITLE
Connected Components - Adjust how we pull our unique ID columns

### ISSUE THREAD

**Issue by Th368MoJ** [moj-analytical-services/splink#451]
We should be using:
```
cols = linker._settings_obj._unique_id_input_columns
```
for this because the `unique_id` and `source_dataset` columns may be called somethine else, but it probably requires a little additional refactoring.

Specifically, i think we want a `composite_unique_id.py` that is responsible for these sort of manipulations.

It gets a bit tricky though e.g. [here](https://github.com/moj-analytical-services/splink/blob/dcd241dc5d204b1ac0eb893d7886f3b1eb27769d/splink/blocking.py#L18)

for now, `composite_unique_id.py` probably just wants a single function that takes a list of strings and returns `" || '-__-' || ".join(cols)`

_Originally posted by @RobinL in https://github.com/moj-analytical-services/splink/pull/444#discussion_r867814660_

**Comment by RobinL** [comment]
Closed by #459
