### ISSUE TITLE
Splink fails to install on docker Ubuntu 20.04

### ISSUE THREAD

**Issue by austinkat94** [moj-analytical-services/splink#481]
Hi,

I've been using splink locally for a few weeks now and am attempting to deploy this but am running into issues with getting it onto docker container. Error is below, this is erroring from pip install splink as when it is removed it works fine. Versions for software are below. If more info on the docker container is needed do let me know! main thing is it's using ubuntu:20.04.

pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.6)
Python 3.6.15
Pyspark 2.4.6 using Hadoop 2.7

/usr/bin/python3: can't find '__main__' module in '/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py'

ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2nlnkrgt Check the logs for full command output.

failed to solve: executor failed running [/bin/sh -c pip install splink==2.1.0]: exit code: 1

Any assistance on this is greatly appreciated!

**Comment by mamonu** [comment]
can you try this 👇?

`pip install --no-use-pep517 WHATEVER_YOU_WANT_TO_INSTALL`
[there is a thread here that is relevant perhaps ](https://twitter.com/codewithanthony/status/1240690187543298048)

**Comment by RobinL** [comment]
This has been dormant for a while so closing
