### ISSUE TITLE
Add density-based sampling to splink cluster studio

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#539]
Similar to [`by_sample_size`](https://github.com/moj-analytical-services/splink/blob/5b15b06b736a1a8431f3f81b030018218fea20e0/splink/cluster_studio.py#L203) but want to 'stratisfy'  by cluster density

**Comment by RossKen** [comment]
To be part of clustering work upcoming in the rest of 2023

**Comment by RobinL** [comment]
Closed by #1754
