### ISSUE TITLE
Allow a case expression which takes two columns as an input

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#65]
At the moment `sparklink` would probably break if you tried this because `col_name` doesn't make sense in the comparison columns

**Comment by samnlindsay** [comment]
I find myself easily getting confused between (a) matching values derived from two columns (e.g. `full_name`) and (b) matching conditions based on two columns.

I'm trying to think of useful examples that aren't easily replicated by adding derived columns*, such as: 
```
CASE WHEN l.first_name = r.first_name AND l.last_name = r.last_name THEN 2
WHEN l.first_name = r.last_name AND l.last_name = r.first_name THEN 1
ELSE 0 END
```
And this could still be referred to as `gamma_name_swap` or something even though `name_swap` isn't an actual column in the data.

*although I've just figured out how a derived column could solve this problem, and do it much better

**Comment by mamonu** [comment]
a derived column with both and then a jaccard sim on Q2grams would perhaps work here?
this is what im trying on swappy columns

**Comment by samnlindsay** [comment]
I was thinking of concatenating a sorted list of names (however you would do that in SQL) and matching on that:

John Adam Smith -> "AdamJohnSmith"
Adam John Smith -> "AdamJohnSmith"
Smith Adam Jonathan -> "AdamJonathanSmith"
