### ISSUE TITLE
`roc_chart_from_labels` fails if blocking rules refer to columns not used by model

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#656]
Supposing a model refers to `dmeta_first_name` in `blocking_rules_to_generate_predictions`, but 
- does not use `dmeta_first_name` in any of the `comparison`s
- does not include `dmeta_first_name` in `additional_columns_to_retain`

Then Splink will fail with a message like:
```
 cannot resolve '`dmeta_first_name_l`' given input columns: [pred.surname, ...
```

**Comment by ThomasHepworth** [comment]
See [here](https://github.com/moj-analytical-services/splink/issues/719) for more on this issue.

My opinion is that we should remove the blocking rule step and add it to its own evaluation method. This could calculate pairs completeness, reduction ratio and the harmonic mean of the two to give users an insight into how effective their BRs are.

Further Reasoning:
* This allows users to profile their blocking rules before running any code or at the end of the modelling phase when they're looking to evaluate accuracy.
* It helps with clarity by separating out blocking rule accuracy and model accuracy. While the two could be viewed in tandem, our current offerings .
* And I guess most importantly, it also kills off this issue in one.
