### ISSUE TITLE
`pd.NA` is treated as a string value when registered in a db.

### ISSUE THREAD

**Issue by ThomasHepworth** [moj-analytical-services/splink#657]
It's late, so I'll update this with some further information tomorrow morning as appropriate.

This impacts anywhere that either requests nulls be removed/adjusted or that compares strings. This rather tragically includes most of the modelling process.

The good news is that this is an issue with pandas and how pandas deals with csv files, rather than an issue with splink.

Working exmaple:
Or in code form:
```
from splink.duckdb.duckdb_linker import DuckDBLinker
import pandas as pd
import numpy as np

from tests.basic_settings import get_settings_dict

dict = {
    "unique_id": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "first_name": ["a", "b", "c", "d", np.nan,np.nan,np.nan,np.nan,np.nan,np.nan, pd.NA,pd.NA,pd.NA,pd.NA,pd.NA],
    "numbers": [1,2,3,4,5,6,7,8,9,pd.NA,pd.NA,pd.NA,pd.NA,pd.NA, np.nan]
}
df = pd.DataFrame(dict)

linker = DuckDBLinker(
    df,
)

linker.profile_columns("first_name")
```

![Screenshot 2022-07-19 at 20 50 06](https://user-images.githubusercontent.com/45356472/179836245-51a85d91-b529-4836-a990-bdcc302bb983.png)

**Comment by RossKen** [comment]
No clear way to fix this, so closing issue

**Comment by supermacro** [comment]
Pardon my naiveté, but why is there no clear way to fix this?

**Comment by RobinL** [comment]
I think there's no clear way to fix this _when going through pandas_.  The solution is to avoid pandas altogether. If you're using the duckdb backend, load the data in duckdb and give it to Splink as a duckdbpyrelation.  If you're using the spark backend do the equivalent in spark.

**Comment by supermacro** [comment]
All the docs in splink seem to imply to just pass in a dataframe, what's the API for passing in the data as a duckdbrelation?

**Comment by supermacro** [comment]
Claude is suggesting the following:

```python
from splink.exploratory import completeness_chart
from splink import DuckDBAPI
import duckdb

# Load the DataFrame into DuckDB
duckdb_conn = duckdb.connect()

# Create a DuckDB table from the pandas DataFrame
duckdb_conn.register("my_data", df)  # Register the DataFrame as a DuckDB table

# Create a DuckDB relation
duckdb_relation = duckdb_conn.table("my_data")

db_api = DuckDBAPI()
completeness_chart(duckdb_relation, db_api=db_api)```

Is this correct?
