### ISSUE TITLE
Unable to create `Comparison` for a function with a non-default schema

### ISSUE THREAD

**Issue by philip-hunt-kani** [moj-analytical-services/splink#666]
If I try to create a custom `Comparison` (for DuckDB) that calls a function in a non-default schema, a parsing error is raised.

I've tracked the problem down to the sqlglot parser not handling this case. A similar issue was raised and fixed for this a couple of days ago for a different dialect: https://github.com/tobymao/sqlglot/issues/250. A cursory glance looks like it should resolve the issue for other dialects too; however, splink currently doesn't support v4 of sqlglot so is unable to pick up this bugfix.

Fortunately, I don't really need to use a custom schema, so I can workaround this, but it would be good if it could be resolved in case anyone else has this issue and can't workaround it.

**Comment by RobinL** [comment]
Hi Philip,

If you upgrade to splink 3.0.1, we now support duckdb 4.0+

Grateful if you could let me know if that fixes the issue!    We haven't experimented too much with this - could you share the code that calls a function in a non-default schema so we have an example to replicate?

Thanks!

**Comment by philip-hunt-kani** [comment]
Sharing my code might be a bit complex. I had to create custom versions of the `distance_function_level` and `distance_function_at_thresholds` methods because they don't accept additional function params. However, if I still have this issue after the upgrade I'll post a test showing a minimal example.

At the moment, my DuckDB integration tests are failing due to a problem opening an in-memory DB connection after upgrading:

```
Failed with Error: IO Error: Trying to read a database file with version number 31, but we can only read version 33.
The database file was created with an older version of DuckDB.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.
```

**Comment by philip-hunt-kani** [comment]
It was a typo in my tests. I missed the trailing colon, i.e. `duckdb.connect(database=":memory")` instead of `duckdb.connect(database=":memory:")`, so it must have been using a physical file instead.

Looks like the sqlgot issue is still there. Doesn't look like the latest release (v4.2.0) contains the bugfix.

Here's the minimal tests to demonstrate the issue. First test fails whilst the second passes:

import unittest

import splink.duckdb.duckdb_comparison_library as c  # type: ignore
from splink.duckdb.duckdb_comparison_level_library import _mutable_params as cl_params  # type: ignore

import kani_splink_matching.linker_model_building.splink_comparisons as sc

```
class TestNonDefaultSchema(unittest.TestCase):
    def test_comparison_function_with_specific_schema_passes(self) -> None:
        c.distance_function_at_thresholds("foo", "example.test_function", [1, 2])

    def test_comparison_function_with_default_schema_passes(self) -> None:
        c.distance_function_at_thresholds("foo", "test_function", [1, 2])
```

**Comment by RobinL** [comment]
Thanks, very useful to have the example

**Comment by RossKen** [comment]
@ADBond to check and close if solved
