### ISSUE TITLE
Splink 3.2.0 requirements doesn't allow the use of DuckDB 0.5.0

### ISSUE THREAD

**Issue by palmaresk8** [moj-analytical-services/splink#756]
### What happens?

By installing the lattest Splink master with `pip install git+https://github.com/moj-analytical-services/splink.git` (commit `d80b0c72a71ebb93dfb2aef76f5f1ceb458f7623`) and trying to install the lattest DuckDB release (0.5.0) `pip install duckdb==0.5.0` I get the message 

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
splink 3.2.0 requires duckdb<0.5.0,>=0.4.0, but you have duckdb 0.5.0 which is incompatible.

By trying to use the library with `import splink` I get the error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "M:\Miniconda3\envs\py310\lib\site-packages\splink\__init__.py", line 3, in <module>
    __version__ = pkg_resources.require("splink")[0].version
  File "M:\Miniconda3\envs\py310\lib\site-packages\pkg_resources\__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "M:\Miniconda3\envs\py310\lib\site-packages\pkg_resources\__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (duckdb 0.5.0 (M:\Miniconda3\envs\py310\lib\site-packages), Requirement.parse('duckdb<0.5.0,>=0.4.0'), {'splink'})

Otherwise, if a install first DuckDB and then Splink, the setup uninstall the newer DuckDB release and install the (buggy) previous release:

>   Attempting uninstall: duckdb
    Found existing installation: duckdb 0.5.0
    Uninstalling duckdb-0.5.0:
      Successfully uninstalled duckdb-0.5.0

DuckDB 0.5.0 has several new improvements, incluiding Jaro Winkler function and several annoying bug fixes (specially for Windows user like me).

### To Reproduce

1. Install Splink:
`pip install git+https://github.com/moj-analytical-services/splink.git` (commit `d80b0c72a71ebb93dfb2aef76f5f1ceb458f7623`) or `pip install splink==3.2.0`

2. Install DuckDB:
`pip install duckdb==0.5.0`

### OS:

Windows

### Splink version:

3.2.0

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Thanks for the report.  This should be fixed by version 3.2.1 which I just released.  Let me know if it doesn't!
