### ISSUE TITLE
Linking on columns with different names

### ISSUE THREAD

**Issue by samnlindsay** [moj-analytical-services/splink#78]
`comparison_columns` in settings assumed columns both have the same name in two datasets. Fine for deduping, but not necessarily the case when linking (e.g. `l.birth_date = r.dob`)

**Comment by RobinL** [comment]
Yep.  This will be a bit annoying for users who will have to rename columns. 

But I think the additional complexity of code we'd need in sparklink isn't worth it - e.g. we'd have to fundamentally change the settings object.

**Comment by rjbks** [comment]
I assume this is still not possible with splink3? I have a Phone and CellPhone column in 1 dataset and I want to link either of those to a Phone column in a different dataset.
