### ISSUE TITLE
Missingness chart fails if tables don't have same columns

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#808]
### What happens?

The missingness chart fails for a linker with multiple tables if tables beyond the first are missing any columns contained in the first table.
Error is e.g.
```
duckdb.BinderException: Binder Error: Referenced column "house_number" not found in FROM clause!
```

### To Reproduce

```
import random

import pandas as pd

from splink.duckdb.duckdb_linker import DuckDBLinker

random.seed(220922)

def make_frame(n_rows):
    return pd.DataFrame(
        data={
            "id": range(0, n_rows),
            "forename": random.choices(["Tammy", "Emma", "Sophia", "Alice", "Danni", "Amy", None], k=n_rows),
            "surname": random.choices(["Beaumont", "Lamb", "Dunkely", "Capsey", "wyatt", "Jones", None], k=n_rows),
            "city": random.choices(["Brighton", "London", "Sheffield", "Bristol", None], k=n_rows),
            "house_number": random.choices([*range(1, 301), None], k=n_rows)
        }
    )

dfs = [make_frame(600), make_frame(600)]
dfs[1].rename(columns={"house_number": "street_number"}, inplace=True)
# or e.g.
# del dfs[1]["house_number"]

basic_settings = {
    "unique_id_column_name": "id",
    "link_type": "link_only",
}
linker = DuckDBLinker(dfs, basic_settings)
mc = linker.missingness_chart()
```

### OS:

Linux

### Splink version:

3.3.7

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by checkbook-org** [comment]
I had the same problem occur today, with two additional functions:
count_num_comparisons_from_blocking_rule
estimate_probability_two_random_records_match

**Comment by RossKen** [comment]
Need to create a clearer error to make it easier to understand for users
