### ISSUE TITLE
Error on find_matches_to_new_records() - term frequency tables not found

### ISSUE THREAD

**Issue by zzandi** [moj-analytical-services/splink#815]
### What happens?

Hi, 
when I call find_matches_to_new_records() on SparkLinker instance I get the following error:  `pyspark.sql.utils.AnalysisException: Table or view not found: __splink__df_concat_with_tf; line 25 pos 7`

The problem is that the term frequency tables have not been computed. One could solve the problem by first calling `_initialise_df_concat_with_tf(materialise=False)` to compute the tf table as the first sql task in the Pipeline queue. However, I was not sure if that would be the optimal solution. Or is there something missing in my code that would compute the tf table? 

Thanks in advance

### To Reproduce

`linker = SparkLinker(df) ` \
 `linker.load_settings_from_json("saved_settings.json") ` \
 `linker.compute_tf_table("city")` \
` record = {'unique_id': 1,
     'first_name': "John",
     'surname': "Smith",
     'dob': "1971-05-24",
     'city': "London",
     'email': "john@smith.net"
     }` \
 `df = linker.find_matches_to_new_records([record], blocking_rules=["l.first_name = r.first_name","l.surname = r.surname"])`

### OS:

windows 10

### Splink version:

3.3.8

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Hello.  yeah - this isn't great at the moment.  To fix, you also need to run 
`linker._initialise_df_concat_with_tf()`
see here for an example:
https://moj-analytical-services.github.io/splink/demos/example_real_time_record_linkage.html

We'll fix this properly at some point so you don't need theL
```
linker._initialise_df_concat_with_tf()
linker.compute_tf_table("city")
```
part

**Comment by zzandi** [comment]
Thank you for your reply. I'm looking forward for the proper fix.
