### ISSUE TITLE
Error in forming clusters with SparkLinker when using "linker.cluster_pairwise_predictions_at_threshold".

### ISSUE THREAD

**Issue by AJAYRapidops** [moj-analytical-services/splink#821]
Hi. I have used SparkLinker for linking the records, by doing so i am able to produce the predictions in terms of "matched probabilities" but when i pass the predictions dataframe to ""linker.cluster_pairwise_predictions_at_threshold"  for generating pairwise clusters, it throws error that: 
 **"AttributeError: 'DataFrame' object has no attribute 'physical_name'.**

**Comment by RobinL** [comment]
It's possible you're passing the pandas dataframe.  

So when you do:
`df_predictions = linker.predict()`

`df_predictions` is a SplinkDataFrame

You convert that into a pandas/spark dataframe with `df_predictions.to_pandas_dataframe()`

When you call `linker.cluster_pairwise_predictions_at_threshold`, you need to pass the original SplinkDataFrame
