### ISSUE TITLE
Comparison viewer filters doesn't use level labels

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#839]
In `linker.comparison_viewer_dashboard()` we have dropdowns for filtering on the various comparisons, but the dropdown options are only displayed by comparison vector value. It would be nice if these (also) had the corresponding `label_for_charts`, so as to not have to refer back to the vector values when exploring results.

**Comment by RossKen** [comment]
Agreed, using the gamma values is a pain. A simpler version of this could be to provide the chart labels so people could see what is what in the dashboard
