### ISSUE TITLE
In the docs, clarify that `register_table` returns a SplinkDataFrame

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#840]
See https://github.com/moj-analytical-services/splink/discussions/828

Need to have a `Returns:` part in the docstring

**Comment by rapidAmbakar** [comment]
Hey i can add to this! 
it's in splink/spark/spark_linker.py right ? because doc is redirecting to splink/linker.py

**Comment by RobinL** [comment]
Thanks!  You can add it in both, but the linker.py is prob slightly more important because that's what appears in the online docs.
