### ISSUE TITLE
Complex sql conditions break EM-training if not in conjunctive normal form

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#894]
### What happens?

If you have, within some comparison level, some logical formula that is not expressed in [conjunctive normal form](https://en.wikipedia.org/wiki/Conjunctive_normal_form) then the EM training step may break.

This is due to the fact that without passing `comparison_levels_to_reverse_blocking_rule` means they are computed with `Settings._get_comparison_levels_corresponding_to_training_blocking_rule`, ultimately using `ComparisonLevel._is_exact_match`, which splits the condition on `AND`s, parsing each bit of sql separately. This can then fail if there are any `AND`s nested below the top-layer of the condition, for instance in an expression such as `(A AND B) OR (C AND D)`. The `sqlglot` parser will see an expression `(A ` and fail due to lack of closing parenthesis: `sqlglot.errors.ParseError: Expecting ).`

This can be worked around by passing `comparison_levels_to_reverse_blocking_rule` (which comes with some mental overhead), or by rewriting the sql statement in conjunctive normal form, i.e. so that it is a series of smaller, `AND`-less clauses combined together with `AND`s (which could be complicated to derive in practice, and may hurt readability).

### To Reproduce

```py
import pandas as pd
import numpy as np

from splink.duckdb.duckdb_linker import DuckDBLinker
import splink.duckdb.duckdb_comparison_library as cl
import splink.duckdb.duckdb_comparison_level_library as cll
from splink import __version__

print(__version__)

np.random.seed(11)

companies = (
    "Wilbrinkingtons",
    "Green Camel Solutions",
    "Inverted Chessboard Industries",
    "Davis and Vadis",
    pd.NA,
)
names = (
    "Grolter",
    "Janklew",
    "Hartilty",
    "Ploblibb",
    "Swanglini",
    pd.NA
)

n_rows = 2000
df = pd.DataFrame(
    {
        "id": range(0, n_rows),
        "name": np.array(list(map(lambda x: np.random.choice(names, 1)[0], range(0, n_rows)))),
        "company_1": np.array(list(map(lambda x: np.random.choice(companies, 1)[0], range(0, n_rows)))),
        "company_2": np.array(list(map(lambda x: np.random.choice(companies, 1)[0], range(0, n_rows)))),
        "company_3": np.array(list(map(lambda x: np.random.choice(companies, 1)[0], range(0, n_rows)))),
    }
)
print(df.head())

def _col_is_null(col):
    return f"({col}_l IS NULL OR {col}_r IS NULL)"

sql_two_out_of_three_null = (
    f"(({_col_is_null('company_1')} AND {_col_is_null('company_2')}) OR "
    f"({_col_is_null('company_2')} AND {_col_is_null('company_3')}) OR "
    f"({_col_is_null('company_3')} AND {_col_is_null('company_1')}))"
)

settings = {
    "unique_id_column_name": "id",
    "link_type": "dedupe_only",
    "comparisons": [
        cl.exact_match("name"),
        {
            "output_column_name": "company_comparison",
            "comparison_levels": [
                {
                    "sql_condition": f"{_col_is_null('company_1')} AND {_col_is_null('company_2')} AND {_col_is_null('company_3')}",
                    "label_for_charts": "NULL",
                    "is_null_level": True,
                },
                {
                    "sql_condition": sql_two_out_of_three_null,
                    "label_for_charts": "2/3 NULL",
                },
                cll.exact_match_level("company_1"),
                cll.exact_match_level("company_2"),
                cll.exact_match_level("company_3"),
                cll.else_level(),
            ],
        }
    ]
}

linker = DuckDBLinker(df, settings)

linker.estimate_parameters_using_expectation_maximisation(
    "l.name = r.name"
)
```

### OS:

Mac OS

### Splink version:

3.4.2

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by tobymao** [comment]
i'm not sure if it's relevant, but sqlglot has the ability to convert a boolean expression into CNF or DNF

https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/normalize.py#L6

**Comment by NickCrews** [comment]
I just ran into this problem independently, so that's a +1 to its user impact.
