### ISSUE TITLE
HTML generated from `comparison_viewer_dashboard` broken in Chrome

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#895]
### What happens?

If I run

```python
linker.comparison_viewer_dashboard(
    df_predict,
    "comparision_viewer.html",
    overwrite=True,
)
```

the resulting html file is generated, but if I open it in Chrome I see:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/10820686/201988748-3ebff822-7616-4b14-b0a7-7063f7d79ba2.png">

Here is the resulting file I'm trying to view:
[comparision_viewer.html.zip](https://github.com/moj-analytical-services/splink/files/10014979/comparision_viewer.html.zip)

[The docs](https://moj-analytical-services.github.io/splink/linkerqa.html#splink.linker.Linker.comparison_viewer_dashboard) claim that I can just load the html file in my browser and it should work. Do I need to install vega or something? I also am not sure what is going on with the minified javascript at the top of the page that looks like it is supposed to be inside a <script>, but it looks to be cut off?

### To Reproduce

I haven't tried to repro on master, only on 3.4.1.

### OS:

macOS 12.6

### Splink version:

3.4.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Not sure what's going on here - that file loads fine for me in Chrome...

**Comment by NickCrews** [comment]
Sorry, it's my fault. I was serving the file from vscode with a live server (web dev habit) instead of just plain opening it statically as a file. It works fine when I just open the file. Excuse the noise!
