### ISSUE TITLE
splink using spark is slower and complex then 2.1.14 version

### ISSUE THREAD

**Issue by abhishek-ksolve** [moj-analytical-services/splink#908]
### What happens?

Hey I ran this new version of splink on a spark, And I found that the latest version of splink is much slower than the previous version 2.1.14, And also the parameters were too simple, but the newest version has complex parameters. May I know if my statement is correct or not?Is this version not made for spark?

### To Reproduce

Supposed to be faster than the previous version 2.1.14 for spark.

### OS:

ubuntu

### Splink version:

3.4.2

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
For most jobs, Splink 3 is significantly faster than Splink 2 using Spark.  Do you have an reproducible example of a job that's slower with Splink 3?

**Comment by RobinL** [comment]
Closing in favour of https://github.com/moj-analytical-services/splink/discussions/909
