### ISSUE TITLE
`RANDOM()` / `RAND()` backend compatibility

### ISSUE THREAD

**Issue by samnlindsay** [moj-analytical-services/splink#910]
https://github.com/moj-analytical-services/splink/blob/83f80c811fff2b611aeee4002f5fc867f4daf6bb/splink/splink_comparison_viewer.py#L32

Comparison viewer code assumes `RANDOM()` works on all backends:
- **DuckDB** - `RANDOM()` only
- **Athena** - `RAND()` or `RANDOM()`
- **Spark** (2.4) - `RAND()` only :x: 
  - FAILS on v2.4 but works in v3.0+

**Comment by RossKen** [comment]
Default Spark support v3.0+ so closing this issue
