### ISSUE TITLE
Improve documentation for `estimate_m_from_pairwise_labels`

### ISSUE THREAD

**Issue by kylebutts** [moj-analytical-services/splink#928]
Hi there, thanks for your work on this package! I ended up here cause it's the most versatile record linking package I could fine, so kudos!!

I'm looking at the documentation and see some suggestions that the linking algorithm can be improved from providing training data. I think `linker_pairwise.register_table(df_labels, "labels")` and `linker.estimate_m_from_pairwise_labels("labels")` are the two functions I would use, but the documentation is scarce. 

Looking through the source code I see `block_from_labels` with the following documentation:
```python
"""Create pairwise record comparisons corresponding to the ID pairs in a labels
table
The table of labels should be in the following format, and should be registered
with your database:
|source_dataset_l|unique_id_l|source_dataset_r|unique_id_r|clerical_match_score|
|----------------|-----------|----------------|-----------|--------------------|
|df_1            |1          |df_2            |2          |0.99                |
|df_1            |1          |df_2            |3          |0.2                 |
Note that `source_dataset` and `unique_id` should correspond to the values
specified in the settings dict, and the `input_table_aliases` passed to the
`linker` object.
"""
```
If this is the correct format (including column names) to use `linker.estimate_m_from_pairwise_labels`, I'd be happy to submit a pull request to add that. I'm assuming `clerical_match_score` determines the "certainty of this manual label" and that a value of `1` is "full confidence", right?

**Comment by kylebutts** [comment]
Also, looking at https://github.com/moj-analytical-services/splink/blob/48158dd564c4d144d405a7d141e0130b43c0c9d7/splink/m_from_labels.py#LL19, I'm not seeing the option to pass `clerical_match_score` to `block_from_labels` which defaults to `clerical_match_score = False`

**Comment by RobinL** [comment]
Hi Kyle,

Thanks for this and sorry for the lack of documentation.    Yes, if you're willing to add a docstring within `linker.py` a PR  would be greatly appreciated.  To help a little, I've just added a brief working example to the list of examples in the docs [here](https://moj-analytical-services.github.io/splink/demos/example_pairwise_labels.html).

In answer to your questions, that is the correct format for the table, except that the `clerical_match_score` column isn't needed (and if provided will be ignored).  You're also correct in saying there is no option currently to pass clerical match scores in.

Currently, the algorithm assumes that each row in the labels dataset represents a sure match (i.e. 100% match probability, fffectively that `clerical_match_score` is 1.0 for each row).

It wouldn't be too difficult to update the method to allow for non-100% `clerical_match_scores`, but currently that functionality does not exist.  The relevant line is [here](https://github.com/moj-analytical-services/splink/blob/48158dd564c4d144d405a7d141e0130b43c0c9d7/splink/m_from_labels.py#L29) I think.


Robin

**Comment by kylebutts** [comment]
Great, thanks for the confirmation! I wasn't sure if I had to run a build step to compile the docs. If so, let me know and I'll add that commit to PR #938!

Thanks for the offer Robin; I'll probably bug you at some point :-)

One quick question:
It seems like you can have multiple training sources. Is it possible to train using labels and also the traditional expectation maximization approach?

**Comment by RobinL** [comment]
@kylebutts - The answer is yes.  If you use multiple estimation routines, the estimates get averaged.  But you can see the individual estimates as follows:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/2608005/208069376-a691896a-7849-4d48-8682-e7d0178f3db3.png">
