### ISSUE TITLE
Training blocking rule produces error

### ISSUE THREAD

**Issue by ashczq** [moj-analytical-services/splink#929]
### What happens?

When I train the blocking rule on the 'name' column, it gives the error: `Column 'nan' does not exist`
The blocking rules work for the other columns is there a reason why this is occurring, can't seem to find any documentation that would lead to this error? 

![image](https://user-images.githubusercontent.com/49942750/206643762-9f5f0886-f3bd-41c7-b243-686b2ffc487a.png)

### To Reproduce

training_blocking_rule = "l.name = r.name"
training_session_fname_sname = spark_linker.estimate_parameters_using_expectation_maximisation(training_blocking_rule)

### OS:

Windows

### Splink version:

3.0.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
To help, we'd need to see your full settings object please

**Comment by ashczq** [comment]
Sure i've included my code as well as the last training block which leads to the error as shown above. Thanks for the help.
```
cc_spark_lower = company_spark.select('unique_id',
    *[lower(col(col_name)).name(col_name) for col_name in ['name','description','head_office_location','website_1',
                                                           'ownership']]
)

company_settings = {
    "link_type": "dedupe_only",
    "comparisons": [
        cl.jaro_winkler_at_thresholds("name", 0.7),
        cl.levenshtein_at_thresholds("description"),
        cl.exact_match("head_office_location", term_frequency_adjustments=True),
        cl.levenshtein_at_thresholds("website_1"),
        cl.exact_match("ownership")
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
}

spark_linker = SparkLinker(
    cc_spark_lower,
    company_settings
)

spark_linker.estimate_u_using_random_sampling(target_rows=1e6)
```
![image](https://user-images.githubusercontent.com/49942750/206667073-b160ab45-13d1-4fd8-80dc-a14fc1050b2c.png)

```
training_blocking_rule = "l.name = r.name"
training_session_name = spark_linker.estimate_parameters_using_expectation_maximisation(training_blocking_rule)
```

**Comment by RobinL** [comment]
Does the traceback provide more detail?  Sometimes it shows the SQL statement.  The placement of the nan would help us debug.

I think it's fairly likely it's due to 
<img width="801" alt="image" src="https://user-images.githubusercontent.com/2608005/206673664-6635f554-57fa-4a19-9d2c-677abb39416f.png">

You could try setting `target_rows` to a much higher value e.g. `target_rows=1e8`

**Comment by ADBond** [comment]
Haven't looked at this in detail, but this can happen if your `training_blocking_rule` produces no matches - see #852. Looking at the output from the u-training step suggests that it may well be the case here.

**Comment by ashczq** [comment]
In my case it would be more likely that the other columns excluding `name` would produce no matches, would this be the reason? Also i realised that the warning for `name` was exact match but i was using jaro-winkler. Have provided the traceback below for more details as well.
 
![image](https://user-images.githubusercontent.com/49942750/206944140-894c95a2-a5da-45b9-994e-4774b956744d.png)

**Comment by RobinL** [comment]
Thanks for the update
