### ISSUE TITLE
`__splink_df_concat_with_tf_left` table not found

### ISSUE THREAD

**Issue by andrewbovey** [moj-analytical-services/splink#949]
I'm attempting to use splink in a Databricks environment, with spark version 3.2.1. I'm using the latest version of splink, and running splink.databricks.enable_splink.enable_splink() before any other commands.

I'm specifically interested in the SparkLinker. There are no examples of Linking with the SparkLinker in the docs at this time, but when I attempt to swap the SparkLinker into the DuckDBLinker example, I hit an AnalysisException while estimating probability two random records match. Does the missing __splink_df_concat_with_tf_left mean that the SplinkLinker requires a different setup than the DuckDBLinker?

```
from splink.databricks.enable_splink import enable_splink
from splink.spark.spark_linker import SparkLinker
import splink.spark.spark_comparison_library as cl

enable_splink(spark)

settings = {
    "link_type": "link_only",
    "blocking_rules_to_generate_predictions": [
        "l.first_name = r.first_name",
        "l.surname = r.surname",
    ],
    "comparisons": [
        cl.levenshtein_at_thresholds("first_name", 2),
        cl.levenshtein_at_thresholds("surname"),
        cl.levenshtein_at_thresholds("dob"),
        cl.exact_match("city", term_frequency_adjustments=True),
        cl.levenshtein_at_thresholds("email"),
    ],       
}

df_l = (spark
  .read.format('parquet')
  .options(header='true')
  .load('fake_df_l.parquet')
)

df_r = (spark
  .read.format('parquet')
  .options(header='true')
  .load('fake_df_r.parquet')
)

linker = SparkLinker([df_l, df_r], settings, input_table_aliases=["df_left", "df_right"], spark=spark)
deterministic_rules = [
    "l.first_name = r.first_name and levenshtein(r.dob, l.dob) <= 1",
    "l.surname = r.surname and levenshtein(r.dob, l.dob) <= 1",
    "l.first_name = r.first_name and levenshtein(r.surname, l.surname) <= 2",
    "l.email = r.email"
]

linker.estimate_probability_two_random_records_match(deterministic_rules, recall=0.7)
```

> AnalysisException: Table or view not found: __splink_df_concat_with_tf_left; line 20 pos 7;

> 'WithCTE
:- 'CTERelationDef 2
:  +- 'SubqueryAlias __splink__df_blocked_data
:     +- 'Union false, false
:        :- 'Union false, false
:        :  :- 'Union false, false
:        :  :  :- 'Project ['l.source_dataset AS source_dataset_l#672, 'l.unique_id AS unique_id_l#673, 'r.source_dataset AS source_dataset_r#674, 'r.unique_id AS unique_id_r#675, 'l.first_name AS first_name_l#676, 'r.first_name AS first_name_r#677, 'l.surname AS surname_l#678, 'r.surname AS surname_r#679, 'l.dob AS dob_l#680, 'r.dob AS dob_r#681, 'l.city AS city_l#682, 'r.city AS city_r#683, 'l.tf_city AS tf_city_l#684, 'r.tf_city AS tf_city_r#685, 'l.email AS email_l#686, 'r.email AS email_r#687, 0 AS match_key#688]
:        :  :  :  +- 'Filter (1 = 1)
:        :  :  :     +- 'Join Inner, (('l.first_name = 'r.first_name) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1))
:        :  :  :        :- 'SubqueryAlias l
:        :  :  :        :  +- 'UnresolvedRelation [__splink_df_concat_with_tf_left], [], false
:        :  :  :        +- 'SubqueryAlias r
:        :  :  :           +- 'UnresolvedRelation [__splink_df_concat_with_tf_right], [], false
:        :  :  +- 'Project ['l.source_dataset AS source_dataset_l#689, 'l.unique_id AS unique_id_l#690, 'r.source_dataset AS source_dataset_r#691, 'r.unique_id AS unique_id_r#692, 'l.first_name AS first_name_l#693, 'r.first_name AS first_name_r#694, 'l.surname AS surname_l#695, 'r.surname AS surname_r#696, 'l.dob AS dob_l#697, 'r.dob AS dob_r#698, 'l.city AS city_l#699, 'r.city AS city_r#700, 'l.tf_city AS tf_city_l#701, 'r.tf_city AS tf_city_r#702, 'l.email AS email_l#703, 'r.email AS email_r#704, 1 AS match_key#705]
:        :  :     +- 'Filter (1 = 1)
:        :  :        +- 'Join Inner, ((('l.surname = 'r.surname) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1)) AND NOT 'COALESCE((('l.first_name = 'r.first_name) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1)), false))
:        :  :           :- 'SubqueryAlias l
:        :  :           :  +- 'UnresolvedRelation [__splink_df_concat_with_tf_left], [], false
:        :  :           +- 'SubqueryAlias r
:        :  :              +- 'UnresolvedRelation [__splink_df_concat_with_tf_right], [], false
:        :  +- 'Project ['l.source_dataset AS source_dataset_l#706, 'l.unique_id AS unique_id_l#707, 'r.source_dataset AS source_dataset_r#708, 'r.unique_id AS unique_id_r#709, 'l.first_name AS first_name_l#710, 'r.first_name AS first_name_r#711, 'l.surname AS surname_l#712, 'r.surname AS surname_r#713, 'l.dob AS dob_l#714, 'r.dob AS dob_r#715, 'l.city AS city_l#716, 'r.city AS city_r#717, 'l.tf_city AS tf_city_l#718, 'r.tf_city AS tf_city_r#719, 'l.email AS email_l#720, 'r.email AS email_r#721, 2 AS match_key#722]
:        :     +- 'Filter (1 = 1)
:        :        +- 'Join Inner, ((('l.first_name = 'r.first_name) AND ('LEVENSHTEIN('r.surname, 'l.surname) <= 2)) AND NOT ('COALESCE((('l.first_name = 'r.first_name) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1)), false) OR 'COALESCE((('l.surname = 'r.surname) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1)), false)))
:        :           :- 'SubqueryAlias l
:        :           :  +- 'UnresolvedRelation [__splink_df_concat_with_tf_left], [], false
:        :           +- 'SubqueryAlias r
:        :              +- 'UnresolvedRelation [__splink_df_concat_with_tf_right], [], false
:        +- 'Project ['l.source_dataset AS source_dataset_l#723, 'l.unique_id AS unique_id_l#724, 'r.source_dataset AS source_dataset_r#725, 'r.unique_id AS unique_id_r#726, 'l.first_name AS first_name_l#727, 'r.first_name AS first_name_r#728, 'l.surname AS surname_l#729, 'r.surname AS surname_r#730, 'l.dob AS dob_l#731, 'r.dob AS dob_r#732, 'l.city AS city_l#733, 'r.city AS city_r#734, 'l.tf_city AS tf_city_l#735, 'r.tf_city AS tf_city_r#736, 'l.email AS email_l#737, 'r.email AS email_r#738, 3 AS match_key#739]
:           +- 'Filter (1 = 1)
:              +- 'Join Inner, (('l.email = 'r.email) AND NOT (('COALESCE((('l.first_name = 'r.first_name) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1)), false) OR 'COALESCE((('l.surname = 'r.surname) AND ('LEVENSHTEIN('r.dob, 'l.dob) <= 1)), false)) OR 'COALESCE((('l.first_name = 'r.first_name) AND ('LEVENSHTEIN('r.surname, 'l.surname) <= 2)), false)))
:                 :- 'SubqueryAlias l
:                 :  +- 'UnresolvedRelation [__splink_df_concat_with_tf_left], [], false
:                 +- 'SubqueryAlias r
:                    +- 'UnresolvedRelation [__splink_df_concat_with_tf_right], [], false
+- 'Sort [cast('match_key as int) ASC NULLS FIRST], true
   +- 'Aggregate ['match_key], [count(1) AS row_count#671L, 'match_key]
      +- 'SubqueryAlias __splink__df_blocked_data
         +- 'CTERelationRef 2, false

**Comment by andrewbovey** [comment]
I've found the reason for this issue. When _initialise_df_concat_with_tf() gets run, it will skip the creation of __splink_df_concat_with_tf_left if __splink__df_concat_with_tf exists in your spark.catalog.currentDatabase(). 

Rename or delete the __splink__df_concat_with_tf table if you are hitting the error that I was above.

**Comment by RobinL** [comment]
Thanks Andrew for posting the solution.  This looks like something we will want to fix around the caching of the __splink__df_concat_with_tf table, and having this example is useful
