### ISSUE TITLE
having a hard time invalidating cache with spark

### ISSUE THREAD

**Issue by funkysandman** [moj-analytical-services/splink#952]
### What happens?

Using Splink 3.5.1 in the Databricks environment, I am able to successfully perform a prediction for a link_and_dedupe.
All subsequent attempts with different right-hand input datasets return the previous predictions instead of performing a new prediction.  Restarting the cluster seems to be the only way to reset the cache.

I've tried setting the break_lineage_method="delta_lake_table" parameter which results in a delta_lake_table named default.__splink__df_predict_06a8a64

I've tried dropping this table but it comes back with the exact same original prediction
I've also tried 'Refresh table default.__splink__df_predict_06a8a64' with no change 

### To Reproduce

in spark environment using Splink 3.5.1 perform a dedupe on 2 input datasets and examine the prediction dataframe

repeat the operation with new input datasets (same structure but different content and number of records) and the prediction output dataframe remains the same

### OS:

12.0 ML (includes Apache Spark 3.3.1, Scala 2.12)

### Splink version:

3.5.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
Hiya.  Sorry about this.  It's on the list of things to fix.

In the meantime, to invalidate the cache, you want to drop all tables beginning with `__splink` from the database.  To get a list it'd be something like:

```
splink_tables = spark.sql(
            f"show tables from my_databse like '__splink*'"
        )
```

**Comment by RobinL** [comment]
Hmm - that's odd.  Fuller code would be something like:

```
splink_tables = self.spark.sql(
    f"show tables from {self.splink_data_store} like '__splink__*'"
)
temp_tables = splink_tables.filter("isTemporary").collect()
drop_tables = list(
    map(lambda x: x.tableName, filter(lambda x: x.isTemporary, temp_tables))
)
# drop old temp tables
# specifying a catalog and database doesn't work for temp tables.
for x in drop_tables:
    self.spark.sql(f"drop table {x}")
```

**Comment by funkysandman** [comment]
ok, I think I was only deleting the non-temporary splink tables... I wasn't getting them all. 

 However, I think it is necessary to delete both **regular and temporary**   __splink__ tables

**Comment by RobinL** [comment]
Thanks - you're probably right.  Glad you've found a workaround for now

**Comment by RossKen** [comment]
Closing as referenced in #961
