### ISSUE TITLE
comparison library not generating settings for distance_function_at_thresholds

### ISSUE THREAD

**Issue by funkysandman** [moj-analytical-services/splink#975]
### What happens?

Hi
I'm unable to generate settings when I try to use distance_function_at_thresholds with the comparison library.
Also, thresholds seem to be mandatory as opposed to optional.

returns:

TypeError: __init__() got an unexpected keyword argument 'igher_is_more_similar'

I've tried several variations without any luck.
Please let me know if I'm missing something!
Sandy

### To Reproduce

spark.udf.registerJavaFunction("cosine_distance", "uk.gov.moj.dash.linkage.CosineDistance", types.DoubleType())

import splink.spark.spark_comparison_library as cl

settings = {
    "link_type": "dedupe_only",
    "comparisons": [
        cl.distance_function_at_thresholds("street_numbers","cosine_distance",0.5)]
}

will return:
TypeError                                 Traceback (most recent call last)
File <command-2900638926777177>:6
      1 import splink.spark.spark_comparison_library as cl
      3 settings = {
      4     "link_type": "dedupe_only",
      5     "comparisons": [
----> 6         cl.distance_function_at_thresholds("street_numbers","cosine_distance",0.5)]
      7 }

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/splink/comparison_library.py:133, in DistanceFunctionAtThresholdsComparisonBase.__init__(self, col_name, distance_function_name, distance_threshold_or_thresholds, higher_is_more_similar, include_exact_match_level, term_frequency_adjustments, m_probability_exact_match, m_probability_or_probabilities_lev, m_probability_else)
    131         kwargs["distance_function_name"] = distance_function_name
    132         kwargs["igher_is_more_similar"] = higher_is_more_similar
--> 133     level = self._distance_level(**kwargs)
    134     comparison_levels.append(level)
    136 comparison_levels.append(
    137     self._else_level(m_probability=m_probability_else),
    138 )

TypeError: __init__() got an unexpected keyword argument 'igher_is_more_similar'

### OS:

12.0 ML (includes Apache Spark 3.3.1, Scala 2.12)

### Splink version:

3.5.2

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment]
Apologies, this is due to an error within `distance_function_at_thresholds`. I will submit a fix for this today, but in the meantime if you need to you can work-around the problem by manually defining a comparison using the comparison level library directly (which shouldn't have the error) - see [the docs on comparison leves](https://moj-analytical-services.github.io/splink/topic_guides/customising_comparisons.html#method-2-comparisonlevels) for more detail.

**Comment by ADBond** [comment]
This is now fixed on `master`, and will be included in the next release, which should be relatively soon.
