### ISSUE TITLE
bug: sqlglot dep shouldn't be pinned to a specific version

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#991]
### What happens?

sqlglot is pinned to exactly "5.1.0". I also want to install Ibis, which requires a different version of sqlglot. They conflict and therefore pip won't let me install both libs at the same time.

Usually, as a lib, you want to require as loose of a range on your deps as possible, otherwise this sort of conflict between libs is likely to happen.

Can we simply do `sqlglot>=5.1.0` instead? This might end up being TOO loose, and there might be an issue with sqlglot=6.0.0, but if this happens, it is very easy for me as an application developer to get around this by adding an additional `sqlglot!=6.0.0` dep to my app's deps. It's easy from the app's perspective to make requirements more restrictive, but very hard to make them less restrictive, so generally I think libraries should err on the side of too loose.

I tried this fix on my branch, but `poetry update` had a bunch of errors, so I can leave that to you as an easy fix.

### To Reproduce

`echo $'ibis-framework>=4\nsplink>=3' > requirements.txt && pip install -r requirements.txt`

### OS:

macOS 12.6

### Splink version:

all splink versions >3 suffer from this

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by NickCrews** [comment]
I'm writing a PR now

**Comment by RobinL** [comment]
Thanks Nick.

In terms of this history of this, we've been using sqlglot since the very early days of the library where the API was changing quite a bit between major versions.  As a result, we kept on running into problems backward incompatibility - i.e. of the latest version being incompatible with the Splink codebase.  IIRC there was also a bug earlier in the 5.x series that affected us.  Hence we pinned the version.

Totally agree this isn't great.  I would generally prefer pinning to a particular major release, since there's no guarantee the API won't change in a backwards-incompatible way between major versions.   

I notice SQLGlot is now at `10.5.6`.  Are you aware of any issues that would prevent us requiring version 10 of SQLGlot?  (i think the `pyproject.toml` syntax would be `sqlglot = "^10"`.  Would that be incompatible with Ibis?

**Comment by NickCrews** [comment]
Currently, Ibis supports sqlglot 10, so this would work for me in the short term, but I think it would be short-sighted.

Ibis inevitably is going to update to require sqlglot 11, and then we're in the same place, forced to update in lock step with them. Or, someone besides me might want to use some other 3rd lib that requires sqlglot 8, and then there is simply no solution, either me or that person is going to be out of luck. So I think it would be better if we can support multiple major versions of sqlglot.

I recognize that there are some breaking changes in there that we would have to add some compat wrappers around, eg
```python
def _get_sqlglot_dialect_quotes(dialect: sqlglot.Dialect):
    try:
        # For sqlglot < 6.0.0
        quotes = dialect.identifiers
        quote = '"' if '"' in quotes else quotes[0]
        start = end = quote
    except AttributeError:
        # For sqlglot >= 6.0.0
        start = dialect.identifier_start
        end = dialect.identifier_end
    return start, end
```
which is in the PR above. But if you look in the PR above, I only needed to make really 3 changes in order to update to sqlglot 10. 2 of those changes were compatible with sqlglot 5, so we would have had to do that effort anyways. The example above is the only case where I needed to do some try/except ugliness to support multiple sqlglot versions. I think that one case is a small price to pay.

And, sqlglot 5 came out less than 6 months ago, so cutting support for that really isn't giving people much time to upgrade.

Note that [Ibis requires sqlglot>=10,<11](https://github.com/ibis-project/ibis/blob/8f33775b72249125d928470389dd91baad633473/pyproject.toml#L35), so they aren't being particularly good citizens either :), in an ideal world they should be support multiple major versions of sqlglot too :)

> I would generally prefer pinning to a particular major release, since there's no guarantee the API won't change in a backwards-incompatible way between major versions

This might be true, but as an application developer it's easy to fix. If sqlglot 11 comes out, pip decides to install that for me, and then I get breakages, I can just add a `sqlglot<11` to my application's dependencies and I'm fine. I can file a bug here and it will get eventually fixed, but I'm not blocked. I would prefer this situation to what I currently have to do (make a fork with some patches)

**Comment by RobinL** [comment]
OK - that all makes sense - you've convinced me!  I'm happy with supporting 5+, or moving to supporting 6+ if you'd prefer.  Will take a look at the PR as soon as i have a spare moment
