### ISSUE TITLE
feat: drop python 3.6 support

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#994]
As I wrote #992, I was getting dragged down by python 3.6:

1. It's hard to find libs that support the wide range of 3.6 up to 3.11+. You often have to specify multiple versions of libs depending on the version of python. eg in pyproject.toml
```
pyarrow = [
    {version = "^6.0.0", python = "<3.7"},
    {version = "^7.0.0", python = ">=3.7"},
]
```
This is hard because it forces our code base to be compatible with multiple versions of the other libs, for instance
```
def _get_sqlglot_dialect_quotes(dialect: sqlglot.Dialect):
    try:
        # For sqlglot < 6.0.0
        quotes = dialect.identifiers
        quote = '"' if '"' in quotes else quotes[0]
        start = end = quote
    except AttributeError:
        # For sqlglot >= 6.0.0
        start = dialect.identifier_start
        end = dialect.identifier_end
    return start, end
```
2. python 3.6 reached end of life in dec 2021, a year ago. Many other modern python libs don't support it anymore.
3. We cant use `from __future__ import annotations` in 3.6 which makes type hints much more annoyting, and probably limits us in other modern language features.
4. splink doesn't even currently work in 3.6: ever since https://github.com/moj-analytical-services/splink/commit/6b87ddaa34a714bcc14d5ec12c48c53b211b8f9e, when I added the `from __future__ import annotations` line, 3.6 will crash. No one seems to be complaining.
5. We have complicated tests for 3.6 at .github/workflows/pytest_36_compatibility.yml. It would be nice to delete this file.

**Comment by mamonu** [comment]
As the person that tried to make splink compatible with 3.6 I absolutely agree. 
3.6 is a lost cause. I leave the decision of taking out all the 3.6 related tests/ conditional imports to others (like the splink lead developers) but I totally agree with your point of view.

**Comment by NickCrews** [comment]
Thanks for the opinion @mamonu! I will put in the effort to write some PRs if we get approval from maintainers.

**Comment by RobinL** [comment]
Thanks Nick - yeah also agree we should drop 3.6 support

**Comment by NickCrews** [comment]
@RobinL see the PR above
